### ISSUE TITLE
give nested OBJECT types the items() functionality

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1003]
For datamodels, a datamodel itself has `items()`. The `meta` attribute also has `items()`. However, any other nested property, of type `object` does not have `items()`. An example would be `adatamodel.meta.coordinates`.

Give any datamodel property which is an `object` the `items()` method. Oh, and maybe the rest of the dict-like methods too?

**Comment by bernie-simon** [comment]
I've added __iter__ and items() to ObjectNode to make it easier to iterate over collections of metadata items. I didn't add full support for dictionary methods because the datamodels code is styled to have metatdata look like object attributes, not dictionaries.
