### ISSUE TITLE
refactor level3 pipelines for consistency

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1013]
As per [this comment](https://github.com/STScI-JWST/jwst/pull/1010#pullrequestreview-46668134), review all level3 pipelines for I/O and API consistency.

**Comment by hbushouse** [comment]
@stscieisenhamer has this been addressed in the various updates included in B7.1 or should we keep it open for B7.2, in order to review all level-3 pipelines (image3, spec3, ami3, coron3, and tso3)?

**Comment by stscieisenhamer** [comment]
naw. close it up. Basically what is left is in #1316.

**Comment by jdavies-st** [comment]
I would like to refactor the `image3` pipeline to loop through products, just as the spec3 pipeline does.  Generally, the `image3` pipeline only has one product, but for consistency.  I can open a new issue on this though, and it can be deferred to 7.2 I think.

**Comment by stscieisenhamer** [comment]
imho that should be its own issue.

**Comment by hbushouse** [comment]
Looping over multiple products in calimage3 may come in useful for handling the direct images that are related to grism (WFSS) observations. The direct images can be obtained in more than 1 filter, in which case we need to build a combined/resampled product for each filter, as well as a combined/resampled product from images in all filters (the so-called "uber" image that gets used to construct a WFSS source catalog). So go ahead and open an issue for calimage3 in B7.2.
