### ISSUE TITLE
Save the scale factor in the group_scale step.

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1023]
The `group_scale` step applies a factor to the data for the case that the number of frames per group is not an integral power of 2.  That affects the gain.  Therefore, it would be helpful if `group_scale` saved that scale factor in the metadata.  Any step that uses the gain (e.g. `jump`, `ramp_fit`) will need to divide the gain reference file values by that scale factor.

**Comment by hbushouse** [comment]
I'm not sure how this affects the gain. The rescaling that's applied by group_scale is to fix the fact that the scaling done on-board was not correct. Hence after group_scale is applied the data are (theoretically) back onto their native scale (the averaging has been done properly). Of course I could easily be missing something here.

**Comment by philhodge** [comment]
You're probably right.  If the gain reference file was made using data that had been corrected for the group_scale factor, then the gain would match science data after group_scale correction, yes.
