### ISSUE TITLE
Update WCS in extract_1d output

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1034]
Currently the 1D data model created as output from the extract_1d step still contains the same 2D/3D WCS object info copied from the input spectrum data model. The 1D output should have an updated WCS object that contains:

1) A constant RA/Dec value for all pixels, perhaps corresponding to the center of the extraction/summation aperture used to perform the extraction

2) A table of wavelength values that document the pixel-to-wavelength transform (essentially the same as the column of wavelength values already included in the output spectral data table).

In addition to updating the WCS object info (contained in the ASDF meta data) in this fashion, we should also look into recording this info in some way in FITS standard WCS keywords in the output table header. At the very least, the wavelength array might be representable via CRPIX1, CRVAL1, and CDELT1 keyword values, at least in an approximate way (depending on whether the wavelength scale has a constant delta-lambda per pixel). Would also be nice to represent the constant RA/Dec values somehow.

**Comment by nden** [comment]
@philhodge Can this be closed, now that #1099 is merged?

**Comment by philhodge** [comment]
Closed by PR #1099.

**Comment by hbushouse** [comment]
It looks like #1099 only updates the WCS object in the meta data. Are we doing anything in terms of FITS-like keywords that get written to the table extension header? We don't necessarily need or want any keywords to describe the wavelength array, because the wavelength array is stored explicitly in the table, but what about at least putting in a couple of keywords that give the RA/Dec of the slit center, corresponding to what's in the WCS object? We don't want to use the TARG_RA, TARG_DEC (or are they RA_TARG/DEC_TARG) keywords that are in the primary header, so we could potentially make up something new like SLIT_RA/SLIT_DEC?

**Comment by nden** [comment]
Does it make sense to have a minimal

**Comment by hbushouse** [comment]
I don't think the FITS standard allows CRVAL (and similar) keywords in a table header, because they only apply to imaging. I think there's a whole separate set of WCS-related keywords for a table header, but in that case I believe they are supposed to relate to rows along certain columns, e.g. the equivalent of CRVAL1/CDELT1 would supposedly relate to the rows contained in column 1. In our case the RA/Dec is constant for all entries.

**Comment by nden** [comment]
Oh yes, right.

**Comment by nden** [comment]
The final piece of this issue was resolved in #1154
