### ISSUE TITLE
Copy slit-related keywords to extract_1d output

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1042]
The MultiSlitModels that serve as input to extract_1d contain slit-specific keywords as attributes of each slit instance (stored in the SCI extension header of FITS files). These meta attributes are currently defined in the multislit.schema.yaml file. Most of these meta attributes should be copied over to the MultiSpecModel created as output from extract_1d, in order to carry along useful info like source_id, etc. Right now the MultiSpecModel does not define these meta data. It should be enhanced to include them (or at least the ones that are relevant) and then have extract_1d populate them from the input model.

**Comment by hbushouse** [comment]
The following are relevant entries from an email thread on this topic:

@nden:
PR #1031 creates a slit.schema.yaml. 
Can that be used for MultiSpecModel?
Does it need anything else?

@philhodge:
Four of the keywords in MultiSlitModel are SLTSTRT[12] and SLTSIZE[12], which are not relevant for 1-D extracted spectra because the extraction region can be smaller than those limits, and (because of Mihai's enhancements) the extraction region can have polynomial upper and lower boundaries.  The extraction region can even consist of multiple, disjoint regions.

For a MultiSpecModel, there should be info regarding the background region(s), if any.  Those can also have polynomial upper and lower boundaries.

@philhodge:
It seems to me that there are a few items in slit.schema.yaml that would not be relevant for the 1-D spectrum.  The wavelength is already in the MultiSpecModel table, but as a 1-D array.  I don't understand the distinction between wavelength_pointsource and wavelength_uniformsource; but in any case, if they were in the MultiSpecModel, I would expect to find them as table columns, not independent extensions.  (By the way, if these and the pathloss items are independent extensions in the FITS file, how do we associate them with the science data?  By matching name, or source_id, or something else?)  The xstart, xsize, ystart, and ysize I already mentioned as being not necessarily relevant for 1-D spectra.

**Comment by hbushouse** [comment]
PR #1031 does indeed create a slit.schema.yaml, but it appears to include not only the meta data definitions, but also the data arrays normally used in a MultiSlitModel. For the MultiSpecModel we only need the meta data and perhaps not all of them. It has its own data structure, in the form of a table.

**Comment by philhodge** [comment]
There are possible input models other than MultiSlitModel.  This is a complete list (at the current time):

* MultiSlitModel
* MultiProductModel
* ImageModel
* DrizProductModel
* CubeModel
* IFUCubeModel

There are some slit-specific or source-specific attributes in the first two of these, but they are not present in any of the other models.  Will they be at some time in the future, or only after some particular step has been run?  Or should the extract_1d step only copy such attributes from MultiSlitModel or MultiProductModel input?

**Comment by hbushouse** [comment]
Slit/source-specific meta data only shows up in models in which there's some kind of pre-determined knowledge of the existence of multiple slits or sources. For example, in a NIRSpec fixed-slit exposure you know which slits were included, and in NIRSpec MOS exposures we get a catalog of defined slits from the front end systems (APT/PPS), and finally for NIRCam and NIRISS WFSS (grism) exposures, the cal pipeline generates its own catalog of sources, which is used as input to the calspec2 pipeline. Hence for all of those modes there will be some kind of meta data related to the characteristics of individual slits or sources. All of those exposure modes will result in either a MultiSlitModel, MultiProductModel, or DrizProductModel (if the slit cutouts have been drizzled) going into extract_1d. So it appears that DrizProductModel may need to be updated to allow for the slit/source meta data.

Data contained in an ImageModel (MIRI LRS fixed-slit), CubeModel (MIRI LRS slitless, NIRISS SOSS), or IFUCubeModel (NIRSpec IFU, MIRI MRS) never has pre-defined slit/source info and hence there's nothing for us to populate.

**Comment by philhodge** [comment]
OK, I'll change the extract_1d step to copy those keywords for a DrizProductModel input, if the keywords are present.

**Comment by hbushouse** [comment]
Fixed by #1161
