### ISSUE TITLE
tweakreg work for B7.1

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1050]
Several changes/upgrades are needed for tweakreg.

1) Upgrade the infrastructure to use the JWST-style WCS/gwcs objects

2) @jdavies-st and I think it would be reasonable to combine the tweakreg_catalog and tweakreg steps into a single step. This could be accomplished by simply writing a high-level tweakreg step that calls the existing tweakreg_catalog and tweakreg steps. Can't imagine it ever being necessary or useful in the pipeline environment to run one without the other. This would also involve an update to the calimage3 pipeline module to only call the one new combined step.

3) tweakreg should delete the catalogs produced by tweakreg_catalog when it's all done doing its work. There are no plans to archive the source catalogs for the individual exposures, hence they should be cleaned out of the directories.

**Comment by larrybradley** [comment]
:+1: to combining the steps.

**Comment by mcara** [comment]
Most definitely tweakreg step cannot run without catalogs. However, can anyone ever want to create catalogs without aligning the images? I was under impression that this was the initial thought... If it is not true any longer than definitely it makes sense to combine the two steps.

**Comment by hbushouse** [comment]
Can anyone think of any use cases where someone might want to just create the catalogs for each image? Could the source_catalog step be used for that (on one image at a time) or is it a bit different than tweakreg_catalog?

**Comment by sosey** [comment]
I can imagine you might to use different catalog parameters to create each of those catalogs (source vs tweakreg) since they have a different purpose - i.e. find me all the objects vs find me all the objects which are appropriate for calculating offsets? Are the input parameter sets the same to both tweakreg_catalog and source_catalog?

**Comment by larrybradley** [comment]
They are fundamentally different catalogs.  `tweakreg_catalog` searches for point-like sources (i.e. sources similar to an input kernel) to be used for *alignment*.   `source_catalog` catalogs all sources (point-like and extended) that are above some given threshold (e.g. a S/N threshold above the background).  The source catalog also contains a lot more measurements (incl. morphological) than the tweakreg catalog.

`tweakreg_catalog` is essentially `DAOFind` and `source_catalog` is like `SExtractor`.

**Comment by jdavies-st** [comment]
If a user wants to run the step without actually doing the `tweakreg` part and just make catalogs, then there could be a flag for that.  But it does make sense to combine them from my view.  If one needs to control photutils params for these catalogs, they're available in the step `spec`.

I think they were originally separate as Mihai and Larry were working separately on them due to their areas of expertise.  When @stsci-hack and I were planning out the Level 3 imaging pipeline on the white board for Build 6, I don't recall there being any other reason.

**Comment by hbushouse** [comment]
From @larrybradley comments, it basically sounds like the remaining question is whether it's ever useful or desirable for someone to run the tweakreg_catalog style approach on images, all by itself. If someone is serious about building a serious source catalog, they would use source_catalog. I guess the possibility of wanting to apply the tweakreg-style cataloging could be accommodated by the suggestion from @jdavies-st to have a flag/parameter/argument in the combined tweakreg step that would tell it to only produce catalogs. Perhaps an analogous argument could be included that would tell it to only perform the matching/alignment operation, without regenerating catalogs first (i.e. if someone had existing catalogs and made some mods to them or whatever and wanted to use them as input).

**Comment by mcara** [comment]
> From @larrybradley comments, it basically sounds like the remaining question is whether it's ever useful or desirable for someone to run the tweakreg_catalog style approach on images, all by itself.

That was basically my question too. If the answer is "no", I do not think we should bother with complicating the step by introducing more parameters that will most likely never be used. I do not imagine anyone supplying custom catalogs to tweakreg *in the pipeline* (it's different for post-pipeline data analysis).

**Comment by larrybradley** [comment]
@mcara  Some people do use custom catalogs for HST's tweakreg step (as part of astrodrizzle).  I expect `calwebb_image3` will be used outside of the *pipeline* for custom drizzling of JWST data, just like they currently use astrodrizzle for HST data.

**Comment by mcara** [comment]
@larrybradley True, but I do not re-run HST *pipeline* to do this. That is, even though `astrodrizzle` is run within the HST pipeline, I regard it as a stand-alone data analysis tool. I do not think people should use drizzled products from HST pipeline for anything serious except for a "preview".

**Comment by mcara** [comment]
I guess, do we look at individual pipeline steps as stand-alone data analysis tools or as a part of a bigger pipeline used to calibrate raw data and to create ``*flt.fits``-like products to be analyzed by the user using stand-alone tools?

**Comment by larrybradley** [comment]
I agree with you about the HST drizzled products -- no one uses them. :smile:   That may change some with JWST, but some people *are* still going to want to tweak settings from the defaults (e.g. pixfrac, scale, etc.) or combine datasets over different programs, etc.

I'm equating `calwebb_image3` to `astrodrizzle`.  Both are part of the respective pipelines, but they can also be run independent of the entire pipeline.

**Comment by mcara** [comment]
> I agree with you about the HST drizzled products -- no one uses them.

Based on the information (=private communications) that I have from INS, that is not true: it seems that quite a lot of users use drizzled products "as is" (even though they *shouldn't*).

**Comment by mcara** [comment]
@hbushouse Point nr.1 has been addressed in part in https://github.com/STScI-JWST/jwst/pull/1458

**Comment by mcara** [comment]
@hbushouse Second take (due to merge conflicts): https://github.com/STScI-JWST/jwst/pull/1460

**Comment by hbushouse** [comment]
Fixed by #1460 and #1556.
