### ISSUE TITLE
EXTVER handling in output products

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1074]
Mike Swam reports:

Richard made a fresh SIC/DIL run using our build from 2017-07-07 (a little old by now, but still our best) and we’re seeing a set of failures during level-2b archive ingest related to the EXTVER keyword.   Here is the error we get:
 
2017202093645809 ERROR edu.stsci.dms.ingest.IngestManifestMain [jw95065009001_02106_00001_nrs1] [ERROR Message: ERROR: root cause: 
Error 515, Level/Severity 16, State 2, Procedure spIngest_InsertScienceSlit, Line 64 
Message: Cannot insert the value NULL into column 'extver', table 'jwarchiveops.dbo.ScienceSlit'; column does not allow nulls. INSERT fails. 
 
And here are the values seen in the input files from level-1b, 2a, and 2b:
 
iljwdmsbdpv2> egrep "EXTNAME|EXTVER" /home/mswam/jw95065009001_02106_00001_nrs1_uncal.lis
EXTNAME = 'SCI     '           / extension name
EXTVER  =                    1
 
iljwdmsbdpv2> egrep "EXTNAME|EXTVER" /home/mswam/jw95065009001_02106_00001_nrs1_rate.lis
EXTNAME = 'SCI     '           / extension name
EXTNAME = 'DQ      '           / extension name
EXTNAME = 'ERR     '           / extension name
EXTNAME = 'ASDF    '           / extension name
 
iljwdmsbdpv2> egrep "EXTNAME|EXTVER" /home/mswam/jw95065009001_02106_00001_nrs1_cal.lis
EXTNAME = 'SCI     '           / extension name
EXTNAME = 'DQ      '           / extension name
EXTVER  =                    1 / extension value
EXTNAME = 'ERR     '           / extension name
EXTVER  =                    1 / extension value
 
We seem to have lost the EXTVER keyword in the level2a extensions completely (though oddly, archive catalog population didn’t care about that), and it remains lost for the 1st (SCI) extension in the level2b _cal file, which I think is the cause of the catalog ingest error, though it is present in the DQ and ERR extensions.

**Comment by hbushouse** [comment]
Technically, according to the FITS standard, there's nothing wrong with these files, because EXTVER is not required when there's only 1 extension with a given EXTNAME, but it would be good to at least achieve consistency in all of the products. Hence the _cal.fits product in this case should have EXTVER present for all extensions, not just the ERR and DQ. And it can't hurt to just always write it out with a value of 1 even when there's only 1 extension per EXTNAME.

**Comment by bernie-simon** [comment]
Datamodels now always writes the EXTVER keyword when saving files.
