### ISSUE TITLE
Problems with Level1b data model

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1075]
Bryan Hilbert reports:

I'm seeing what I think is a bug in the Level1bModel datamodel. When I use it to read in a file that has no zeroframe extension, it seems to populate model.zeroframe with an array of all zeros, but it the shape doesn't make sense. It looks like the default array size is ngroups x ny x nx, rather than nints x ny x nx. Let me know if you'd like me to put this in a new issue in the github repo. The only downside of that is that it seems like I don't have permissions enough to attach labels to the issue.

Here's what I'm seeing, using astropy as a comparison:

file='/ifs/jwst/wit/nircam/isim_cv3_files_for_calibrations/darks/A1/NRCNRCA1-DARK-60011933591_1_481_SE_
   ...: 2016-01-01T20h04m44_uncal.fits'

In [6]: from astropy.io import fits

In [7]: h=fits.open(file)

In [8]: h.info()
Filename: /ifs/jwst/wit/nircam/isim_cv3_files_for_calibrations/darks/A1/NRCNRCA1-DARK-60011933591_1_481_SE_2016-01-01T20h04m44_uncal.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     392   ()      
  1  SCI           1 ImageHDU        10   (2048, 2048, 108, 1)   float32   
  2  PIXELDQ       1 ImageHDU        10   (2048, 2048)   int32 (rescales to uint32)   
  3  GROUPDQ       1 ImageHDU        10   (2048, 2048, 108, 1)   uint8   
  4  ERR           1 ImageHDU        10   (2048, 2048, 108, 1)   float32   
  5  ASDF          1 ImageHDU         7   (1811966053,)   uint8   

In [1]: from jwst.datamodels import Level1bModel

In [3]: mod=Level1bModel(file)

In [4]: mod.data.shape
Out[4]: (1, 108, 2048, 2048)

In [5]: mod.zeroframe.shape
Out[5]: (108, 2048, 2048)

---------------------------------------------------------------------------------------
Here's another detail that I came across that I don't understand. It looks like the level 1b model keeps the data as signed integers, while the RampModel switches them to unsigned integers. But when I read in the same file with as both a Level1bModel and a RampModel, the difference in the data (at least in terms of the max values) is not equal to 2^15, which is what I expected. Am I misinterpreting what's going on here?

In [3]: file='/ifs/jwst/wit/nircam/isim_cv3_files_for_calibrations/darks/A1/NRCNRCA1-DARK-60011933591_1_481_SE_2016-01-01T20h04m44_uncal.fits'

#read in same file with both models
In [5]: mod = Level1bModel(file)
In [11]: rmod = RampModel(file)

#look at signal range in Level1bModel
In [8]: np.min(mod.data)
Out[8]: -32768

In [9]: np.max(mod.data)
Out[9]: 32753

#signal range in Level1bModel plus 2^15
In [14]: np.min(mod.data+2**15)
Out[14]: 0

In [15]: np.max(mod.data+2**15)
Out[15]: 65521

#look at signal range in RampModel
#These should equal the level1b values+2^15
#above, right?
n [12]: np.min(rmod.data)
Out[12]: 0.0

In [13]: np.max(rmod.data)
Out[13]: 40317.0

**Comment by hbushouse** [comment]
Yes, that test looks correct. The shape of the zeroframe should be (nints, ny, nx), not (ngroups, ny, nx).

We may want to remove the "default: 0.0" declarations for all optional arrays like zeroframe and refout from the level1b, ramp, and miri_ramp data models, if it's causing those arrays to be populated when they don't exist in an input file that's being loaded into one of these data models. If they aren't there, we don't want to create them and have them appear in a subsequent output product, because they are optional. We only want to force the appearance of required arrays like SCI, DQ, and ERR (or for ramp models it's pixeldq and groupdq, instead of dq).

Also, regarding the data types that are declared in the level1b schema, Bryan is right that any array like "data", "zeroframe", and "refout" which results from data coming down from the telescope should be declared as uint16, rather than int16, because the data coming down are always unsigned 16-bit (i.e. native range of 0 to 65,535).

It's OK to declare them as floats in RampModel and MiriRampModel, because those models are always used as the starting point for calwebb_sloper processing, where we want them converted from uint16 to float for use in all of the calwebb_sloper corrections.

**Comment by stscieisenhamer** [comment]
Currently, for the array to not be created, the `ndim` and `datatype` properties need to be removed. Oddly enough, the `default` does not play into this. This is at the datamodels level, so if there is desire to still be able to define the dimensions and datatype but not have the array be created, a new property could be added, such as `optional` to indicate that if the array is not there, don't create it. Or key off of the existence of the `default` value. If no `default`, don't try creating.

**Comment by stscieisenhamer** [comment]
upon further review and testing, wanting to have at least `datatype` specifiable is highly desired. And, probably `ndim` also. So, either a new property or keying off `default` to flag whether an array should be created is necessary.

**Comment by hbushouse** [comment]
That really surprises me. In most of the data model modules (e.g. ramp.py, image.py, etc.) we have statements like:
```
        self.pixeldq = self.pixeldq
        self.groupdq = self.groupdq
        self.err = self.err
```
in order to force those arrays to get created and populated (with their default value) in the event there aren't any corresponding arrays/extensions in the input file being loaded into the data model. This happens all the time when we load a level-1b FITS file into a RampModel. The level-1b FITS file does not have any PIXELDQ, GROUPDQ, or ERR extensions, hence the corresponding arrays don't show up on their own when that file is loaded into a RampModel. The first time a cal step tries to access one of those arrays in the data model, it throws an error. So we put in those statements shown above to force those arrays to be created in the data model. All of them have ndim and datatype defined in the schemas. So why don't they show up when we load a level-1b FITS file into a RampModel?

Or has that behavior changed over the years, such that they do in fact show up now, with us resorting to using the statements above?

**Comment by bernie-simon** [comment]
The code that controls this is in datamodels.properties and you can look at it for the details. Briefly, accessing an object using the dot notation calls ObjectNode.__getattr__ (line 194 in properties.py). Then it is not found, the code calls _make_default (line 206).  _make_default has a bunch of tests, to view them all the code starts at line 94. It decides to call _make_default_array based on max_ndim, ndim, or datatype. If any of them are present it gets called. _make_default_array either creates an array based on the primary array shape or ndim, depending on whether the primary array is defined.

Of course, that's based on how the code currently works, which can be changed.

**Comment by stscieisenhamer** [comment]
wow, those statements are completely nonsensical and appear to be unnecessary. don't know about change, but existence of any of `default`, `ndim`, `datatype`, or `max_ndim` will cause array creation. As coded, its next to impossible not to have an array created, except for having a very empty schema definition.

**Comment by stscieisenhamer** [comment]
Note to the second issue about data consistency: if the data is properly read in as `uint16`, the min/max values are consistent. Incorrectly reading the data as `int16` causes the inconsistency. So, the schema, minimally, will be modified to set datatype to `uint16` for all properties.

**Comment by bernie-simon** [comment]
If there's no assignment in the model's __init__ function

   self.foobar = self.foobar

then the foobar array won't get created unless it's already in the fits file. Default values are only created when you try to access them.

**Comment by stscieisenhamer** [comment]
Guess that handles the case where one always wants arrays written to a file, regardless of them ever being accessed.  Otherwise, they would be lazy-instantiated anyways if accessed after opening.

**Comment by hbushouse** [comment]
I've always wanted a optional/required option for entries in schemas, for data arrays and keywords (meta). I seem to recall Mike D. (see, that's how far back this issue goes ...) saying it was possible and the json (now yaml) schema allows for it, but it was either never implemented in our interpreter/parser or it just simply didn't work for some unknown reason. If we could use such an argument, then we wouldn't have to worry about indirect methods such as whether or not a default value is specified or ndim is specified, etc.
