### ISSUE TITLE
AstropyDeprecationWarning: "tolerance" was deprecated, use "rtol"

### ISSUE THREAD

**Issue by pllim** [STScI-JWST/jwst#1092]
I see a lot of this in your test logs:
```
2017-07-30 10:38:57,171 - stpipe -
  WARNING - .../astropy/io/fits/diff.py:316: AstropyDeprecationWarning:
  "tolerance" was deprecated in version 2.0 and will be removed in a future version.
  Use argument "rtol" instead.
  AstropyDeprecationWarning)
```

https://ssb.stsci.edu/steuermann/steuermann.cgi?action=log&name=conda_tests_2017-07-30-10:30:02/jwcalibdev:conda_testing/jwst_dev_tests

**Comment by hbushouse** [comment]
As of today, all test modules have been updated to use `rtol`.
