### ISSUE TITLE
update pointing algorithms

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1107]
Northrup Grumman is updating the algorithms for the quaternion to sky coords algorithm. Changes include:

- 2.5 updated steering mirror transformation to new algorithm
- 2.3 Change reading of the J-frame mnemonics. If the mnemonics are all zero, use a predefined set.

If time permits, re-run the original Kinzel test data to track differences.

**Comment by stscieisenhamer** [comment]
# Implementation

- [ ] test setup
- [ ] algorithm review
- [ ] update how mnemonic existence check is done. allow defaults for J-frame
- [ ] update steering mirror transformation

**Comment by nden** [comment]
@hbushouse  So this does not calculate the footprint the way APT does, i.e. does not use the vertices of the aperture in the Ideal frame. Is this how we decided to do it and does it work for spectral data? Or is this a temporary solution?

**Comment by hbushouse** [comment]
This is a temporary solution just to get the S_REGION keyword populated with something that the other DMS subsystems can use once they start running the delivery we made yesterday. We still plan to replace this with the better, but more complicated, APT way of doing it that uses the aperture vertices from the SIAF. Hence #580 is still open.
