### ISSUE TITLE
handle dash separated suffixes

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1128]
@hbushouse writes:

> So I've discovered a problem with the FGS guide mode data sets when processing them through the new calwebb_guider pipeline. The problem is that the names of some of the input (raw) products look like:
>
> jw88600073001_gs-id_7_image-uncal.fits
> jw88600073001_gs-id_7_stacked-uncal.fits
>
>The problem here, in case you haven't already spotted it, is the fact that the "uncal" suffix is preceded by a dash rather than an underscore.
>
> In the calwebb_guider pipeline I set self.suffix='cal' and it succeeds in creating an output file name that has the "cal" suffix tacked on, but because of the dash in the existing file name it doesn't replace the "uncal" with "cal." Instead it just appends "cal", so that you end up with:
>
> jw88600073001_gs-id_7_image-uncal_cal.fits
> jw88600073001_gs-id_7_stacked-uncal_cal.fits
>
> I find this result surprising in that I would've expected the step infrastructure that does the file name creation to look for the last occurrence of underscore and replace everything following it, e.g.
>
> jw88600073001_gs-id_7_cal.fits
> jw88600073001_gs-id_7_cal.fits
>
> which is equally bad, because that would lead to file name degeneracy.
>
> Ideas as to why it's doing what it's doing and how we might be able to fix it so that we end up with names like:
>
> jw88600073001_gs-id_7_image-cal.fits
> jw88600073001_gs-id_7_stacked-cal.fits
>
>i.e. just the "uncal" has been replaced with "cal".

**Comment by larrybradley** [comment]
> I find this result surprising in that I would've expected the step infrastructure that does the file name creation to look for the last occurrence of underscore and replace everything following it

No, it doesn't do this.  It will only replace the suffix if it's in a list of known suffixes:

`SUFFIX_LIST = ['rate', 'cal', 'uncal', 'i2d', 's2d', 's3d',
               'jump', 'ramp', 'x1d', 'x2d', 'x1dints', 'calints', 'rateints']`

**Comment by larrybradley** [comment]
And the suffix that is searched for is indeed `_<suffix>` not `-<suffix>`, but the regex that does this could be modified to include both.

**Comment by jdavies-st** [comment]
Why the dashes and not underscores?  Can't we be consistent in the naming?  I.e. get rid of all dashes?

`jw88600073001_gs_id_7_image_cal.fits`

**Comment by stscieisenhamer** [comment]
first: almost done with the regex fix: simple.
as to why: bad naming on the sdp side and unclear about whether it will change.

**Comment by hbushouse** [comment]
I made the argument a couple months ago when those names were proposed, but lost. In this case the "stack" and "image" strings are considered to be part of the product type designation, hence the entire product type is seen as being "image-uncal" and "stacked-uncal", which we then replace with "image-cal" and "stacked-cal".

**Comment by jdavies-st** [comment]
This is terrible from a user perspective.  Ugh.

**Comment by hbushouse** [comment]
Well fortunately there won't be that many users of the guide star data. Mainly just a couple folks on the FGS team and these particular products - from the ID (identification) phase of acquiring a guide star - are the least useful and hence least used of all the guide star products.
