### ISSUE TITLE
P_ keyword schema bugs

### ISSUE THREAD

**Issue by jaytmiller** [STScI-JWST/jwst#1140]
Operationally we noticed a problem with keyword_preadpatt.schema.yaml which I think is due to missing |-bars near the end of each line of the value pattern.

For example,  P_FILTER says:

            pattern: "\
              ^((CLEAR|F070LP|F090W|F1000W|F100LP|F1065C|\
              F110W|F1130W|F1140C|F115W|F1280W|F140M|F140X|F1500W|F150W|\
              F150W2|F1550C|F170LP|F1800W|F182M|F187N|F200W|F2100W|F210M|\
              F212N|F227W|F2300C|F250M|F2550W|F2550WR|F277W|F290LP|F300M|\
              F322W2|F335M|F356W|F360M|F380M|F410M|F430M|F444W|\
              F460M|F480M|F560W|F770W|FLENS|FND|FNDP750L|GR150C|\
              GR150R|OPAQUE|P750L|WL3|WLP4|N/A|ANY)\\s*\\|\\s*)+$"

but P_READPATT says:

            pattern: "\
              ^((ACQ1|ACQ2|ALLIRS2|BRIGHT1|BRIGHT2\
              DEEP2|DEEP8|FAST|FASTGRPAVG|FASTINTAVG\
              FGS|FGS60|FGS8370|FGS840|FGSRAPID|FINEGUIDE\
              ID|MEDIUM2|MEDIUM8|NIS|NISRAPID\
              NRS|NRSIRS2|NRSN16R4|NRSN32R8|NRSN8R2\
              NRSRAPID|NRSIRS2RAPID|ALLIRS2|NRSSLOW|RAPID\
              SHALLOW2|HALLOW4|SLOW|TRACK|ANY|N/A)\\s*\\|\\s*)+$"
 
where the almost-trailing | is missing on each line.  

This results in end-of-line values being glued to the first value of the subsequent line,  so e.g. NISRAPID is not valid, NRS is not valid,  but NISRAPIDNRS is valid.

The missing or-bar issue only seems to apply to:

    keyword_preadpatt.schema.yaml
    keyword_pdetector.schema.yaml  

However,  I also stumbled onto this by accident:

   keyword_pgrating.schema.yaml:            enum: 
   ^((G140M|G235M|G395M|G140H|G235H|G395H|PRISM|MIRROR|N/A|ANY)\\s*\\|\\s*)+$

where "pattern" is replaced by "enum".   I think:

    keyword_pgrating.schema.yaml

also needs an update.

**Comment by hbushouse** [comment]
Fixed by #1141
