### ISSUE TITLE
explore using reprocessing to handle level2b background

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1168]
exposures that are backgrounds need to be included in two associations: one for itself and one as a background. currently a kludge is setup with `check_flags` to get both created. More proper implementation is to use the reprocess logic to first create all the base associations, then add in the backgrounds.

**Comment by hbushouse** [comment]
Not sure why we need to have them in 2 separate ASN's. Can't the backgrounds be listed in just the ASN that also contains the science target exposures that they'll be used for, such that calspec2 knows to

1) give them all the normal processing done for a science target exposure, and
2) use them as background for the designated target exposures in the ASN

On Sep 6, 2017, at 9:24 AM, Jonathan Eisenhamer <notifications@github.com<mailto:notifications@github.com>> wrote:


exposures that are backgrounds need to be included in two associations: one for itself and one as a background. currently a kludge is setup with check_flags to get both created. More proper implementation is to use the reprocess logic to first create all the base associations, then add in the backgrounds.

**Comment by stscieisenhamer** [comment]
First note: this issue is an internal code-specific refactor. No change in output is expected.

Regardless, just for clarification on how it works now, below is a snippet of an association concerning two exposures, one of which is marked background for the other:
```
    "products": [
        {
            "name": "exp_science",
            "members": [
                {
                    "expname": "exp_science_rate.fits",
                    "exptype": "science"
                },
                {
                    "expname": "exp_bkg_rate.fits",
                    "exptype": "background"
                },
            ]
        },
        {
            "name": "exp_bkg",
            "members": [
                {
                    "expname": "exp_bkg_rate.fits",
                    "exptype": "science"
                }
            ]
        }
    ]
```
In words, the association has two products which will produce `exp_science_cal.fits` and `exp_bkg_cal.fits`. The first product for the science exposure has, in its member list, the background exposure. The background has no other members than itself for its own processing.

Is the suggestion to remove the second product, and have `Spec2Pipeline` note that it should process any background members as science members also?

I would suggest not because ultimately, one will not know where the background came from nor whether it should have its own processing afterwards. Scenarios that support this are:

- User-processing: A user may want to create their own background which will probably not be able to be 2b processed
- If, at some future point, the background needs 2b, or other, processing before being used as a background

The current setup disconnects the 2b processing of the exposures, as they would have been done anyways.

**Comment by hbushouse** [comment]
All of that makes perfect sense and is the way I was expecting things to be handled. When you originally said "exposures that are backgrounds need to be included in two associations" I thought you were implying that the background exposure would show up in 2 completely separate ASN files. In the scenario you outlined above it's in a single ASN file, but is used in two different products within that ASN (one for the science and one for itself). That's fine.

**Comment by stscieisenhamer** [comment]
👍  However, note that it is a simple thing to make each level2 association product a separate association. Why? Well, if we can't beat the memory issues, it may be best if SDP ran with the whole mess of associations instead. It would be a whole bunch of association files, one-per-exposure, and these would then be archived, presumably, but otherwise operations would not be different.
