### ISSUE TITLE
Enable resampling of coron3 output data

### ISSUE THREAD

**Issue by stsci-hack** [STScI-JWST/jwst#1184]
The `Coron3Pipeline` step includes outlier_detection to generate updated PSF-subtracted images.  These products are then expected (based on JWST CWG outline of CALCORON3) to be combined into a single final product, something which would be done with the resample step. The current default configuration file for the `Coron3Pipeline` skips the resample step.

**Comment by stsci-hack** [comment]
Investigating how to turn on resampling for the `Coron3Pipeline` output product revealed that it can NOT be turned on until support for this observation type has been added to `assign_wcs`.  Adding this support will require obtaining updated WCS information for the observing mode from the instrument team.  

@hbushouse and @nden will need to report on when the update has been implemented in `assign_wcs` in order to finally enable the full range of planned initial processing of coronographic data in the pipeline.

**Comment by hbushouse** [comment]
I believe that for MIRI the already delivered distortion reference file for the imager detector is applicable to the entire detector FOV, which includes the areas of the coronagraphic masks and Lyot stops. Is that sufficient for assign_wcs to work with MIRI coronagraphic exposures?

What's the situation with NIRCam? Do the distortion reference files already delivered for imaging modes not cover the areas/subarrays of coronagraphic exposures?

**Comment by nden** [comment]
@stsci-hack @hbushouse `assign_wcs` for `NRC_CORON` mode was enabled in #1193. Reference files have been delivered though it may take a day to show up in CRDS.

**Comment by hbushouse** [comment]
Fixed by #1185 and #1433
