### ISSUE TITLE
Fix caltso3 regression test

### ISSUE THREAD

**Issue by stsci-hack** [STScI-JWST/jwst#1198]
The regression test `test_nrc_tso3_1.test_tso3_pipeline2` has been crashing with an error due to a bug in the `outlier_detection_scaled_step`.  A new version of that step needs to be provided to get this regression test to run successfully and not ERROR out.

**Comment by stsci-hack** [comment]
It turns out that this issue came up as a result of incorrectly using the `.get_reference_file()` method in this step.  The code assumed that all methods returned a DataModel for the specified reference file, while in fact, this method only returns the filename that must still be opened and passed back.  (In other words, the developer assumed the wrong behavior.)  This problem will be corrected once PR #1200 gets merged.

**Comment by hbushouse** [comment]
Fixed by #1200
