### ISSUE TITLE
Move pandokia test scripts back here

### ISSUE THREAD

**Issue by pllim** [STScI-JWST/jwst#1208]
This would be needed for integration with Jenkins. Obviously, you also have to rewrite it so it does not rely on pandokia anymore. I recommend you add some kind of pytest fixture to them (akin to what you did to the "slow tests") so they won't run on Travis but will run on Jenkins.

c/c @jhunkeler 

Supersede #674

**Comment by stscicrawford** [comment]
- [x] Move scripts into their own directory on here
- [x] Create jenkins build script
- [ ] run test directory on jenkins
- [ ] fix or skip anything that fails
- [ ] document how to check and be notified by tests
- [ ] deactivate pandokia scripts
