### ISSUE TITLE
Deprecated behavior in tweakreg C code needs to be updated

### ISSUE THREAD

**Issue by stsci-hack** [STScI-JWST/jwst#1224]
The compilation of the C extension in tweakreg triggers a Deprecation warning for using the the old API to Numpy.  As documented on scipy.org, this deprecation can be easily resolved through the inclusion of the following definition in the C code:

#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION

This, along with the other compilation warnings, should be addressed in order to prevent any future problems with compatibility to numpy and/or Python.

**Comment by mcara** [comment]
I have a solution for this and it will be submitted after tweakreg re-work.

**Comment by mcara** [comment]
Solved through https://github.com/STScI-JWST/jwst/pull/1461
