### ISSUE TITLE
CAL_VER version number format,  CRDS usage

### ISSUE THREAD

**Issue by jaytmiller** [STScI-JWST/jwst#1227]
CALIBRATION_SOFTWARE_VERSION,  CAL_VER,  is passed to CRDS as the matching parameter that is used to look up CAL component s/w versions given to the archive (SYSTEM CALVER reference) and also used to determine reference types that should be examined for reprocessing (currently the hidden/built-in SYSTEM CRDSCFG references).

For B7 CRDS used literal matching to version strings of a form like this:

    0.7.0rc8

Currently CAL_VER has morphed to this:

   e564f6f1

While CRDS rmaps can be constructed to match on the hashes,  hashes are pretty brittle,  hard or impossible to order,  and cannot be guessed.   So I'd like to work out some "operational parameter" to pass to CRDS that has better properties for macroscopic version control,  or at least start a discussion on what should be done.   Internally,  I think CRDS should probably just use x.y.z and drop off any rcN or devXXXX, etc.

**Comment by hbushouse** [comment]
CAL_VER keyword values in .fits files fresh out of the cal pipeline (interactive runs, regression test runs, etc.) have strings like this:

0.7.8rc2.dev161

Where is it that you're seeing hashes for that keyword value?

**Comment by sosey** [comment]
I get this issue when I've forgotten to pull the tags from the git repo for jwst, if you update your branch with the tags from master, then the version should be updated correctly

**Comment by jaytmiller** [comment]
I believe Meg is right about this,  the problem was that I install "jwst" from a git clone on the servers... without updating the tags.    The tags in master also seem coarser grained than the nightly conda-dev tags....  which is probably good.
