### ISSUE TITLE
I can't get NIRCAM imaging mode WCS to roundtrip to the same pixels

### ISSUE THREAD

**Issue by sosey** [STScI-JWST/jwst#1240]
Is it just me? The following completes fine:
```
directim=image.ImageModel(direct_image)
step=assign_wcs.AssignWcsStep()
direct_out=step(directim)
```
and I get a viable output wcs with the frames I expect:

```
Available reference frames for (NRC_IMAGE, F335M): ['detector', 'v2v3', 'world']

test_to_sky=direct_out.meta.wcs.get_transform('detector','world')
test_to_detector=direct_out.meta.wcs.get_transform('world','detector')
```
Using this example pixel (x,y) = 940.0 pix 943.0 pix, I can't go to world coordinates and come back to the same place. 
```
(x, y): 940.0, 943.0
(ra, dec): 0.0007298343751536788 -0.0006946864451814786  # test_to_sky
(x, y): 941.2369823537116, 942.3461025929757  # test_to_detector
```
This is using a single example image which CRDS matched to: jwst_nircam_distortion_0061.asdf

**Comment by jdavies-st** [comment]
Hmm, I wonder if the `forward_transform` and `backward_transform` polynomials are not quite right?  They are from the SIAF file from the telescopes group.  Or perhaps a 0 or 1 indexing problem in one of the transforms?  Hmm.

**Comment by jdavies-st** [comment]
Testing NIRCam simulated data I get:
```
In [76]: im = datamodels.open('nrca1_47Tuc_primary_dither2_newpos_cal.fits')

In [77]: w = im.meta.wcs

In [78]: w(940, 943)
Out[78]: (5.895625205731407, -72.00777739607614)

In [79]: w.backward_transform(*w(940, 943))
Out[79]: (941.2369774875979, 942.3461003772096)

```
So it is not just you.  Hmm.

**Comment by jdavies-st** [comment]
Looking at the gwcs forward and backward transforms, they seem correct in terms of structure.  The poly2D coeffs act on 1-indexed pixel coordinates because they are ultimately derived from the SIAF, but we pass it 0-indexed coordinates, so there's a offset=1 in there.  Nothing obviously wrong.

At the CRPIX1 and CRPIX2, it produces correct results.
```
In [87]: w.backward_transform(*w.forward_transform(1023.5, 1023.5))
Out[87]: (1023.4999999999613, 1023.4999999999159)
```

**Comment by sosey** [comment]
I think its the distortion reference file, it's really the only thing getting used. The same issue exists with NIRISS, but we already know the distortion reference file is sketchy there.

**Comment by jdavies-st** [comment]
Yes, absolutely.  In fact, one can do the same test going from `detector` to `v2v3` to take out anything that's not the distortion reference file:
```
In [12]: im = datamodels.open('nrca1_47Tuc_primary_dither2_newpos_cal.fits')

In [13]: w = im.meta.wcs.get_transform('detector', 'v2v3')

In [17]: w.inverse(*w(1023.5, 1023.5))
Out[17]: (1023.5000000000005, 1023.5)

In [18]: w.inverse(*w(940, 943))
Out[18]: (941.2369774876402, 942.3461003780544)
```

**Comment by nden** [comment]
There were no proper distortion measurements during ground testing. These transforms come from the TEL group and are not very accurate especially far from the reference point. But that's the best we have now.
