### ISSUE TITLE
For WFSS/GRISM data, do flat_field before extract_2d

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1241]
The calspec2 pipeline (calwebb_spec2.py) currently runs `extract_2d` before `flat_field` for all input types.  For NRC_GRISM, NIS_WFSS, and NRC_TSGRISM data, the `flat_field` step should be run before `extract_2d`.  Furthermore, `extract_2d` should actually be run on NRC_GRISM and NIS_WFSS data (though still not on NRC_TSGRISM data).

**Comment by nden** [comment]
Closed by #1249
