### ISSUE TITLE
Update calspec2 to always build a single IFU cube

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1265]
When cube_build is called for a single input exposure, which is always the case when it's called from the calspec2 pipeline, it should always return a single IFU cube even when the input data span multiple wavelength bands. Cube_build is capable of doing this by setting the step parameter "output_type=multi". The calspec2 pipeline needs to be updated to always call cube_build in this way.

**Comment by hbushouse** [comment]
Updating the call to cube_build in the calspec2 python module to include the output_type argument, e.g.
`cube = self.cube_build(input, output_type='multi')`
doesn't work because of the known issues with the .call versus .run methods on steps, so the next best approach is to just modify the default calwebb_spec2.cfg file to include:
```
      [[cube_build]]
        save_results = True
        output_type = multi
```
but that doesn't allow for someone to run the calspec2 pipeline by just referencing the pipeline class, e.g.
`strun jwst.pipeline.Spec2Pipeline my_rate.fits`
because then the output_type argument won't get included.

So what's the best approach to making sure calspec2 always uses this argument when calling cube_build?

**Comment by hbushouse** [comment]
@jdavies-st @stscieisenhamer @bernie-simon  any thoughts?

**Comment by stscieisenhamer** [comment]
Bottom line first: If output_type='multi' has to be this way and is not user-changeable in Spec2Pipeline, then I believe you can do the following in code:
```
self.cube_build.output_type = 'multi'
cube = self.cube_build(input)
```
If this option, while running Spec2Pipeline could be changed, then <big discussion of what the appropriate defaults should be occur> and the `spec` variable for `cube_build` is set to default to `multi`.

That will be 2cents....

**Comment by jdavies-st** [comment]
Agree with @stscieisenhamer .  At the top of the spec2 pipeline we have
```
    step_defs = {
        'bkg_subtract': background_step.BackgroundStep,
        'assign_wcs': assign_wcs_step.AssignWcsStep,
        ...
        'cube_build': cube_build_step.CubeBuildStep,
        'extract_1d': extract_1d_step.Extract1dStep
    }
```
which instantiates `self.cube_build`.  Now you can just edit anything in the `spec` of `cube_build` as shown above.

If this is the default way of running `cube_build` in the pipeline, then it might be worth having it be the default.

**Comment by hbushouse** [comment]
Unfortunately we can't make output_type=multi the default for all occurrences of cube_build in pipelines, because it needs to use "multi" when run in calspec2, but when run in calspec3 we want it to not be multi (i.e. we need to allow it to build separate cubes for each wavelength band).

So just hardwiring `self.cube_build.output_type='multi'` in calwebb_spec2.py seems to be the way to go.
