### ISSUE TITLE
ExtractModel defines __del__: is this necessary?

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1272]
`__del__` methods can be detrimental to the garbage collection algorithm, in particular in the removal of circular references. There is no commentary in the code, so wondering if anyone would know a reason for the this method on this model. This is the only model, and in fact the only code in the jwst package, that defines `__del__`.

**Comment by jdavies-st** [comment]
@philhodge ?

**Comment by philhodge** [comment]
It isn't a model, it's just a class in extract_1d.  I probably added the `__del__`, but I don't remember why.  It looks harmless to me:

    extract_model = ExtractModel(input_model, slit, **extract_params)

    ap = get_aperture(data.shape, extract_model.wcs, extract_params)
    extract_model.update_extraction_limits(ap)
    extract_model.log_extraction_parameters()

    extract_model.assign_polynomial_limits()
    (ra, dec, wavelength, net, background) = extract_model.extract(data)
    del extract_model

**Comment by hbushouse** [comment]
It's defined in /extract_1d/extract.py, but never used. Should it be removed just to be on the safe side?

**Comment by philhodge** [comment]
It is used.  See line 1269 in extract_1d/extract.py.  That code snippet was included in the comment I made yesterday.

How is it causing a problem?

**Comment by stscieisenhamer** [comment]
No immediate problem except for what was said in the initial comment. However, since we are dealing with memory leak issues, and considering that there is no apparent compelling reason for keeping it, I would suggest removing the method; as of Python 3, garbage collection should handle all this anyways.

**Comment by stscieisenhamer** [comment]
Apologies for my short-attention-span-CRS: To finish the last comment, I will be removing this method.

**Comment by jdavies-st** [comment]
The other option would be to call the method something other than `__del__`, so that it doesn't override the behavior of `del`.  If you still want to set the attributes of the class to `None`, then perhaps you could just rename it `reset` or something similar and call it appropriately.
