### ISSUE TITLE
Convert reference data from float to complex, if necessary

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1277]
The reference data for reference pixel correction for NIRSpec IRS2 data are 1-D arrays of complex numbers.  The NIRSpec team has delivered reference files (tables) with the data declared as float, i.e. interleaved real and imaginary parts.  The refpix step should check for this case and convert the data on-the-fly to complex.

**Comment by hbushouse** [comment]
Check to see if new ref files are selected in latest CRDS context. If so, merge.

**Comment by hbushouse** [comment]
Fixed in #1279
