### ISSUE TITLE
Subtract background for WFSS/GRISM data

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1283]
The background subtraction in calspec2 (calwebb_spec2) should be applied for WFSS/GRISM data.  Here is a description from @hbushouse 

It needs to work by taking a full-frame background reference image (from CRDS) and then scaling the overall level of that background image to match the intensity of the blank sky regions of the grism science exposure, and then finally subtracting that full-frame scaled background image from the full-frame grism exposure.

**Comment by hbushouse** [comment]
See #599
