### ISSUE TITLE
mrs_imatch does not have a .cfg file

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#1287]
Should it?

**Comment by hbushouse** [comment]
The step class does allow for a couple of arguments:

    spec = """
        # General sky matching parameters:
        bkg_degree = integer(min=0, default=1) # Degree of the polynomial for background fitting
        subtract = boolean(default=False) # subtract computed sky from 'images' cube data?

so in that case, yes it should have a .cfg file to allow setting those arguments.
