### ISSUE TITLE
resample_step output must have correct meta.wcsinfo block

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#1292]
Resample produces output with a correct `meta.wcs` GWCS object, but it does not update the `meta.wcsinfo` block.  It ought to do that, especially since the the FITS WCS keywords can completely describe the WCS in a resampled image.

**Comment by hbushouse** [comment]
We should try to get this fixed soon so that it can be included in an upcoming B7.1 patch. Having correct WCS is important to other subsystems downstream, like archive preview.

**Comment by jdavies-st** [comment]
@nden and I have discussed this.  I can hack together a solution for now.

The better solution may be new functionality in `gwcs` that allows round tripping of a WCS object between `astropy.wcs` and `gwcs`.  Would be interested in thoughts on this.
