### ISSUE TITLE
Calspec3 outlier detection needs to use resample_spec

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1294]
The calspec3 pipeline calls outlier_detection, which in turn is using the resample step to attempt to resample the input "images", but because these data are spectra, it should be calling resample_spec instead. This only applies to slit-like spectra, not IFU data. For IFU data outlier_detection needs to use cube_build to do resampling to a common output frame (as already documented in #1286).

**Comment by stsci-hack** [comment]
The work done in #1369 allowed outlier_detection to call resample_spec for spectroscopic data, while using outlier_detection logic specific to spectroscopic data where necessary.
