### ISSUE TITLE
Update extract_1d to deal with grism mode observations 

### ISSUE THREAD

**Issue by sosey** [STScI-JWST/jwst#1297]
The current version of extract_1d is expecting slit or IFU observations, not extracted grism spectra. We need to update the logic to detect NRC_GRISM and NIS_WFSS exposures and process them. Neither instrument currently has an EXTRACT1D type reference file. I looked at MIRI for an example of what this file contains:
```
 {
        "id": "MIR_LRS-FIXEDSLIT",
        "region_type": "target",
        "bkg_order": 0,
        "dispaxis": 2,
        "extract_width": 11,
        "nod2_offset" : 15
        },

        {
        "id": "MIR_LRS-SLITLESS",
        "region_type": "target",
        "bkg_order": 0,
        "dispaxis": 2,
        "extract_width": 11,
        "nod2_offset" : 0
        }
```
Looking at this information, I'm not sure that it's proper to have a similar reference file for grism modes. The dispersion axis for NIRCAM depends on the module and grism in use. This information has to be known for extract2D in order to create the bounding boxes around each object detected in the direct image photometry catalog. For NIRISS there is only 1 detector, but the column and row dispersions go in opposite sense from the similar named grisms in NIRCAM.  

It's possible that the EXTRACT1D reference file could be created for each instr/module/grism to contain the dispersion axis, but I'm not sure if this adds use.  Additionally the background subtraction is done before extract2d and the extraction height and extraction width change with each object.  @philhodge  is the knowledge man on this, what do you think?

The extracted 2D spectra will be entering extract_1D, each one has a WCS object which should return the appropriate wavelength-pixel value give x,y location on the image. In addition, these attributes have been added:
```
.name
.xstart
.xsize 
.ystart
.ysize 
```
Are there any other values, in absence of an EXTRACT1D  file that would be useful to add to these to facilitate extraction? The aperture is the entire image. The dispersion length is the entire image,  I'm not sure if the teams want the cross-dispersion size to also be the entire image.

**Comment by philhodge** [comment]
As long as there would never be a nod offset, I don't see any reason why a reference file would be required.  The step could assume that the dispersion direction is the longer axis of the input image.  I could take the extraction region to be the full image in both directions.  If that's not the case, or if background subtraction should be done, one could create a suitable reference file and use the override_extract1d option to specify it.

**Comment by hbushouse** [comment]
No concept of nod offsets for WFSS mode. Exposures will be dithered, but that will be taken care of upstream by having extract_2d produce a cutout that always has the source spectrum centered within the bounds of the cutout. So it does sound like there's no real need for an extract1d ref file for WFSS modes.

**Comment by philhodge** [comment]
> Are there any other values, in absence of an EXTRACT1D file that would be useful to add to these to facilitate extraction?

I need the spectral order number, e.g. spectral_order (keyword sporder).  This is in wcsinfo.schema.yaml, but I don't find it in an _extract_2d.fits file.

**Comment by philhodge** [comment]
Closed by PR 1334.
