### ISSUE TITLE
Level-1b _uncal.fits files are getting extra extensions added

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1298]
The latest version of the set_telescope_pointing script included in B7.1rc3 is loading the intermediate _uncal.fits file created by SDP into a jwst datamodel using the generic datamodels.open() function:

https://github.com/STScI-JWST/jwst/blob/master/jwst/lib/set_telescope_pointing.py#L9

SDP has set the DATAMODL keyword in the headers of these files to 'RampModel' or 'MIRIRampModel', which means that datamodels.open() loads the file into this type of model, hence when the script has finished updating meta data and saves the model, the resulting new version of the _uncal.fits file now has all the SCI array up-converted to float32 and has added all the extra extensions like ERR, PIXELDQ, and GROUPDQ. This should not be happening.

We could have SDP set DATAMODEL='Level1bModel' instead of 'RampModel', in which case none of the extra extensions would get added when datamodels.open() is called in the pointing script. However that also means that when datamodels.open() is called in the calwebb_detector1 pipeline to process level-1b files, the data would also get loaded into a Level1bModel, when we want it loaded into a RampModel (or MIRIRampModel).

So I think the best approach to fix the issue with the pointing script is to open the level-1b FITS file using datamodels.DataModel(), which loads it into a base model without any special extensions. The one other change that might be needed to make this work is to add wcsinfo.schema.yaml to the DataModel class, because right now it only includes core.schema.yaml and the pointing script needs access to the WCS and pointing keywords that are no longer defined in core.schema.yaml.

**Comment by nden** [comment]
This is fixed in #1278

**Comment by hbushouse** [comment]
Fixed by #1278
