### ISSUE TITLE
Failure when processing MIRISIM MRS output at assign_wcs step with jwst b71.rc3

### ISSUE THREAD

**Issue by baileyji** [STScI-JWST/jwst#1300]
```
2017-10-12 01:02:53,689 - stpipe.MRSMetaPipeline.assign_wcs - INFO - Step assign_wcs running with args ((<jwst.datamodels.image.ImageModel object at 0x1168ab710>, None),).
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-6eab71f2384c> in <module>()
      1 #Run the pipeline
      2 files = [f for f in glob('./*mirisim/det_images/*exp1.fits')]
----> 3 run_pipe(files[0])
      4 pool = Pool(6)
      5 pool.map(run_pipe, files[1:])

<ipython-input-1-5e76bd6ce1d3> in run_pipe(f)
    152                                   'cube_build': {'output_dir': os.path.dirname(f),
    153                                                  'output_file': f[:-4] + 'cube_radec.fits'}})
--> 154     pipe(f)
    155 
    156 

/Users/one/anaconda2/envs/jwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-macosx-10.7-x86_64.egg/jwst/stpipe/step.pyc in run(self, *args)
    368             else:
    369                 try:
--> 370                     result = self.process(*args)
    371                 except TypeError as e:
    372                     if "process() takes exactly" in str(e):

<ipython-input-1-5e76bd6ce1d3> in process(self, input)
    129         input = self.jump(input)
    130         input = self.ramp_fit(input)
--> 131         input = self.assign_wcs(input)
    132         input = self.flat_field(input)
    133         # input = self.straylight(input)  #Not simulated by mirisim

/Users/one/anaconda2/envs/jwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-macosx-10.7-x86_64.egg/jwst/stpipe/step.pyc in run(self, *args)
    368             else:
    369                 try:
--> 370                     result = self.process(*args)
    371                 except TypeError as e:
    372                     if "process() takes exactly" in str(e):

/Users/one/anaconda2/envs/jwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-macosx-10.7-x86_64.egg/jwst/assign_wcs/assign_wcs_step.pyc in process(self, input)
     45     def process(self, input):
     46         reference_file_names = {}
---> 47         with datamodels.open(input) as input_model:
     48             # If input type is not supported, log warning, set to 'skipped', exit
     49             if not (isinstance(input_model, datamodels.ImageModel) or

/Users/one/anaconda2/envs/jwst/lib/python2.7/site-packages/jwst-0.7.8rc3.dev10-py2.7-macosx-10.7-x86_64.egg/jwst/datamodels/util.pyc in open(init, extensions, **kwargs)
     96         for item in init:
     97             if not isinstance(item, int):
---> 98                 raise ValueError("shape must be a tuple of ints")
     99         shape = init
    100 

ValueError: shape must be a tuple of ints
```

**Comment by hbushouse** [comment]
The ramp_fit step now always returns two objects. The first is the datamodel for the _rate product (data averaged over all integrations) and the second is the datamodel for the _rateints product (per-integration results), if one is produced. If the input has NINTS=1, then no _rateints product is created and the second object returned by ramp_fit will be None.

In any case, I'm guessing this may be causing the problem, because in your statement:

 input = self.ramp_fit(input)

the "input" returned by ramp_fit will now be a tuple of either an ImageModel and None, or an ImageModel and a CubeModel. This then causes assign_wcs to complain when that tuple is provided as input. You probably only ever care about or want the _rate product, which is the first datamodel in the tuple returned by ramp_fit, so a simple change in the call to assign_wcs to:

 input = self.assign_wcs(input[0])

should do the trick.

**Comment by hbushouse** [comment]
@baileyji Did the change to assign_wcs argument fix this problem?

**Comment by baileyji** [comment]
This is deep inside stock stsci code. I thought your comment might be for someone there. The only thing I could think of on my end would be a wrong context, but I tried a few with no effect.

**Comment by hbushouse** [comment]
This code block:
```
in process(self, input)
129 input = self.jump(input)
130 input = self.ramp_fit(input)
--> 131 input = self.assign_wcs(input)
132 input = self.flat_field(input)
133 # input = self.straylight(input) #Not simulated by mirisim
```
looks to me like it's in a personal script of some sort. We have nothing like this in any of our pipeline code. Our calwebb_detector1 pipeline stops at calling the ramp_fit step and then the calwebb_spec2 pipeline picks up with calling assign_wcs. Changing line 131 to:
```
input = self.assign_wcs(input[0])
```
should fix the issue with ramp_fit (immediately preceding) now returning a tuple.

**Comment by stscieisenhamer** [comment]
`MRSMetaPipeline` is not in the jwst package, unless it is somehow dynamically created.

**Comment by baileyji** [comment]
Right, this is just a meta pipeline. I missed that that is what you were talking about. I'm guessing there isn't a summary page that talks about how we should update custom pipelines with new releases. 

I guess: input = self.assign_wcs(input[0] if isinstance(input, tuple) else input) will preserve compatibility with the version in MIRISIM.

class MRSMetaPipeline(Pipeline):
    from jwst.dq_init import dq_init_step
    from jwst.saturation import saturation_step
    from jwst.linearity import linearity_step
    from jwst.rscd import rscd_step
    from jwst.lastframe import lastframe_step
    from jwst.refpix import refpix_step
    from jwst.persistence import persistence_step
    from jwst.jump import jump_step
    from jwst.ramp_fitting import ramp_fit_step
    from jwst.assign_wcs import assign_wcs_step
    from jwst.flatfield import flat_field_step
    from jwst.fringe import fringe_step
    from jwst.photom import photom_step
    from jwst.cube_build import cube_build_step

    step_defs = {'dq_init': dq_init_step.DQInitStep,
                 'saturation': saturation_step.SaturationStep,
                 'linearity': linearity_step.LinearityStep,
                 'lastframe': lastframe_step.LastFrameStep,
                 'refpix': refpix_step.RefPixStep,
                 'persistence': persistence_step.PersistenceStep,
                 'jump': jump_step.JumpStep,
                 'ramp_fit': ramp_fit_step.RampFitStep,
                 'assign_wcs': assign_wcs_step.AssignWcsStep,
                 'flat_field': flat_field_step.FlatFieldStep, # include_flat
                 'fringe': fringe_step.FringeStep,
                 'photom': photom_step.PhotomStep,
                 'cube_build': cube_build_step.CubeBuildStep}

    # start the actual processing
    def process(self, input):
        input = datamodels.open(input)
        input = self.dq_init(input)
        input = self.saturation(input)
        input = self.linearity(input)
        input = self.lastframe(input)
        input = self.refpix(input)
        input = self.persistence(input)
        input = self.jump(input)
        input = self.ramp_fit(input)
        input = self.assign_wcs(input)
        input = self.flat_field(input)
        input = self.fringe(input)
        input = self.photom(input)
        input = self.cube_build(input)
        return input
