### ISSUE TITLE
Task: MIRI first-frame correction step

### ISSUE THREAD

**Issue by karllark** [STScI-JWST/jwst#1312]
The MIRI first frame is currently not used by anyone on the MIRI team in analyzing data.  There is some kind of transient seen and no correction algorithm is currently available. 

This step should flag the 1st frame as bad and later steps should not use it.  This is similar to the 1st pass at the last frame correction.
Later, there may be a correction algorithm.

**Comment by karllark** [comment]
I will work on adding this step this week based on the existing last-frame correction step.
Cannot assign milestones, but someone who can should add this for B7.2.

**Comment by hbushouse** [comment]
At what location in the MIRI data flow in calwebb_detector1 should this step be added?

**Comment by karllark** [comment]
Right before the last-frame correction.

**Comment by jemorrison** [comment]
I just looked at the calwebb_detector1.py code and the I think the order of the steps is wrong
it should be dq_init, saturation,reject first frame, reject last frame,  [ipc], linearity, rscd, dark current, refpix.
The RSCD correction uses the last frame from the last integration for a correction. Eventually we hope to have a last frame correction which will need to be applied before the RSCD correction.  It really does not matter if we reject last frame and then first frame or vice verse we just want to occurring  as one of the first steps in the pipeline. 
The RSCD correction in the JWST pipeline is an old algorithm I need to update it to the new algorithm that James Colbert has given me. It could be that the old algorithm is using the last frame- let me check

**Comment by karllark** [comment]
@jemorrison: your ordering corresponds to what is the on the CALDETECTOR1 confluence page.  
With one exception, the IPC is in a different place (before first-frame correction).  Not sure this is important at this point as we are not doing IPC.  Where IPC fits in the pipeline will need to be discussed if/when we decide to use it - at least this is my thinking.

**Comment by hbushouse** [comment]
Fixed by #1327.
