### ISSUE TITLE
Refactor and simplify file I/O for Step

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1322]
In light of further development of the level 3 pipelines, inclusion of associations, and issues [such as this](https://github.com/STScI-JWST/jwst/pull/1316), a refactor of the Step file I/O is in order.

TMI, a "shower revelation" occurred: Up to this point, all work on the I/O has attempted to preserve all of the existing logic. However, much of the I/O API appears to have been designed before much of anything had been developed, except maybe `calwebb_detector1`. However, with everything being read and processed through `DataModel`s and associations, where only suffix changes occur, much of the current logic can be removed.  The remaining code can be refactor to take advantage of the `DataModel`/association input.

# Implementation 
- [ ] PR #1316 
- [x] Resolves #1016
- [x] Resolves #1288
- [x] Resolves #942 
- [x] Resolves #798 
- [x] #756 _previously resolved_

**Comment by hbushouse** [comment]
We should at least leave in place the existing infrastructure that creates an output file by just appending the class name of the step or pipeline being run in cases where no other output file name has been provided, such as when running a single step from the command line (strun).  For example, if you just run the jump step without specifying output_file, you should get an output file name that is a copy of the input file name with the additional suffix "jump" (or is it JumpStep?) appended.

**Comment by stscieisenhamer** [comment]
# Design

## Suffix replacement
If a filename ends with a _known_ suffix, that suffix will be replaced with the new suffix. Otherwise, the new suffix will be appended.

Examples:
1. `filename_rates.fits` => `filename_cal.fits`
2. `filename_mygoofytest.fits` => `filename_mygoofytest_cal.fits`
3. `filename.fits` => `filename_cal.fits`

## Suffix determination
If a suffix has not been defined, either by setting `Step.suffix` or as an argument to `Step.save_model`, the name of the Step is used as the suffix

## Cases
1. `strun` a `Step` without `output_file` or `suffix` defined:
    ```
    input_filename<_index>_stepname.input_file_ext
    ```
    where the `_<index>` is added if there are multiple results. **Multiple results** is any of: `list`, `tuple`, `list`-like, or `ModelContainer`

2. `strun` a `Step` with `output_file` specified and `Step.suffix` is defined:
    ```
     output_file<_index>_suffix.output_file_ext
    ```

3. `Step` creates multiple results and creates/modifies names on its own. The desired output names are then stored in the `meta.filename` of the return model(s). To tell the `Step` architecture to use `meta.filename`, specify `Step.output_use_model = True`:
    ```
    model_1_meta_filename_suffix.meta_filename_ext
    model_2_meta_filename_suffix.meta_filename_ext
    ...

    `cube_build` is an example of this brute-force file naming. My goal is to update the API so that steps do not need to have such inherent knowledge; it is looking possible to do this
