### ISSUE TITLE
cube_build cubes are not written to disk if when a multiprocessing pool is used.

### ISSUE THREAD

**Issue by baileyji** [STScI-JWST/jwst#1323]
With b7.1rc3 simple pipelines like the one below will no longer write their output cubes to disk when run via a process pool.

```Python
class MRSCubePipeline(Pipeline):
    from jwst.cube_build import cube_build_step
    step_defs = {'cube_build': cube_build_step.CubeBuildStep}

    def process(self, input):
        input = datamodels.open(input)
        return self.cube_build(input)

def runCubePipe((f, args)):
    MRSCubePipeline(steps={'cube_build': args}).run(f)

pool = Pool(4)
pool.map(runCubePipe, arglist) #Works but no files written
pool.close()

for a in arglist: runCubePipe(a) #works properly but is slow
```

**Comment by jemorrison** [comment]
Lets back up a bit. I do need more information from you - like what is in arglist and what is the input (association, model container, data model ) 
But have you first tried something simple like running the calspec3 pipeline ?
That way we can see if it is a cube_build problem when running in calspec3 or some not quite right in your pipeline  set up.

**Comment by baileyji** [comment]
arglist is a list of tuples. The first element is always the association file name for an association of 12 photometry step output files from a 2-point dither 12 sub-band simulation. The second is a dictionary that cycles through the band channel combinations and sets output file names.

('dither2_asn.json',
 {'band': 'SHORT',
  'channel': '1',
  'output_dir': '/Users/one/CloudStation/miri/mirisim/flat10',
  'output_file': 'dither2_asn.cube1SHORTradec.fits',
  'rois': 0.15000001})

**Comment by jemorrison** [comment]
We need to test this with the latest cube_build.  If it still does not work first just try to use the pipeline calspec3 pipeline.

**Comment by baileyji** [comment]
This look slike a python 2 vs 3 issues. My conda is set up to use 2 by default. 
conda create -n jwstb7.1cr3 -c http://ssb.stsci.edu/conda-dev python=3 jwst seems to have resolved the issue.

**Comment by stscieisenhamer** [comment]
Hmmm, this particular issue should not have been a py2/py3 thing.

However, and this may have already announced, but everyone should take note that all further development in astropy will only be python3-compatible; I think all 3.0dev versions since 1Oct can have python2 incompatibilities. The corollary is that all jwst software from this point, is inherently python3 only also, though technically there is nothing, yet, that is python2 incompatible.

**Comment by baileyji** [comment]
Well it could be that something that was committed in the day days since I tried fixed it...
