### ISSUE TITLE
Add spectral order to MultislitModel

### ISSUE THREAD

**Issue by sosey** [STScI-JWST/jwst#1325]
I'm looking for a place to save the spectral order that was extracted for the grism "slit", I don't see anything already in the model that is obvious to me to represent the objects spectral order that was extracted already - should we add a new entry "specorder" to the datamodel?

@nden @hbushouse

**Comment by philhodge** [comment]
wcsinfo.schema.yaml has a spectral_order (FITS keyword SPORDER), so just now I copied that into multispec.schema.yaml (except that I changed type from number to integer).  So yes, I think adding it to multislit.schema.yaml would be a good idea.

**Comment by nden** [comment]
A slit is an ImageModel. Should slit.meta.wcsinfo.spectral_order be updated?

**Comment by philhodge** [comment]
That makes sense, as long as that info will actually end up in the MultiSlitModel file.

**Comment by nden** [comment]
It should end up in the SCI extension.

**Comment by sosey** [comment]
ah, I missed that. So don't update slist[].spectral_order, just update the mode.meta. will do.
