### ISSUE TITLE
cube_build step memory usage increased with b7.1rc3 from ~4 GB to ~11GB 

### ISSUE THREAD

**Issue by baileyji** [STScI-JWST/jwst#1326]
It looks like the cube_build memory usage has significantly increased with the latest changes. Prior to rc3 and since the initial memory issue 16GB was sufficient to build 4 sub-channel cubes simultaneously from either 2-pt or 4-pt data. Now the piepline is running at 10.6GB per task. Half to 80% of this new usage is being flagged as compressible on osx which seems to indicate it isn't in heavy (any?) use by the interpreter.

**Comment by stscieisenhamer** [comment]
May not be related, but if you have not updated you conda-dev environment since 12Oct, you may want to. An issue with astropy.modeling and memory usage was resolved in astropy on that day. I see the current version as '3.0.dev20401'. Most reliable check is to:
```
>>> import astropy
>>> astropy.__version__
```

**Comment by baileyji** [comment]
I reinstalled conda-dev this morning and it looks like we are back to normal, though I'd note that the astropy installed by the jwst conda-dev command is dev20010.

**Comment by baileyji** [comment]
Actually I may have spoken too soon. This may be sub-band dependent or number of cubes dependent. It was ok through the first 3 but is slowly climbing at I'm seeing 5.8-6.5GB now.

**Comment by baileyji** [comment]
And now I'm seeing 12.4 GB as I'm working on the 7th of the 12 subband cubes

**Comment by stscieisenhamer** [comment]
Don't understand why you are getting only dev20010. I just did the following and get 3.0.dev20479:
```
$ conda create -n yetanothercondadev -c http://ssb.stsci.edu/conda-dev python=3 jwst
$ ipython
>>> import astropy
'3.0.dev20479'
```
To confirm whether you have the fixed astropy, do the following. Note, if you see something at the end of the listing that deals looks like `cls.registry.add(cls)` or anything that has `registry`, then you have too old a version of astropy.
```
$ ipython
>>> from astropy.modeling.core import _ModelMeta
>>> _ModelMeta.__init__??
Signature: _ModelMeta.__init__(cls, name, bases, members)
Source:
    def __init__(cls, name, bases, members):
        # Make sure OrderedDescriptorContainer gets to run before doing
        # anything else
        super().__init__(name, bases, members)

        if cls._parameters_:
            if hasattr(cls, '_param_names'):
                # Slight kludge to support compound models, where
                # cls.param_names is a property; could be improved with a
                # little refactoring but fine for now
                cls._param_names = tuple(cls._parameters_)
            else:
                cls.param_names = tuple(cls._parameters_)

        cls._create_inverse_property(members)
        cls._create_bounding_box_property(members)
        cls._handle_special_methods(members)
File:      ~/anaconda3/envs/junk/lib/python3.6/site-packages/astropy/modeling/core.py
Type:      function
```

**Comment by baileyji** [comment]
I'm guessing because I didn't specify python=3. With that I get dev20481.

**Comment by baileyji** [comment]
Using conda create -n yetanothercondadev -c http://ssb.stsci.edu/conda-dev python=3 jwst appears to have resolved this issue. My conda defaults to 2.7 so this may be a 2vs3 issue.
