### ISSUE TITLE
Consider adding slit attributes to CubeModel in extract_2d

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#1332]
`extract_2d` populates a number of attributes when extracting an NRS MSA or FIXED slit. In the case of NRS_BRIGHTOBJ none of those is populated because the output is a `CubeModel`. Consider populating some of them in `CubeModel`. 
More attributes are populated for MSA slitlets that fixed slits. Consider setting some more of the MSA slit attributes to fixed slits if relevant.

**Comment by nden** [comment]
@hbushouse Should we populate `SlitModel.xstart`, `SlitModel.xsize`, `SlitModel.ystart`, `SlitModel.ysize` and `SlitModel.name` for NRS_BRIGHTOBJ? Of course it's now a SlitModel, not a CubeModel.

**Comment by hbushouse** [comment]
Make it so.
