### ISSUE TITLE
Update MIRI RSCD correction

### ISSUE THREAD

**Issue by jemorrison** [STScI-JWST/jwst#1360]
The MIRI RSCD corrections needs to be updated to be in line with the recommended MIRI team algorithm,

**Comment by jemorrison** [comment]
Add saturation checking and modification to the Counts in the last frame in the last integration if the data is saturated. A different algorithm is used to find the scale factor for the RSCD correction

**Comment by jemorrison** [comment]
@stscicrawford

**Comment by hbushouse** [comment]
Since merging https://github.com/STScI-JWST/jwst/pull/1886 all MIRI regression tests that execute the RSCD step are throwing an error, because the updated code is getting old reference files. Is there an ETA on when the new form of the RSCD ref files will be delivered to CRDS?

**Comment by stscicrawford** [comment]
@hbushouse  please see https://jira.stsci.edu/browse/CRDS-190 and similar Jira tickets.  We can raise this as an issue to discuss this afternoon to check on the progress of it.
