### ISSUE TITLE
outlier_detection bitmask and dq array handling needs to be updated

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#1379]
Update `outlier_detection` to use the `datamodels.dqflags.pixel` dictionary of named flags instead of raw bit values.

So instead of the code explicitly referring to bit 4, instead refer to `dqflags.pixel['JUMP_DET']` where needed.

**Comment by stsci-hack** [comment]
No changes can be implemented for the use of hard-coded dqflag values in the outlier_detection as those values are used in defining the default parameter values for the step which requires hard-coded values, not variables.  

However, the resample package relied on default dqflag values as default parameter values and those instances should be corrected.
