### ISSUE TITLE
calwebb_detector1 should skip steps for TSO exposures

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1400]
The JCCWG has determined that several steps in the calwebb_detector1 pipeline should not be applied to exposures from Time-Series Observations (TSO). The list of steps to be applied to TSO exposures is documented at https://confluence.stsci.edu/display/JWSTCC/CALDETECTOR1

At this time, the steps to be skipped for TSO exposures are:
ipc
lastframe (MIRI only)
persistence

**Comment by hbushouse** [comment]
There is currently some debate as to the best approach for implementing this. It could be done by using a custom .cfg file, e.g. calwebb_tso1.cfg, that has appropriate steps set to be skipped. Or the logic to skip steps could be implemented within the calwebb_detector1.py module itself.

**Comment by sosey** [comment]
It would be cool if the cfg files were kept in CRDS and could just be updated as necessary at some point...but it seems like step skipping is the purview of the cfg files to begin with? Or maybe both if the module should never be used with TSO data it should probably refuse to run it regardless of cfg setting?

**Comment by hbushouse** [comment]
The idea of putting cfg files in CRDS is one that's been around for several years. We've just never gotten around to implementing the mechanisms to make use of it (i.e. the cal pipeline modules would need to do a call to get_reference_file to get the appropriate cfg file).

What's different about this particular case is that there's nothing that's stopping TSO data from going through any of these steps, as opposed to some of the logic we have in place in other pipelines, like calwebb_spec2, where certain steps just can't physically be applied to certain types of exposures (e.g. you can't run cube_build on non-IFU exposures). The steps in calwebb_detector1 are perfectly capable of applying their corrections to TSO exposures. It's simply a choice based on suitability or desirability for the purpose of the science.

So that's the drawback to hardcoding the logic into the calwebb_detector1.py module itself. Some users may feel it's OK to apply the IPC step to their TSO data, while others don't. If you hardwire it in the python code, then it's very difficult for a user to do custom processing. It's much easier to turn things on and off in real-time via the .cfg file.

**Comment by hbushouse** [comment]
Final consensus is to go with a custom calwebb_tso1.cfg file that has skip arguments for the steps to e skipped by default. This allows users to easily modify the flow as they wish.
