### ISSUE TITLE
Straylight Step produces blocks of negative values 

### ISSUE THREAD

**Issue by jemorrison** [STScI-JWST/jwst#1435]
David Law gave me some simulated MIRI data that had been run through calspec2. The cal files had strange blocks of negative values in various parts of the image. I reprocessed the data and by turning off the straylight step these blocks of negative pixels go away. The negative blocks seem to be correlated to where there a hot pixels in inter-slice region.

**Comment by jemorrison** [comment]
The straylight step uses the gap between the slices to determine a correction. There is no check if the slice gap pixels have the dqflags.pixel of DO_NOT_USE, DEAD, HOT - this needs to be added to straylight.py so hot pixels are not dominating the determination of the straylight.

**Comment by hbushouse** [comment]
In a more general way, the entire straylight correction algorithm needs to be updated/replaced with algorithm #2 that was provided by the MIRI IDT in a previous CDP. The new algorithm should avoid some of these issues.

@jemorrison has the necessary information in hand to begin implementation.

**Comment by hbushouse** [comment]
INS is tracking in https://jira.stsci.edu/browse/JP-242

**Comment by hbushouse** [comment]
@jemorrison please confirm whether this problem is fixed by implementation of the new straylight algorithm in #1741.

**Comment by jemorrison** [comment]
closed with pr #1741 and #1767
