### ISSUE TITLE
Rule: NRS_FIXEDSLIT not creating associations

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1437]
During Build7.1 integration, it was noted that 95115 did not create any Level3 associations for `exp_type` == `nrs_fixedslit`.

Also see 98005

**Comment by stscieisenhamer** [comment]
Looking through some SDP runs and running the generator on the 95115/98005 pools, associations do get created. However, the SDP runs do not have any associations. This is most likely due to the generator not being triggered in the workflow, which is a workflow issue. Since there appears to be no issues with this exposure type, closing.

**Comment by hbushouse** [comment]
Is there a DR associated with this problem? If so, we need to update the DR with this info.

**Comment by stscieisenhamer** [comment]
This issue arose from either an email conversation or comments made during a DMS Design meeting. If a DR was filed, I am not aware of it.
