### ISSUE TITLE
calwebb_ami3 dies in blendheaders if amiavg results not saved to a file

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1452]
The calwebb_ami3 pipeline is dying at line 141 on the statement
```
blend.blendfitsdata([targ_avg_output_file, psf_avg_output_file], result)
```
when the default value of `save_averages = False` is used, because `targ_avg_output_file` and `psf_avg_output_file` are not defined in that case (no file or file name were created for them).

**Comment by stsci-hack** [comment]
Fixed by #1790 with nightly regression tests passing.
