### ISSUE TITLE
does nrs_image get 2b processing?

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1467]
Per #199 it was determined that nrs_image does not get "higher level processing". However, the question of level2 processing still needs to be addressed.

**Comment by hbushouse** [comment]
The NIRSpec team has requested that NRS_IMAGE exposures go through level-2a and level-2b processing, so that does imply creating level-2 ASN's for them. Same would be true for other imaging-like NIRSpec modes, such as NRS_TACQ, NRS_FOCUS, NRS_TACONFIRM, etc. They all require level-2b processing.

**Comment by stscieisenhamer** [comment]
# Implementation
- [x] Update #1188 
- [ ] tests
- [ ] code
- [ ] tests
