### ISSUE TITLE
TSO processing for calwebb_image2

### ISSUE THREAD

**Issue by karllark** [STScI-JWST/jwst#1472]
The TSO observations need to have slightly different processing in calwebb_image2 than the rest of the observations.
Specifically: the background subtraction step should not be done.  Possible this will happen naturally as it is not clear if background data can be taken with TSO observations.

**Comment by stscieisenhamer** [comment]
After reviewing APT and jdocs for all imaging, there are no modes that include any type of background specification, regardless of whether its TSO or not.  Recommend no changes unless we really just want to bake-in the blocking.

**Comment by hbushouse** [comment]
👍
