### ISSUE TITLE
Coron3Pipeline missing association candidate id in psfsub output file name

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1478]
# Issue
From regression `pipeline/test_coron3_1.py`, the file 
```
jw9999947001_02102_00002_nrcb3_psfsub.fits
```
 is created. This should have the association candidate id in it as follows:
```
jw9999947001_02102_00002_nrcb3_a3001_psfsub.fits
```
This is similar to the correctly named file
```
jw9999947001_02102_00001_nrcb3_a3001_crfints.fits
```

# Implementation
- [x] bump version
- [x] tests
- [x] calwebb_coron3
    - [x] stack_refs is producing a single file with name syntax <prod_name>_psfstack.fits, where <prod_name> includes <ac_id>. This is correct.
    - [x] align_refs, which loops over the n science exposures, is producing a single file with name syntax <prod_name>_psfalign.fits. This is INCORRECT, as noted in a previous comment. There needs to be 1 _psfalign product per input science _calints exposure and they need to use the input (level-2 exposure-based) file name, with the addition of the <ac_id> field and update the suffix from _calints to _psfalign.
    - [x] klip, which loops over the n science exposures, is producing one _psfsub product for each input science member, using the file name syntax <exp_name>_psfsub.fits. This is mostly correct, except for the fact that it's missing the <ac_id> field (as noted above).
    - [x] outlier_detection, which loops over the n science exposures, is producing one crfints product for each input science member, using the file name syntax <exp_name><ac_id>_crfints.fits. This is all correct.
    - [x] resample is producing a single file with name syntax <prod_name>_i2d.fits, where <prod_name> includes <ac_id>. This is correct.
- [x] tests
- [x] bump version

**Comment by hbushouse** [comment]
And I think there are also problems with the file naming for the psfalign product(s). They seem to be getting a level-3 style name, when they should get a level-2 name that's based on the level-2 name of the science target exposure used when doing the aligning.

**Comment by hbushouse** [comment]
As of the current dev version we are getting the following outputs when using a properly constructed ASN file that contains 1 product definition, with all PSF and science exposures as members of that 1 product:

- stack_refs is producing a single file with name syntax <prod_name>_psfstack.fits, where <prod_name> includes <ac_id>. This is correct.

- align_refs, which loops over the n science exposures, is producing a single file with name syntax <prod_name>_psfalign.fits. This is **INCORRECT**, as noted in a previous comment. There needs to be 1 _psfalign product per input science _calints exposure and they need to use the input (level-2 exposure-based) file name, with a simple update from _calints suffix to _psfalign suffix.

- klip, which loops over the n science exposures, is producing one _psfsub product for each input science member, using the file name syntax <exp_name>_psfsub.fits. This is mostly correct, except for the fact that **it's missing the <ac_id> field** (as noted above).

- outlier_detection, which loops over the n science exposures, is producing one _crfints product for each input science member, using the file name syntax <exp_name>_<ac_id>_crfints.fits. This is all correct.

- resample is producing a single file with name syntax <prod_name>_i2d.fits, where <prod_name> includes <ac_id>.  This is correct.

**Comment by hbushouse** [comment]
High priority for B7.2, because it's a bug in the level 4 requirement that satisfies coronagraphic Data Analysis via cal pipeline methods.
