### ISSUE TITLE
When ramp_fit is run in a pipeline, check for skip=True

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1532]
The `ramp_fit` step normally returns two objects.  If `ramp_fit` is run in a pipeline and `skip = True` was specified in the .cfg file, however, the step will just return its input, a single object.  Until this is fixed in a more comprehensive way, calwebb_detector1.py can be modified to explicitly check whether skip was set to True for `ramp_fit`, and if so, the second output object can be set to None.

**Comment by hbushouse** [comment]
Fixed by #1533.
