### ISSUE TITLE
attempt to get product name from association when association is not an input

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1537]
# Issue
When given a single file, calwebb_image3 attempts [to retrieve the output name](https://github.com/STScI-JWST/jwst/blob/master/jwst/pipeline/calwebb_image3.py#L102) from the non-existent association.

# Implementation
- bump version _unneeded_
- [x] tests
-  code _unneeded_
- tests _unneeded_
- bump version _unneeded_

Apparently, something else fixed this issue, most likely #1316. Updated a test and that is all.

**Comment by hbushouse** [comment]
Personally, I don't see the need to make calwebb_image3 capable of handling a single exposure as input, either directly or via an ASN table. If it's given 1 image, it'll skip all steps other than resample and source_catalog. So if someone wants a source catalog from a single exposure they could just run the source_catalog step by itself on the _i2d product that came out of the calwebb_image2 pipeline for that exposure. But if it's not a big amount of work and will save future help calls, go for it.

**Comment by jdavies-st** [comment]
What's the purpose of doing resample before source_catalog in this case?

For fun, I tried running source_catalog on a _cal file, and it crashed. Hmm.

**Comment by hbushouse** [comment]
I assumed that you would want a rectified image as input, but perhaps that's not necessary, if source_catalog can do x/y <--> RA/Dec transforms using the full-blown wcs object that still includes all the distortion terms (so that you get accurate coords for each object).

**Comment by larrybradley** [comment]
@hbushouse In principle, yes.  But `source_catalog` currently requires ` DrizProductModel` as input **and** it is currently using the FITS WCS (not the `gwcs`) because it assumes the image is rectified.

**Comment by jdavies-st** [comment]
Ok, so would it make sense then to allow a single file to go through `Image3Pipeline` in order to allow making a source catalog with RA/DEC positions?

**Comment by hbushouse** [comment]
Yes. And I guess we need to allow for that, because after just rereading our calwebb_image3 docs, they claim that it's possible to do that!
