### ISSUE TITLE
Possible problem with index for flat_field

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1547]
For NIRSpec `MultiSlit` data, the `flat_field` step has an option to write an output file to save the flat field arrays that were constructed on-the-fly.  There is a loop over input slits, and the integer index for that loop is used to assign attributes to the current slit for this output file.  However, there are two `continue` statements within the loop, and if either of these is executed, the index for a subsequent loop can be out of bounds for the slits in the optional output file.

**Comment by hbushouse** [comment]
Fixed by #1549.
