### ISSUE TITLE
TSO Segments

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1561]
Since Time Series Observation (TSO) can go on a long time, the data will be broken up in to _segments_. Associations will need to deal with these as appropriate. 

# Resources
- DMS: [Chunking strategy for TSO SSR files](https://confluence.stsci.edu/display/jwstdms/DMS+Test+Data+Curation+Splinter+Meeting+Series%3A+Chunking+strategy+for+TSO+SSR+files)
- [JWSTKD-124](https://jira.stsci.edu/browse/JWSTKD-124)
- [JWSTKD-125](https://jira.stsci.edu/browse/JWSTKD-125)
- [JSDP-332](https://jira.stsci.edu/browse/JSDP-332)

# Issues
- A number of TSO modes also have target acqs. If Level3 combines all chunks, then no issue. However, if there are any Level3 that still have chunks, remember to ensure that target acq's are placed in all of them.

# Implementation
- [x] Target acqs resolved by #1692
- [x] TSO associations resolved by #1425

**Comment by stscieisenhamer** [comment]
Resolved by #1692 and #1425

**Comment by hbushouse** [comment]
Has this been tested using any of the example segmented level-1b TSO files from SDP, or does it also need example asn pools (containing entries for each of the segmented exposure products) in order to test?

**Comment by stscieisenhamer** [comment]
Ooops. may have closed too soon. Current codebase is complete and tested with what was designed. However, re-open if this issue will be used to test against actual SDP implementation.

**Comment by hbushouse** [comment]
If you think the coding work is complete, based on our current knowledge of the specs, then closing is fine. If testing (when realistic data become available) reveals issues, then we'll open a new issue in the future to make fixes.

**Comment by hbushouse** [comment]
Do the TSO additions in #1425 allow for a mixture of multiple exposures, each one of which can be segmented, within both the level-2b and level-3 ASN's that are created? E.g. a list of members like:
```
exposure_1-seg001
exposure_1-seg002
exposure_1-seg00n
exposure_2-seg001
exposure_2-seg002
```
just to be as flexible as possible, in case a given observation of a given target happens to be split into multiple exposures?

**Comment by stscieisenhamer** [comment]
Regarding multiple exposures: I've just checked rules and there are no constraints on actual exposure number, so if an observation/tso candidate had multiple exposures, they would all be grouped together.
