### ISSUE TITLE
In extract_1d, ignore NaNs when converting 2-D wavelength array to 1-D

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1562]
The wavelength array (WAVELENGTH extension) is 2-D, but `extract_1d` needs a 1-D array of wavelengths.  Currently, the middle line (or average of the two middle lines) of the extraction region is used, but the actual spectrum is not necessarily centered in the extraction region.  Values in the wavelength array that are not close to the spectrum can be NaN or negative, resulting in incorrect wavelengths in the output spectrum.

**Comment by hbushouse** [comment]
Fixed by #1563.
