### ISSUE TITLE
Ramp Fitting with only two groups in semi-ramp

### ISSUE THREAD

**Issue by mwregan2** [STScI-JWST/jwst#1582]
While testing jump detection, I found that in a 100 group integration all the CRs found in the 3rd and 98th group yielded widely varying slopes. These CRs in these two groups cause the formation of a 2-group semi-ramp. Given that the slope and uncertainty have to be calculated differently for a 2-group semi-ramp, it's clear that something is not working correctly in this case.

**Comment by dmggh** [comment]
Hi Mike,


There have been semi-recent updates to that part of the ramp fitting code. Please copy your jump step output to somewhere accessible and I will take a look.


Thanks,

Dave Grumm

________________________________

**Comment by mwregan2** [comment]
Dave,
    I’ve attached the code. I added some print statements to help me understand what it is doing. I just pulled the latest version from Github on Thursday.
  Karl and I have been talking about what we think is the correct way to weight the semi-ramps. We should all probably talk about it.
Mike

**Comment by dmggh** [comment]
Mike,


Hmm, I don't see an attachment.  Anyway, if you can copy your ramp fit input (jump output) to central storage I will take a look at it.


-Dave

________________________________

**Comment by mwregan2** [comment]
Dave,
  I put it in /grp/jwst/wit/odl/jump_output.fits
Mike
Ps There must be something with the github reply system that prevents attachements.

**Comment by dmggh** [comment]
Mike,


Ok, thanks. Are there particular pixels that you have noticed this problem ?


-Dave

________________________________

**Comment by mwregan2** [comment]
Dave,
  Look at any pixel with a cr flagged in group 3 (index =2). They all get slopes that are either very high or very low. The inherent slope is zero but there is read noise. So, the slopes are not exactly zero.
Mike

**Comment by mwregan2** [comment]
Dave,
  The problem is that the two-group semi-ramp has the wrong weight applied. So, when it is combined with the longer data is dominates. The two group semi-ramp is using the MIN_ERR value which 1e-10. The standard deviation of the error is sqrt(2)* read_noise. The Variance is this squared. So, starting at line 1714 inside of fit_double_read change 
From
variance_s[ pixel_ff ] = MIN_ERR
sig_slope_s[ pixel_ff ] = MIN_ERR
sig_intercept_s[ pixel_ff ] = MIN_ERR

to
variance_s[ pixel_ff ] =  2.0 * rn_sect.flatten()[pixel_ff] * rn_sect.flatten()[pixel_ff]
sig_slope_s[pixel_ff] = np.sqrt(2) * rn_sect.flatten()[pixel_ff]
sig_intercept_s[ pixel_ff ] = np.sqrt(2) * rn_sect.flatten()[pixel_ff]

When I make the change the slope images now show no obvious outlier values.

Should I do a pull request?

Mike

**Comment by dmggh** [comment]
Hi Mike,


Thanks for pointing this out. Yes, I had also noticed that the incorrect weight was being applied for these short semi-ramps. ( Some (now obsolete routines) were being called that I had put in there earlier to handle special cases.) I am making some related changes to the code, so I will put in a pull request.


Thanks,

Dave

________________________________

**Comment by karllark** [comment]
Great to see this problem being fixed!

**Comment by hbushouse** [comment]
Regarding the use of readnoise in all of these calculations, we should confirm how the readnoise is being calculated (and delivered in ref files) by the teams, in terms of whether it's the readnoise on a single readout or the noise in a CDS pair of reads, and which way it's expected to be used in these calculations. We have specified CDS readnoise in the reference file docs, because that's the way it's always been used/needed in past IR pipelines, where we're always dealing with samples (groups) that've been zero-read subtracted.

**Comment by mwregan2** [comment]
Howard,
  That’s an excellent point. I’ve been wondering about this too. For general fitting it should be single sample and not CDS. We should poll the teams and do some work on which value should be used where.
Mike

**Comment by hbushouse** [comment]
Fixed by #1596
