### ISSUE TITLE
Negative number of filled traps in persistence

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1599]
Kevin Volk pointed out that this expression

    exp_filled_traps = incoming_filled_traps - trap_density * par2

in `predict_saturation_capture` would give a negative value for `exp_filled_traps` if `incoming_filled_traps` (an input parameter) was zero, which it could be for pixels that happened to not be exposed to any light.  This function only pertains to ramps which contain at least some saturated groups, however, so the pixels must be illuminated.  I suspect there needs to be a mask to exclude pixels for which there are no saturated groups.

**Comment by hbushouse** [comment]
Fixed by #1693.
