### ISSUE TITLE
Task: Update NIRSpec fixed-slit subarray names to match PPS DB

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1613]
The cal pipeline data models and CRDS reference files currently assume the following subarray values associated with NIRSpec fixed-slit readouts:

ALLSLITS, S200A1, S200A2, S200B1, S400A1, and SUB2048 (the latter is for the S1600A1 slit)

while PPS has a constraint to use the names:

ALLSLITS, SUBS200A1, SUBS200A2, SUBS200B1, SUBS400A1, and SUB2048 (edited)

(see http://www-int.stsci.edu/dsd/cns/database/r2d2/PPSDB79/nirspec_exposure_specification.html)

The core schema needs to be updated to allow for the SUBxxxxx versions of the subarray names, and check for any uses of these names in the actual cal code. This discrepancy was discovered during the last stages of B7.1 subsystem testing, hence the fix was left to B7.1.x.

**Comment by nden** [comment]
`assign_wcs` and `extract_2d` need to be changed as well.
