### ISSUE TITLE
Level 3 processing doesn't pay attention to strun --output_dir param

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#162]
Mike Swam reports that when he tried to run wfs_combine level-3 processing using strun and specified the optional --output_dir param to designate a particular output directory in which to place the output product, the output product was still created in the working directory.

I'm guessing this is due to the fact that with level-3 processing, via any task like wfs_combine or calwebb_image3, it's the task/pipeline module itself that's saving the output file, using the name specified in the input ASN table, and is ignoring anything specified via the --output_dir param on the command line. With level-2 processing tasks/pipelines, the output product model is passed back up to stpipe to let it handle the creation of the output file and in that case stpipe does pay attention to any --output_dir that was specified.

Level-3 tasks and pipeline modules, such as wfs_combine, calwebb_image3, calwebb_spec3, etc. should be upgraded to use the output_dir path specified on the strun command line.

**Comment by stscieisenhamer** [comment]
Just as an example of use with the association product names:
```
with open('the_association', 'r') as asn_fh:
    asn = Association.load(asn_fh)
my_result_model = code_returning_some_jwst_datamodels_result_model(asn)
output_dir = '/the/output/directory/path/from--output_dir'
product_type = 'i2d' # Assuming CALIMAGE3
product_name = asn['products'][0]['name']
full_output_path = output_dir + '/' + product_name.format(product_type=product_type)
my_result_model.save(full_output_path)
```

**Comment by hbushouse** [comment]
Regarding line 4 in the above example, if the user specifies the --output_dir param to strun, it will show up as an attribute of the pipeline or step that's being run, as self.output_dir. Hence pipeline modules can check for "self.output_dir is not None" and if so, then be sure to prepend the value of self.output_dir to the output file name.

**Comment by hbushouse** [comment]
Oh, and instead of using the direct approach of appending the path and filename just by using the "+" operator, it might be safer and more OS-benign to use the os.path.join function to do that, i.e. full_output_path = os.path.join(output_dir, product_name).
