### ISSUE TITLE
Task: Update extract_1d to store TSO time stamps in table headers

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1620]
The extract_1d step should be updated to store time stamps related to each integration in the header of the table extension containing the extracted 1D data for that integration. The time stamps will come from the expanded table of time stamps that SDP will create in the level-1b products of TSO exposures (see #1617). Names for the extension header keywords are TBD.

**Comment by hbushouse** [comment]
This is high priority for B7.2, because it is needed to fulfill level 4 requirements DMS-785 and DMS-786.

**Comment by hbushouse** [comment]
The new integration times table extension format and contents is described in https://jira.stsci.edu/browse/JSDP-387

**Comment by philhodge** [comment]
Closed by PR #2171.
