### ISSUE TITLE
Task: Update the white_light step to use TSO time stamps from table

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1621]
Update the white_light step to read the time stamps for each integration from the table extension that will be provided by SDP in TSO exposures (#1617), rather than computing them. Analogous to the updates to the tso_photometry step (#1619).

**Comment by hbushouse** [comment]
This issue is high priority for B7.2, because it is needed to fulfill level 4 requirements DMS-785 and DMS-786.

**Comment by hbushouse** [comment]
The new integration times table extension format and contents is described in https://jira.stsci.edu/browse/JSDP-387

**Comment by philhodge** [comment]
Fixed by PR #2171.
