### ISSUE TITLE
Task: extract_1d updates for NIRISS SOSS

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1626]
The extract_1d step should be updated to perform its extraction by following the spectral trace that has been determined by the NIRISS team, e.g. via the specification of a polynomial that defines the aperture location as a function of wavelength. It should also be updated to extract all spectral orders that are present in a given exposure.

**Comment by philhodge** [comment]
Should the extraction aperture be parallel to an image axis?  One could imaging that the extraction aperture would be perpendicular to the spectral trace, or some other angle that could vary with wavelength.
