### ISSUE TITLE
Check the DQ extension of persistence reference files

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1635]
The ramp slope is needed for computing the capture of charge by traps, and the slope is in units of a fraction of the persistence saturation limit per second.  The persistence saturation limit (persat) reference file may contain invalid values (e.g. zero), so the persistence step should check the DQ extension of the persistence saturation limit file; the ramp slope should be set to zero for pixels that are flagged as bad in this reference file.

The trap density reference file is also used for computing charge capture, but since this is used as a factor, pixels in the trap density data that are flagged as bad can just be set to zero.

**Comment by hbushouse** [comment]
Fixed by #1696.
