### ISSUE TITLE
Blendheaders causing schema validation error

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1650]
Alicia Canipe reports, in basecamp message https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/104426490/comments, that the calwebb_image3 pipeline is failing in the resample step due to schema validation errors on the input data to the step. The schema validation error is:

ValidationError: In V54321001002P0000000001101_A1_F150W_a3001_crf.fits 'MULTIPLE' is not of type 'integer'
Failed validating 'type' in schema['properties']['position_number']:
    OrderedDict([('title', 'Position number in primary pattern'),
                 ('type', 'integer'),
                 ('fits_keyword', 'PATT_NUM')])
On instance['position_number']:
    'MULTIPLE'

This is obviously due to blendheaders resetting the value of the PATT_NUM keyword to 'MULTIPLE', because the input exposures do in fact have multiple values of that keyword. Schema validation fails because the keyword value is now a string, instead of an integer.

Need to rework the blendheaders handling of these types of cases so that it doesn't change the data type of keywords or use values that aren't allowed by the schema.

**Comment by stsci-hack** [comment]
Fundamentally, the user/instrument team can define the output value to be determined using any of the supported functions for blendheaders; namely, first, last, multiple, and so on.  As a result, the software assumes that the user knows what they are doing and with FITS it did not matter what form the output value took.  Therefore, the FITS-based version of blendheaders will never be able to prevent such problems (which have occasionally affected HST data as well).  

Instead, schema-based validation of output values and/or a tool for developing schema-valid rules will be developed as part of the new model_blender package to implement blending directly on models.  
This ticket will, in the meantime, support that part of the implementation.

**Comment by hbushouse** [comment]
Fixed by #1689 and #1690.
