### ISSUE TITLE
Limit reference prefetch to Pipeline level,  remove CRDS header caching

### ISSUE THREAD

**Issue by jaytmiller** [STScI-JWST/jwst#1661]
Data models header caching was added to the crds_client module to optimize data model header reads for more complex pipeline cases with heavy file loads,  avoiding multiple dataset reads by caching parameters keyed using the model filename.

Nadia directly encountered the limitation of that approach,  the header for a particular filename is only read once so it cannot change easily during interactive sessions,  particularly for people unaware of the optimization.  Nadia debugged it,  most may not.   So I now believe CRDS header caching is too dangerous,  it will give incorrect results to some users doing (interactive) work.

Jonathan had a better design shift for optimizing the prefetch.  Noticing that the calls to get_reference_file() always immediately follow the prefetch within individual Step functions,  he suggested moving the Step version of the prefetch entirely to the Pipeline level where it is most applicable and also most efficient. 

A minor(?) downside with my implementation is that Steps no longer prefetch,  only the Pipeline.  Because Steps no longer prefetch,  single Step runs will not detect all reference file errors at the outset,  only type-by-type as the Step runs and calls get_reference_file().    Pipelines will still have the property that all reference availability errors and caching for the pipeline are detected before Steps start running.

**Comment by hbushouse** [comment]
Fixed by #1662
