### ISSUE TITLE
Incorrect calculation of the median 1st difference is twopointdifference.py

### ISSUE THREAD

**Issue by mwregan2** [STScI-JWST/jwst#1668]
When calculating the median 1st difference twopointdifference.py uses the absolute value of the 1st differences. This is incorrect because it leads to a positive bias in the low to zero flux case. When the flux is zero the median 1st difference should be zero. Instead it's around 1 sigma. This leads to false detection of jumps.
  I have coded the fix and tested it. I'll be submitting a pull request.

**Comment by hbushouse** [comment]
Fixed by #1670.
