### ISSUE TITLE
SUBARRAY is not being used as a constraint

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1671]
# Issue
First noticed for MIRI LRS modes: The only parameter that distinguishes fixed-slit vs. slitless LRS modes is the subarray in use. Currently associations generated do not append the subarray to the Level3 product name, causing a name conflict.

In general, `SUBARRAY` is not being used as a constraint, which will cause exposures of the same optical path, but of different subarray's, to be mistakenly associated together.

# Resources
- [Level3 file naming](https://confluence.stsci.edu/display/jwstdms/JWST+DMS+Associations+De-Scope+Design+Overview#JWSTDMSAssociationsDe-ScopeDesignOverview-AssociationLevel3&3.5FileNames)
- Value sets
    - miri
        - image: full, brightsky, sub256, sub128, sub64
        - lrs: full, slitlessprism
        - mrs: full
        - coron: full
    - nrc
        - image: full
            - module b: full, sub640, sub320, sub160, sub400p, sub160p, sub64p
        - coron: full, sub640
        - tso: full, sub400p, sub160p, sub64p
        - grism tso: full, subgrism256, subgrism128, subgrism64
        - wfs: full
    - nrs
        - fss: full, allslits
        - ifu: full
        - mos: full
        - bots: sub2048, sub1024a, sub1024b, sub512, sub512s
    - nis
        - image: full, sub256, sub128, sub64
        - wfss: full
        - soss: full, substrip256, substrip96
        - ami: full, sub80

# Implementation
- [x] bump version
- [x] tests
- [x] remove/rename subarray from other rules if not needed.
- [x] collapsing spectral associations
    - [x] add subarray as a default constraint
    - [x] Non-IFU spectral: `Asn_Spectral`
    - [x] IFU spectral: `Asn_IFU`
    - [x] Happenstance resolves #1441, #1643
    - [x] Combine the TSO associations using the new `or` functionality. And, why the tso exp_types are forcing the flag to not be defined?  Test is `pool_021` and `pool_022`. For some reason the tso have completely disappeared. _handled in #1745_
- [x] PR #1746 for the above changes.
- [x] determine how the name convention should work
    - Simple option, option 1 from below, will be implemented.
- [x] implement name convention
- [x] refactor the other `_get` string representations to not raise exceptions but return empty.
- [x] tests
- [x] bump version

**Comment by hbushouse** [comment]
I believe the source-based file name syntax rules do allow for the inclusion of subarray name as a field, we apparently just haven't made use of it yet. This is a really unfortunate situation with the MIRI LRS.  They really should have a separate observation template or something like that, to distinguish the fixed-slit from slitless mode. Of course that still wouldn't prevent file name conflicts.

**Comment by stscieisenhamer** [comment]
# Question

Question on a couple of options for file naming:

1. Simple option: Value of `FULL` will not be placed in the file name. Any other value will be placed in the file name.

2. Mode-specific: If subarray is not relevant to a particular mode, the subarray field will be blank. Otherwise, all values relevant to that mode, including `FULL`, will be placed in the filename.

Any preferences or should this go to the association group?

**Comment by hbushouse** [comment]
I agree with not having `FULL` appear and also with the inclusion of `SLITLESSPRISM` for LRS slitless. But not sure why you'd want/need to include subarray at all for NRC module B?

**Comment by stscieisenhamer** [comment]
Did an email response, but don't see it in the comments here, so, just in case:

The reason NRC Module B is called out separately, is that, according to APT, if one selects just Module B, the full set of NRC subarrays becomes available for selection.

**Comment by stscieisenhamer** [comment]
@hbushouse Back to the naming. Your previous response is unclear. Were you advocating for the "simple option", #1, or for option #2?

**Comment by hbushouse** [comment]
Both? I don't like having `FULL` every appear in a file name, while I think having a (non-FULL) subarray name appear when it's relevant is OK. So I would be in favor of a reworked option 2:

Mode-specific: If subarray is not relevant to a particular mode, the subarray field will be blank. Otherwise, all values relevant to that mode, _except for_ FULL, will be placed in the filename.

Special cases:

   lrs vs. lrs slitless: field will be blank for lrs, but SLITLESSPRISM for slitless.
   nrc imaging: If both modules are used, field will be blank. If only module b, then the field will be filled with whatever the value is, _except for_ FULL.

**Comment by hbushouse** [comment]
My remaining question about this option is who and how do we determine whether a subarray is "relevant" to a mode?

**Comment by stscieisenhamer** [comment]
In reality, this is option 1: If one removes `FULL` from the list, then anytime something other than `FULL` appears, it will end up in the name.

Option 2 would have required defining a list of modes where `SUBARRAY` can be selected. The reason for this was to also put `FULL` in those names, because it had to have been chosen and is part of the list.  Clearly a bit fragile but would have made clear in the naming that subarray could have been changed and it was chosen to be `FULL`.

With regard to the MIRI LRS modes, I believe subarray of `FULL` corresponds to the slit mode, so again, nothing would have to be done. Will confirm that.

So, the simpler approach will be taken.

**Comment by hbushouse** [comment]
Yes, MIRI LRS slit mode is always FULL. It's only distinguishing feature from MIRI imaging is FILTER='P750L'. The only distinguishing feature between LRS slit and slitless is SUBARRAY='SLITLESSPRISM' for the slitless mode.
