### ISSUE TITLE
Bugs in refpix step median calculation

### ISSUE THREAD

**Issue by stscirij** [STScI-JWST/jwst#1678]
As reported by Bryan Hilbert in basecamp:

https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/104497164/comments

The median filter has two bugs: an indexing error in the create_reflected function and use of the wrong dq array in the median (should be augmented_dq instead of dq).

**Comment by hbushouse** [comment]
Has everything in the original issue been fixed by the changes in #1679? If so, then this can be closed.

**Comment by stscirij** [comment]
Yes, everything was fixed in #1679
