### ISSUE TITLE
Incorrect Readnoise is being used in ramp_fit

### ISSUE THREAD

**Issue by mwregan2** [STScI-JWST/jwst#1683]
There are two problems with the way ramp_fit routine is using readnoise from the reference file. First, the readnoise in the reference file is the CDS readnoise (I think). Overall, when fitting nframes=1 groups, we need to use the single sample read noise. This is the CDS value divided by the sqrt(2).
Second, the readnoise per group is then reduced by the sqrt(nframes). For example, with NIRCAM DEEP8 the readnoise is reduced by the sqrt(8). 
This leads to different S/N calculations. So, the optimum weights will be different and the final uncertainties in the slope values will change.

**Comment by hbushouse** [comment]
You're right that the readnoise ref files are expected to contain the CDS readnoise (noise in the difference between two frames), but whether that's what the teams have actually delivered is a separate question that should be answered.

**Comment by hbushouse** [comment]
This may also affect the jump step, because the readnoise reference data is used there too.

**Comment by mwregan2** [comment]
Howard,
  Yes, the question of which type of readnoise is in the ref file does affect the jump detection. Jump detection does scale the read noise by the number of frames per group.
Mike

**Comment by mwregan2** [comment]
The CDS readnoise in electrons is the correct version of read noise to use in jump detection. The readnoise is compared to the first differences. First differences are CDSs. So, this problem does not affect the jump detection step.

**Comment by hbushouse** [comment]
Fixed by #1925
