### ISSUE TITLE
Incorrect calculation of the variance of the slope due to Poisson Noise

### ISSUE THREAD

**Issue by mwregan2** [STScI-JWST/jwst#1686]
In ramp_fit.calc_opt_fit the variance of the slope due to Poisson noise is calculated as:
` 
 sig_slope_p = slope/(mask_2d.sum(axis=0) - 1.)
`
Since at this point in the code the slope is in units of DN/frame. The output of this is in units of DN. The actual variance in DN requires the use of the gain in units of e-/DN. If we express the variance in DN, then we need to divide the right hand side of the equation by the gain.

  Also, the variable name should be changed to match what it is. It should be:
`variance_slope_poisson`
It is not a measurement of the standard deviation. It is the variance.

**Comment by hbushouse** [comment]
INS tracking in https://jira.stsci.edu/browse/JP-236

**Comment by hbushouse** [comment]
Fixed by #1925
