### ISSUE TITLE
Incorrect Slope Combination in Ramp Fitting

### ISSUE THREAD

**Issue by mwregan2** [STScI-JWST/jwst#1687]
In ramp fitting when slopes are averaged either between segments or between integrations. The total variance is used. This variance is the sum of the Poisson and what is referred to as the read noise variance. This is incorrect and leads to a bias in the combined slope. This is because including the Poisson noise is wrong. When multiple slopes are averaged the Poisson noise will always be less for smaller slopes. Thus, the average is biased low. I have first hand experience with this since I made the same mistake in the NICMOS pipeline. Reporting this total variance as the uncertainty of the fit also has serious negative consequences for any image combination steps that follow.
Also, what is referred to in the code as "sig_slope_r" is not well named. This is the estimated variance of the fitted slope. It includes components from both read noise and Poisson noise. This is the value that is used in the HST pipelines to weight the segments. It does have the problem that it is poorly determined when the number of samples in the fit is small. Even so, for now it is the best value to use for weighting slopes when calculating their weighted mean. Karl Gordon and I are discussing a better estimate of the slope variance that we could use in the future.

**Comment by hbushouse** [comment]
Fixed by #1925
