### ISSUE TITLE
The guider pipeline may need to accept 3-D input

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1704]
The input to `GuiderPipeline` is normally a 4-D array, an uncalibrated ramp image.  Shannon Osborne tried running this with the first two steps set to be skipped, correctly passing a 3-D slope image as input, in order to run the third step, flat_field.  The pipeline failed because currently the input file is explicitly opened as a `GuiderRawModel`, which must be 4-D.  The guider pipeline should be modified to accept a 3-D slope image if the first two steps are to be skipped.

**Comment by hbushouse** [comment]
See https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/104610817/comments for the original reporting of the problem.

INS is tracking in https://jira.stsci.edu/browse/JP-212

**Comment by hbushouse** [comment]
Fixed by #1821
