### ISSUE TITLE
MultiSlit processing efficiency

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1730]
It's been known for a long time already that parts of the calwebb_spec2 pipeline are very slow when processing something like a NIRSpec MSA exposure that has many sources/slits defined. This became abundantly clear near the end of B7.1 development when testing of the new routines in the extract_2d step to handle WFSS (grism) exposures took tens of hours to process a few extracted slits. Initially the extract_1d step was also very slow with grism data, but the change included in #1469 seems to have fixed that.

Improving the speed of the remaining steps (especially extract_2d) will likely require a change to the way wcs transforms are handled and/or a change to the way datamodel schema validation is done, because it's been known that much of the overhead is due to revalidating the datamodel every time a new slit instance is added to the output model created by extract_2d.

Some work has already taken place towards solving this problem (e.g. #1070 and #1700). This issue simply serves as an official tracking mechanism for the work being done to solve the larger problem.

**Comment by hbushouse** [comment]
INS tracking in https://jira.stsci.edu/browse/JP-234

**Comment by nden** [comment]
This has been resolved mostly in #1070 but also in follow-up PRs - #1734, #1712, #1709, #1707, #1700

**Comment by nden** [comment]
Regression tests passed, I think this can be closed now.
