### ISSUE TITLE
refactor TSO rules into one rule

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1745]
# Issue
There are currently multiple rules for handling the various TSO observation modes. With #1692 which implemented an update constraint system, these rules can be more concisely defined as one rule.

# Implementation
- [x] bump version
- [x] documentation
- [x] tests
- [x] code
    - [x] Remove `TSO_EXP_TYPES` from `rules_level3_base`.
    - [x] Add new attribute `matched` to `Constraint` to indicated what the last match was.
    - [x] Refactor `rules_level3_base.Constraint_NotTSO` to check for both the `tsovisit` flag and `exp_type`.
    - [x] Combine `Asn_TSO_Flag` and `Asn_TSO_EXPTYPE` into a single rule.
    - [x] Update `constraint` module docstrings for what is returned. No longer `Constraint` but `bool`.
- [x] tests
- [x] documentation
- [x] bump version

**Comment by hbushouse** [comment]
You don't envision implementing this for B7.2? Or is the current setup producing the correct results, but just in an inefficient way, hence it's not vital for B7.2?

**Comment by stscieisenhamer** [comment]
The current rule set produces correct associations. This is more of a behind-the-scenes refactor. Personally, always plan on getting things done asap; there is the usual OCD to contend with. But, for playing nice with the rest of the project, am trying to be accurate in needs and priorities. There are bugs to fry first.

**Comment by hbushouse** [comment]
Mmmmm, fried bugs ...
