### ISSUE TITLE
Update outlier detection noise model

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1759]
The outlier_detection step currently uses information from readnoise and gain reference files to compute a noise model for the science data, which is in turn used when finding outliers. Because the ramp_fit step is being updated to compute and pass along more realistic noise/error/uncertainty values in the standard ERR array, the outlier_detection step can be updated to simply make use of that ERR data, rather than recomputing a noise model from scratch. This also yields a big increase in efficiency by not having to fetch and load lots of reference files.

**Comment by stsci-hack** [comment]
The work done in #1758 (based on new ERR array computations implemented in other PRs) should resolve this issue, while it remains subject to further testing and evaluation by INS.
