### ISSUE TITLE
FGS guide star data WCS computation for level-1b

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1765]
# Issue
SDP has asked for our support in providing the algorithms necessary for computing basic WCS info and populating FITS WCS header keywords for level-1b FGS guide star products, similar to the algorithms we provided in the set_telescope_pointing script for application to science exposures.

This is a high-priority task for DMS Build 7.2, in order to satisfy level 4 requirements DMS-189 and DMS-692.

# Resources
- SDP either is already or will be populating the following keywords, based on sources like the SIAF, OSF, and PPSDB:

    - CRPIX1/2
    - CRVAL1/2
    - CDELT1/2 (from SIAF)
    - V2_REF, V3_REF, VPARITY, V3I_YANG (from SIAF)
    - RA_V1, DEC_V1, PA_V3 (from OSF)

# Implementation
- [x] bump version
- [x] tests
- [ ] SCSB code, presumably in a new branch of the set_telescope_pointing script, will compute and populated the PC matrix keywords, based on PA_V3 and VPARITY.
- [ ] The keywords RA_REF, DEC_REF, and ROLL_REF will not appear in guide star product headers.
- [ ] tests
- [ ] bump version

**Comment by hbushouse** [comment]
Recent communication from Ed Nelan, giving his take on where to get info to populate basic FITS WCS keywords in the guide star products:

"I think that for the FGS data sets the RA,Dec and commanded PA of the guide star actually used in the visit will be sufficient for the WCS values. These quantities are best obtained from the Observatory Status file (contains OSS data) polling for the guide star “order number” (which is the candidate GS that was actually used) and the <V3_PA> , which are values listed in table 6-8 of the S&OC Subsystems IRCD, in combination with the PPS data base to get the cataloged RA,Dec of the guide star, as outlined in Daryl’s report (sections 4.2 and 4.3).  I don’t think we need to get sophisticated to the point of using quaternions based upon actual pointing telemetry."

**Comment by hbushouse** [comment]
The latest FGS guide star calibration design document ("Daryl's report") is available on the confluence page at:
https://confluence.stsci.edu/display/jwstdms/JWST+DMS+Guide+Star+Data+Products+and+Processing

**Comment by hbushouse** [comment]
Table 10 in section 5.3.4 of the design doc indicates the following sources for some of the standard WCS keywords:
```
WCSAXES | Number of World Coordinate System axes | Default value = ‘2’
CRPIX1 | Guide star x position on the detector in the ideal   coordinate frame | Guide star x position on the detector (see above)
CRPIX2 | Guide star y position on the detector in the ideal   coordinate frame | Guide star y position on the detector (see above)
CRVAL1 | RA of the guide star (degrees) | PPSDB:   candidate_guide_star: ra
CRVAL2 | Dec of the guide star (degrees) | PPSDB:   candidate_guide_star: dec
CUNIT1 | Units of CRVAL1 | Default value = ‘degrees’
CUNIT2 | Units of CRVAL2 | Default value = ‘degrees’
CTYPE1 | First axis coordinate type | Default value = ‘RA---TAN’
CTYPE2 | Second axis coordinate type | Default value = ‘DEC--TAN’
CDELT1 | Increment per pixel, increasing eastward (degrees) | Read from SIAF for guider in use
CDELT2 | Increment per pixel, increasing northward (degrees) | Read from SIAF for guider in use
PC1_1 | Linear transformation matrix element | cos(theta)
PC1_2 | Linear transformation matrix element | -sin(theta)
PC2_1 | Linear transformation matrix element | sin(theta)
PC2_2 | Linear transformation matrix element | cos(theta)
```

**Comment by hbushouse** [comment]
The information above begs the following questions:

1. If there aren't any entries in the SIAF for the FGS apertures used for guiding modes, should we then use the SIAF info for the "standard" FGS apertures like `FGS1_FULL` and `FGS2_FULL` to get `XSciScale` and `YSciScale` values with which to populate `CDELT1` and `CDELT2`?

2. What is the value of `theta` that we use to compute the `PCi_j` values? Is it the `V3_PA` value mentioned by Ed?

3. What do we do with all the other additional WCS-related keywords that we normally populate for science products, such as RA_V1, DEC_V1, RA_REF, DEC_REF, ROLL_REF, V2_REF, V3_REF, VPARITY, V3I_YANG, etc.? Leave them out of guide star product headers, because they aren't needed for anything downstream anyway (we never do anything with the WCS object)?

**Comment by hbushouse** [comment]
Discussion from a meeting of the minds on 23-March-2018 resulted in the following info and decisions.

1. SDP either is already or will be populating the following keywords, based on sources like the SIAF, OSF, and PPSDB:
 - CRPIX1/2
 - CRVAL1/2
 - CDELT1/2  (from SIAF)
 - V2_REF, V3_REF, VPARITY, V3I_YANG  (from SIAF)
 - RA_V1, DEC_V1, PA_V3  (from OSF)

2. SCSB code, presumably in a new branch of the set_telescope_pointing script, will compute and populated the PC matrix keywords, based on PA_V3 and VPARITY.

3. The keywords RA_REF, DEC_REF, and ROLL_REF will not appear in guide star product headers.

**Comment by stscieisenhamer** [comment]
# Question
Does this get applied to every guiding mode?

**Comment by stscieisenhamer** [comment]
# Question
Any particular `DataModel` for FGS Level1b?

**Comment by stscieisenhamer** [comment]
#Question 
Is there any corresponding JIRA ticket for this?

**Comment by hbushouse** [comment]
No corresponding JIRA ticket.
