### ISSUE TITLE
Resample step fails with too many inputs

### ISSUE THREAD

**Issue by stsci-hack** [STScI-JWST/jwst#1770]
Testing by INS has uncovered a problem with too many inputs causing the resample step to fail when trying to expand the output context image.  

The full traceback provided ended with:

/user/acanipe/miniconda3/envs/jwstdevfeb262018/lib/python3.6/site-packages/jwst-0.9.2a0.dev26-py3.6-linux-x86_64.egg/jwst/resample/gwcs_drizzle.py in add_image(self, insci, inwcs, inwht, xmin, xmax, ymin, ymax, pscale_ratio, expin, in_units, wt_scl)
    210
    211         wt_scl = 1.0  # hard-coded for JWST count-rate data
--> 212         self.increment_id()
    213
    214         dodrizzle(insci, inwcs, inwht, self.outwcs,
/user/acanipe/miniconda3/envs/jwstdevfeb262018/lib/python3.6/site-packages/jwst-0.9.2a0.dev26-py3.6-linux-x86_64.egg/jwst/resample/gwcs_drizzle.py in increment_id(self)
    269         if self.outcon.shape[0] == planeid:
    270             plane = np.zeros_like(self.outcon[0])
--> 271             self.outcon = np.append(self.outcon, plane, axis=0)
    272
    273         # Increment the id
/user/acanipe/miniconda3/envs/jwstdevfeb262018/lib/python3.6/site-packages/numpy/lib/function_base.py in append(arr, values, axis)
   5164         values = ravel(values)
   5165         axis = arr.ndim-1
-> 5166     return concatenate((arr, values), axis=axis)
ValueError: all the input arrays must have same number of dimensions

**Comment by hbushouse** [comment]
Original report and conversation is in https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/104856118/comments

**Comment by stsci-hack** [comment]
Nightly regression tests pass.   The basecamp issue has been updated to reference the closed PR.  Closing this issue...
