### ISSUE TITLE
Checking of FITS Headers for necessary keywords

### ISSUE THREAD

**Issue by stscicrawford** [STScI-JWST/jwst#1780]
Instrument teams need to know what header keywords they need to run the calibration pipeline starting at any stage (1,2, or 3) [ level 1b, level 2a, level 2b, level 3 ].   Instrument teams need an efficient way to check data 

The DMS-WG are requesting a python tool that:

1) Makes a header by instrument, mode, and level, and returns a sample header with keywords and sample values (and range = enum if possible).

e.g. make_header.py miri imaging level2a

2) Add a link to the keyword database such that the instrument teams can find information about valid values, format, source, etc.

Due to the usage during testing, this is a high priority item for the DMS-WG.

**Comment by stscicrawford** [comment]
Tracked as https://jira.stsci.edu/browse/JP-247

**Comment by hbushouse** [comment]
There's a seemingly identical request for such a tool that was filed as a JWST Keyword Dictionary ticket a couple months ago: https://jira.stsci.edu/browse/JWSTKD-146

**Comment by stscicrawford** [comment]
@bernie-simon please take a look at the issue and the attached ticket.  Let me or Howard know if you have any questions.    

To me, the difficult part of this is knowing what keywords are required for the pipeline to run successfully.  I can think of several different ways to do this, but it would be good to think about the best way to do it.

**Comment by bernie-simon** [comment]
I have addressed these issues in #1899

**Comment by stscicrawford** [comment]
Thanks @bernie-simon -- I think you meant #1889 but also just also linking the issue #1876 which it looks like you have addressed as well.

**Comment by stscicrawford** [comment]
Closing again due to the updates in #2048 and #2078
