### ISSUE TITLE
Nirspec WCS input coordinates are 1-based

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#1781]
**This has been resolved in one place now - `assign_wcs.nirspec.detector_to_gwa` - #1834 .
I suggest we keep the issue open until a permanent decision on how to proceed is made.**

Unlike the rest of the instruments the Nirspec WCS model expects 1-based inputs. The following steps need to provide 1-based inputs when calling the WCS object:

[X] extract_2d
[X] flatfield
[ ] msaflagging
[X] extract_1d
[ ] barshadow
[ ] pathloss
[ ] resample
[ ] cube_build

**Note**: When the wavelength array is available (all modes that run through extract_2d) it should be used, because it contains the wavelength zero-point correction (computed and applied in extract_2d).

**Comment by hbushouse** [comment]
Flat_field fixed by #1792.

**Comment by philhodge** [comment]
extract_1d fixed by #1796.

**Comment by stscicrawford** [comment]
Closed by #1834
