### ISSUE TITLE
Incorrect values from a data model

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#179]
Under some circumstances, a model in datamodels can return incorrect values for data in a FITS BINTABLE.  I was using a data model in which the column names of a table were specified as lower case, but the actual table that I was reading had the names in upper case.  I was using Python 2.7.12.  The datamodels code did not give any warning or error message when I referenced the values in a column by giving the name in lower case, but the data values returned by the model were all zero.  For a text string column, the values were all blank.

For most cases, the datamodels code gave the same (correct) results regardless of the case of the file names.  The case where I saw the incorrect values with upper-case names was under the following conditions:  (1) a "multi" model, e.g. MultiSpecModel, (2) there was a text-string column, and (3) there was a column that contained arrays.  The MultiSpecModel does not have any text-string columns and the float columns are scalar, so I modified a local copy of the model.  I changed the table definition to three columns:  slit_name, type ascii, maximum 15 characters; wavelength, type float32, shape (2000,); countrate, type float32, shape (2000,).

**Comment by hbushouse** [comment]
Bug in datamodels fixed by @bernie-simon circa Oct. 2016 (see comments in #324).
