### ISSUE TITLE
Document correspondence between github tags and DMS builds

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1794]
Because the pipeline version numbers have started diverging from DMS Build numbers, it would be very useful to users and testers to have documentation on what version of the github repo was included in each DMS build. This could go into a new section of the repo README, which would show up on the front (landing) page.

For reference:

DMS Build 7:  Final release candidate created 13-Dec-2016 (0.7.0rc7) http://ssb.stsci.edu/conda/jwstdp-0.7.0rc/jwstdp-0.7.0rc7-linux-py27.0.txt

DMS Build 7.1: Final release candidate created 13-Nov-2017 (0.7.8rc9) https://github.com/astroconda/astroconda-releases/tree/master/jwstdp/0.7.8

DMS Builds 7.1.1 and 7.1.2: Patch release created 22-Dec-2017 (0.9.0) https://github.com/astroconda/astroconda-releases/tree/master/jwstdp/0.9.0

DMS Build 7.1.x (not yet delivered to I&T): Patch release created 16-Feb-2018 (0.9.1) https://github.com/astroconda/astroconda-releases/tree/master/jwstdp/0.9.1

**Comment by hbushouse** [comment]
Is tag 0.8.0 identical to 0.7.8rc9 (the DMS Build 7.1 release version)? If so, that should also be documented.

**Comment by sosey** [comment]
You can also add this information by editing the annotated tags, so when you make the tag for release add the information about the DMS build etc to it's notes
