### ISSUE TITLE
In extract_1d, truncate arrays where wavelength is NaN

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1803]
The array of wavelengths for a 1-D extracted spectrum sometimes includes NaN values.  Currently, extract_1d replaces NaNs in the wavelength array with 0.01, intended to be a harmless value that is obviously not valid.  However, it isn't really harmless, and it's completely wrong and therefore useless.  If such elements are found at endpoints of the wavelength array, all the arrays for the 1-D extracted spectrum (wavelength, net, flux, background, etc.) should be truncated to eliminate these elements.  If NaNs are found in interior elements of the wavelength array (i.e. not connected via NaNs to an endpoint), such elements should be flagged in the dq array with `DO_NOT_USE`.

**Comment by hbushouse** [comment]
Fixed by #1813.
