### ISSUE TITLE
Use FOREIGN HDU for ASDF-in-FITS

### ISSUE THREAD

**Issue by drdavella** [STScI-JWST/jwst#1807]
Originally ASDF-in-FITS used an `IMAGE` HDU for storing ASDF within a FITS file. However, the archive decided this was not desirable since we're not storing image data in the HDU, and so using this convention may confuse some data readers and end users. We decided to create a custom `ASDF` HDU, and this has been used for several months now (see https://github.com/spacetelescope/asdf/pull/412). However, since `ASDF` is not an approved convention, it turns out that it can't be validated by NASA's `fitsverify`. So we are considering using a `FOREIGN` HDU, since it is a [registered convention](https://fits.gsfc.nasa.gov/registry/foreign.html), and will validate.

Technically this is a change that needs to be supported in ASDF and/or Astropy. However, since it is being motivated by the JWST pipeline, it seems useful to track here.

@stscicrawford and @hbushouse is this how we want to proceed? If so, it won't be supported in an official Astropy release until at least the 3.1 release in ~June. However, this shouldn't matter since I believe the pipeline builds against the latest development version.

**Comment by stscicrawford** [comment]
@drdavella Yes that would be my recommended way to proceed.   Unless anyone else has any objections, having it in the 3.1 release of Astropy would be acceptable.

**Comment by hbushouse** [comment]
You're correct that the jwst pipeline package always builds against the development version of astropy, so we won't be slowed down by waiting for the 3.1 release. And I agree with using the `FOREIGN` label.

**Comment by drdavella** [comment]
As might be expected, it turns out that supporting a special case of the `FOREIGN` HDU in ASDF specifically for ASDF-in-FITS will be easier to implement than full support of the `FOREIGN` convention in Astropy. So at least in the near term, I'm just going to stick this into ASDF itself, and maybe we can revisit an Astropy implementation at a later date.

**Comment by hbushouse** [comment]
👍

**Comment by stscicrawford** [comment]
Sounds good -- thanks @drdavella

**Comment by drdavella** [comment]
I've had the chance to dig into this a little deeper now. It turns out that NASA's `fitsverify` appears to validate HDUs that use `XTENSION= FOREIGN`, but otherwise conform the `IMAGE` standard. However, it does **not** appear to accept true `FOREIGN` HDUs as valid. When I tested this out initially a few weeks ago, I simply took an existing ASDF-in-FITS file and changed `XTENSION= ASDF` to `XTENSION= FOREIGN`, and `fitsverify` seemed to be happy.

When I try to validate a `FOREIGN` HDU that I have crafted to conform to the `FOREIGN` convention, I get errors about invalid values for an `IMAGE` HDU. Even though `XTENSION= FOREIGN`! A quick inspection of the `fitsverify` source code seems to confirm that it does not actually validate the `FOREIGN` convention, although it recognizes `XTENSION= FOREIGN` as valid for an `IMAGE` HDU.

So we're kind of back to square one. If the goal here is simply to satisfy `fitsverify`, then it seems like all we need to do is take the existing `XTENSION= ASDF` HDU and change it to `XTENSION= FOREIGN`, and it will validate. Astropy has no problem reading this either, although it marks it as non-standard. Maybe we can ignore the queasy feeling we get from using the `FOREIGN` keyword without actually conforming in any way to the published `FOREIGN` convention.

I can't find any examples of files using the actual `FOREIGN` convention in the wild. I'm considering reaching out to NASA's FITS office to get more information, but maybe it's not worth it in the end. Does this seem like a reasonable solution for now? Also, is there someone I can talk to in the archive about this?

**Comment by philhodge** [comment]
Why not request a change to fitsverify?  It looks to me as if you jumped through the right hoops, but fitsverify isn't doing what it should.

**Comment by drdavella** [comment]
@philhodge that's' a good question, and maybe that is in fact the right thing to do. At that point it's also worth asking whether *anyone* actually uses the `FOREIGN` convention anymore, and it's also worth asking why `fitsverify` accepts `IMAGE` HDUs that use the `XTENSION= FOREIGN` as valid.

I suspect this particular path might be long and bumpy, with the possibility that it won't pay off in the end. But it's certainly worth investigating.

**Comment by philhodge** [comment]
I have reported two or three bugs in FITSIO or CFITSIO (admittedly that was a while ago), and they were fixed immediately.

**Comment by drdavella** [comment]
I just sent an email to the FITS office so hopefully we'll have some of these questions answered.

**Comment by hbushouse** [comment]
I would not feel comfortable simply changing the value of XTENSION to FOREIGN, but not at the same time actually making the format/content of the extension conform to the FOREIGN convention. This is a fitsverify problem, not ours. So it's good that you reported it.

**Comment by drdavella** [comment]
I have sent two emails to NASA's FITS office but haven't gotten a response. In the meantime, I have opened a PR in ASDF (https://github.com/spacetelescope/asdf/pull/483) with a workaround that would allow us to create files that will pass `fitsverify`. We can hold out a little longer for a response from the FITS office, but after that @stscicrawford has proposed that we should move forward with a workaround.

**Comment by drdavella** [comment]
So I finally got a response from the FITS office. It seems like the recommended solution is to use a `BINTABLE` to store the contents of the ASDF file. `FOREIGN` is not recommended since it is quite old and does not seem to be properly supported, even by `fitsverify`. It would take some effort and coordination with the FITS office in order to get proper support for that.

`BINTABLE` on the other hand will be recognized by all FITS readers. We will simply use a table with one row and one byte-array column with `TFORM = nB`, where `B` is the length of the file contents.

The only thing that remains to be seen is whether this is a reasonable solution for the archive, since they pushed for the move away from `IMAGE` HDUs in the first place.
