### ISSUE TITLE
calspec2 not using correct product suffixes for NIRSpec BrightObj (TSO) exposures

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1815]
There are hooks in the calwebb_spec2 pipeline that set the correct output product suffix for models that contain multiple integrations using:
```
if isinstance(input, datamodels.CubeModel):
```
which assumes that all multiple-integration models use CubeModel. A while back the processing flow for NIRSpec BrightObj mode exposures (which is a TSO mode and hence the data contain multiple integrations) was modified to send it through the `extract_2d` step, which means the output model type is no longer CubeModel, but rather something like MultiSlitModel (?). Ever since that change, the output files for NIRSpec BrightObj exposures have used the regular `_cal` and `_x1d` suffixes, instead of `_calints` and `_x1dints` (which finally explains why subsequent changes to calspec2 step code have not resulted in regression test failures for this mode, because the reg test isn't using the right input files).

The logic in calspec2 to determine when to use `calints` and `x1dints` needs to be updated to include this type of exposure.

**Comment by stscieisenhamer** [comment]
# Question
What constitutes TSO? There are the `exp_type`'s the are always TSO. However, I believe there is, or will be the case, that nearly any mode can also be requested to be taken in a TSO mode. The association pool will have such information, but at the exposure level, how does one know?

**Comment by stscieisenhamer** [comment]
Actually @hbushouse, does [JWSTKD-81](https://jira.stsci.edu/browse/JWSTKD-81) mean that there will be a header keyword TSOVISIT? This would then the be the flag, since it is supposed to be true for all tso-like observations.  Note: the keyword is apparently not been implemented yet.

**Comment by hbushouse** [comment]
Yes, that's it. If you can't tell TSO explicitly from EXP_TYPE, then the TSOVISIT keyword is the secondary indicator. Note that, if I remember the plans correctly, TSOVISIT will be False for those EXP_TYPE's that are explicitly TSO (e.g. NRC_TSIMAGE, NRC_TSGRISM, NRS_BRIGHTOBJ, and maybe MIR_LRS-SLITLESS). It will only be True for those generic EXP_TYPE's that are requested to be TSO (e.g. MIR_IMAGE, MIR_LRS-FIXEDSLIT). So you can't key off of TSOVISIT alone.
