### ISSUE TITLE
wcs_from_footprints miscalculating output frame

### ISSUE THREAD

**Issue by stsci-hack** [STScI-JWST/jwst#1816]
Testing of the Image3 Pipeline has uncovered an apparent problem with the computation of the WCS for the output frame.  For observations which are dithered/mosaiced (generally offset from one another), the output data seems to be offset from center by the same amount as the offset between the observations.  Fortunately, this does not seem to be affected by any corrections applied by the 'tweakreg' step.

Test data has been made available on central store in:
    /user/hack/data/jwst/Image3Test/

The test data consists of 4 frames at one pointing (*1101_A[1-4]) and 4 frames at another pointing (*1105_A[1-4]).  This test data includes a sample output which demonstrates this problem.  The test can be run using the included .cfg file and _asn.json file which performs a basic resampling to create the mosaic without outlier_detection or alignment.  

The problem was originally reported under the 0.9.0 environment, but it was reproduced using the latest dev version of the code.  The script included in this test directory, reset_gwcs.py, was used to reset the GWCS ASDF object in the input files to allow them to run under the dev environment.

**Comment by jdavies-st** [comment]
I've verified the same behavior as @stsci-hack.

This is the exact same buggy behavior that we saw in #1219 which we "fixed" in #1220.

**Comment by jdavies-st** [comment]
If I set `resample.blendheaders = False`, this bug goes away, and the output frame is set correctly.  So somewhere in the call to `model_blender`, it must be doing something to the GWCS object of the output image.
