### ISSUE TITLE
AstropyDeprecationWarning astropy.tests.pytest_plugins

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#1840]
When one runs pytest from the top level directory of the repository, one gets the following deprecation warning multiple times:
```
WARNING: AstropyDeprecationWarning: The module `astropy.tests.pytest_plugins has been deprecated. The variables `PYTEST_HEADER_MODULES` and `TESTED_VERSIONS`should now be imported from `astropy.tests.plugins.display`. The function `enable_deprecations_as_exceptions` should be imported from `astropy.tests.helper` [astropy.tests.pytest_plugins]
```
The `pytest_plugins` seem to be used for asdf schema tests?  @nden?

A further issue is that there are two `conftest.py` modules, one at the top level which defines `--runslow` and one in the `jwst/` subdir that does these astropy test imports.  We should probably only have one at the top directory.  Thoughts?

**Comment by stscieisenhamer** [comment]
Only one would be nice. Wasn't sure how "top" should be defined for testing, so put one at the top. But if it should be in the subdir `jwst`, that's cool.

Note: I don't get the deprecation warning.

**Comment by nden** [comment]
IIRC the "top" level did not run schema tests while the "second top" did. I may be wrong though. I'll double check. 

Now that I ran it again I don't get the deprecation warnings either. Still, will look into consolidating the two files.

**Comment by jdavies-st** [comment]
If pytest is run from the top level directory, it produces the deprecation warnings.  If run from the `jwst` subdir, it does not.  Hmm.

Running `python setup.py test` from the top level does not produce the deprecation warnings either.  Double hmm.

**Comment by drdavella** [comment]
This is coming from the `jwst/conftest.py` file. I can fix it.
