### ISSUE TITLE
OutlierDetectionStep copies input when no operation is peformed

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1845]
# Issue
`OutlierDetectionStep`, if it has determined that detection cannot be performed, copies the input and returns that copy.

However, if detection is able to be performed, no such copy occurs. At least when the input is a `ModelContainer`

So, should the return always be a new object, or never a new object? Or...

**Comment by jdavies-st** [comment]
In many other steps a copy is returned of a single `datamodel` object.  But is there a good reason to do so?  If there's a container of N objects, is there any use in copying all the objects and then returning them?

**Comment by stscieisenhamer** [comment]
at least for this situation, I would claim no copy since the behavior, when detection occurs, does NOT copy.

**Comment by hbushouse** [comment]
Outlier_detection was intended to always work on the inputs in-place, updating the DQ flags of the inputs to indicate where it found outliers. So it's especially unnecessary to have the 1-input case do a copy, because the input isn't be touched at all. So just return it.
