### ISSUE TITLE
suffix removal not robust enough

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1870]
# Issue
What should have been "known" suffixes are still not getting removed.

# Implementation
- [x] bump version
- [x] tests
- [x] code
    - [x] Add suffix generation code
    - [x] Update `remove_suffix` to use the above results.
- [x] tests
- [x] bump version

**Comment by jdavies-st** [comment]
But `_extract_2d` is not a known suffix.  Shouldn't the defaults for these be set to `_x1d`?

**Comment by hbushouse** [comment]
I was also confused about that point @jdavies-st . I was under the impression that "known suffixes" only included the ones used for standard pipeline products, like `_rate`, `_cal`, `_i2d`, `_x1d`, etc. Is it the intention to add all the individual step class names to the list of known suffixes? I'm not saying it shouldn't be done, I just wasn't aware that that was the intention.

**Comment by stscieisenhamer** [comment]
"Known suffixes" include the step names. This is actually one of the basic parts of `Step` where, if a suffix is not define, the step name is used as the suffix. Part of the bug here is that I had, in some branch, put in code to check for "the current Step" as part of the removal, but must had decided against it, in preparation for something a bit more robust.

Ultimately, a list is needed and it will require maintenance. Part of this issue will be to make sure the list is better exposed and documented. There are also ways of increasing the dynamic robustness of the algorithm, which should be easy enough to do.

**Comment by jdavies-st** [comment]
Now that every step has a `suffix` attribute, wouldn't it be better to have that be the default suffix rather than the step name?

And if every step does not have a default suffix, should we make it a requirement?
