### ISSUE TITLE
Row in the MSA ref file picked up incorrectly

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#1897]
The pipeline code indexes the rows in the MSA ref file using the shutter ID. The MSA file has one shutter per row. However, the shutter IDs are numbered starting from 1 and the indices start from 0. This was originally fixed in #1879. Subsequent review revealed this is not the best place to fix the problem because the shutter IDs are also used by the barshadow correction. A better approach is to correct the index when retrieving the MSA row. This has been implemented in the Nirspec testing branch and will be merged when that branch is merged with master.

**Comment by stscicrawford** [comment]
Shutters are being counted from 1 and slices in the IFU from 0.   @nden please note PR that fixes this

**Comment by nden** [comment]
Fixed in this [commit](https://github.com/nden/jwst/commit/d319a2ae0d59efcb23bbc5c4bc6d6cc674d52708).
