### ISSUE TITLE
Log association exposure being processed

### ISSUE THREAD

**Issue by jaytmiller** [STScI-JWST/jwst#1900]
One of the recent SIC/DIL errors was related to processing this association:

/ifs/int/jwstc/store/doggett/tests/SIC/DIL/cstring/JWSTDP-2018_1-180323/2018-03-28-210018/sdp/asn_creation/cal/level2/jw82600-o018_20180328t210625_image2_002_asn.json

More details:  https://jira.stsci.edu/browse/CRDS-191

Q:  what logging exists to identify the level-2 exposure .fits being processed in an association?  Would that logging be generally applicable to debugging or is CRDS the only application?

**Comment by jdavies-st** [comment]
It seems like some logging in the `stpipe.pipeline` code might make this possible?  The private method

https://github.com/STScI-JWST/jwst/blob/22a880b8981b06f4c14bd37ad7a0430991b8907d/jwst/stpipe/pipeline.py#L174

seems to do the work for pipelines.  Would we want this logging in steps as well?  Right now, the `Step` class is only aware of containers/associations in writing out results, not reading them in.

**Comment by jdavies-st** [comment]
@stscieisenhamer any thoughts?

**Comment by stscieisenhamer** [comment]
Not having looked very closely at how reference files are retrieved, there seems to be two situations:

1. Precaching, done by `Pipeline`'s
2. Actual reference file retrieval.

For the easy case, case 2., the call to retrieve reference files should be the one logging for what data the reference files are being retrieved for. I'm guessing this is being passed a `DataModel`, so the log should report on what `DataModel.meta.filename` is. This can be done in either the jwst code, or the crds code.  Presuming crds is a bit more general, where sometimes the data is not jwst, I would stick in in the jwst side.

For case 1., how are associations being handled anyways? Presumably either the first member is being examined, or all the members are being examined. Regardless, at some point, a call is being made to fetch the reference files, or at least the reference file names. Whatever this call is, the `DataModel.meta.filename` can be reported, again on the jwst side of the call.

**Comment by jaytmiller** [comment]
As it turns out,  I think the best place to do it is probably (1) where the exposure .fits filename is first resolved and the model is opened.   It's just direct and cleaner.

One reservation I have is that this is much more general functionality than "prefetching references".    I think it's highly unlikely because we need it for error detection,  but it's conceivable that the prefetch would be dropped.   It's not really conceivable to "not process exposures" and I think info is probably always top level "relevant to everyone" info.   I think maybe the need only becomes critical however in a DMS-level environment where the user/developer is not immediately aware what the exposures are because there are 1000's being processed.

**Comment by jaytmiller** [comment]
Yes,  I think we can close this.   Thanks!
