### ISSUE TITLE
Define  __repr__/__str__ for DataModel

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#1909]
# Issue
`DataModel` has no `__repr__` or `__str__` definition. Consider defining one or both to provide a bit more information in log/text output than just "DataModel object at 0x23515623425".

# Resources
- #1900

**Comment by philhodge** [comment]
repr and str should dump the entire object.  repr in particular is supposed to return a string that could be used to create a new copy of the object.  Maybe a .info method would give the kind of information that you're looking for.  I agree that that would be useful.

**Comment by jdavies-st** [comment]
Right now, both methods give
```
<jwst.datamodels.image.ImageModel at 0x181ebf8f28>
```
So when a step gets passed one that has already been opened, it logs something like
```
INFO - Step resample running with args (<jwst.datamodels.container.ModelContainer object at 0x1c249da5c0>,).
INFO - Blending metadata for mymosaic
INFO - Drizzling (2048, 2048) --> (4865, 2100)
INFO - Drizzling (2048, 2048) --> (4865, 2100)
INFO - Step resample done
INFO - Saved model in mymosaic_i2d.fits
INFO - Creating source catalog...
INFO - Step source_catalog running with args (<jwst.datamodels.drizproduct.DrizProductModel object at 0x1c4019f9b0>,).
```
What one really wants in the log is
```
INFO - Step resample running with args (ModelContainer <-> mymosaic_asn.json).
INFO - Blending metadata for mymosaic
INFO - Drizzling (2048, 2048) --> (4865, 2100)
INFO - Drizzling (2048, 2048) --> (4865, 2100)
INFO - Step resample done
INFO - Saved model in mymosaic_i2d.fits
INFO - Creating source catalog...
INFO - Step source_catalog running with args (DrizProductModel <-> mymosaic_i2d.fits).
```
But maybe a better syntax.
