### ISSUE TITLE
For NIRSpec, flat_field should not require all three flats

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#1914]
There are three different types of flat field reference file for NIRSpec data, and currently all three types are used for any NIRSpec mode that can be flat fielded.  The `flat_field` step requires that all three reference files be available (i.e. the file name must not be "N/A"), but there is no good reason for that constraint.  Furthermore, for NRS_AUTOWAVE data, only the spectrograph and detector portions (SFLAT and DFLAT) are relevant, because the light does not go through the fore optics.  The step should be modified to allow one or more of the reference files to not be available.

**Comment by hbushouse** [comment]
Fixed by #1967
