### ISSUE TITLE
Strip path from ASNTABLE keyword value

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1940]
DMS has encountered issues with saving the value of the ASNTABLE keyword in the archive catalog, due to the fact that the full directory path is included with the file name, which in turn overfills the archive catalog field for this keyword (see https://www.ess.stsci.edu/prsystem/servlet/prbrowse/dr.4566). They would like to have the directory path removed from the value, as is apparently already done with the value of ASNPOOL keyword.

**Comment by hbushouse** [comment]
For those who may not have access to the PR system:
```
During the process of doing a test procedure, I found this:

[24] IWJWDMSBDB.jwarchiveops.1> SELECT asntable from ScienceCommon WHERE
ArchiveFileID = 5614895 [24] IWJWDMSBDB.jwarchiveops.2> go
asntable
--------------------------------------------------------------------------------
----------------------------------------
/ifs/int/jwst/info/jwowlmgr/build7.1/paths/sdp/asn_creation/cal/lev&

(1 row affected)
[25] IWJWDMSBDB.jwarchiveops.1>

The asntable field is a nvarchar(120), the value in the database is 68
characters long, so it looks like a truncated value is being put into the
database.  Looking at the cal file it came from, we see:

[jwowlmgr@iljwdmsbcsched dms-tp-822]$ grep -i asn
jw95065008001_02101_00001_nrs1_cal.lis ASNPOOL = 'jw95065_20171207T055317_pool'
/ Name of the ASN pool ASNTABLE=
'/ifs/int/jwst/info/jwowlmgr/build7.1/paths/sdp/asn_creation/cal/lev&' CONTINUE
 'el2/jw95065-o008_20171207t055317_spec2_002_asn.json&' CONTINUE  '' / Name of
the ASN table [jwowlmgr@iljwdmsbcsched dms-tp-822]$
```

**Comment by jdavies-st** [comment]
Thanks @hbushouse.  This looks like a simple fix in ModelContainer class.  I'll do this change when I strip out the superfluous schema values.

**Comment by jdavies-st** [comment]
I've already done the change.  Will submit the PR today.
