### ISSUE TITLE
Move doc build to RTD?

### ISSUE THREAD

**Issue by pllim** [STScI-JWST/jwst#198]
Why not?

**Comment by jhunkeler** [comment]
Similar to how to we converted the namespace packages down into sub-packages, we'd just have to move the guts of each Sphinx project to the top-level and adjust the index.rst to compensate. Then of course we'd need to sift through the errors and fix them as they occur (i.e. import failures, uncaught requirements, inter-sphinx linkage, etc).

Then... ship it off to RTD and be done with it ;)

**Comment by hbushouse** [comment]
If that's the direction we're going with other HST/JWST/STScI packages, it seems reasonable to me, at the very least for consistency.

**Comment by pllim** [comment]
Re: move the guts of each Sphinx project to the top-level

I think that has to be done regardless of moving to RTD or not. It just does not make sense to have so many different docs for the same pipeline...

**Comment by hbushouse** [comment]
Agreed. This is simply still a leftover from long ago when the first individual pieces of the cal pipeline were constructed independently by multiple developers and so they just put the docs in with the code for their step. We've just never taken the time yet to go back and do it the right way now that we have a package that contains dozens of step sub-packages.
