### ISSUE TITLE
Change NRC_GRISM to NRC_WFSS

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1985]
SDP is working on updates that will change the EXP_TYPE value 'NRC_GRISM' that is used in all front-end systems for the NIRCam grism (Wide-Field Slitless Spectroscopy) mode to 'NRC_WFSS', for the sake of consistency with the 'NIS_WFSS' EXP_TYPE used for NIRISS WFSS mode. All references to 'NRC_GRISM' in Cal pipeline code and data model schemas should be updated to include the value 'NRC_WFSS' (i.e. we want Cal code to accept **both** values, for backwards compatibility with existing data products and test files).

**Comment by hbushouse** [comment]
A quick check through the code base shows that `NRC_GRISM` appears in:

- [ ] assign_wcs/assign_wcs.py
- [ ] assign_wcs/nircam.py
- [ ] background/background_step.py
- [ ] datamodels/wcs_ref_models.py
- [ ] extract_1d/extract.py
- [ ] extract_2d/extract_2d.py
- [ ] outlier_detection/outlier_detection_step.py
- [ ] photom/photom.py
- [ ] pipeline/calwebb_spec2.py
- [ ] datamodels/schemas/core.schema.yaml
- [ ] datamodels/schemas/keyword_exptype.schema.yaml
- [ ] datamodels/schemas/keyword_pexptype.schema.yaml

**Comment by hbushouse** [comment]
extract_1d/extract.py was updated in #1987

**Comment by stscieisenhamer** [comment]
Added the general `associations` to the above checklist.

Also question: Is there a change to `NRC_TSGRISM` or does this stay the same?

**Comment by hbushouse** [comment]
`NRC_TSGRISM` is staying the same, because it's consistent with the name of the observing template "Time Series Grism".

**Comment by sosey** [comment]
see https://github.com/STScI-JWST/jwst/pull/2037
