### ISSUE TITLE
Is it NIS_IMAGE or NRS_IMAGE?

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#199]
Documents (to be found) say that EXP_TYPE for NIRISS imaging is NIS_IMAGE. Build6 however is producing NRS_IMAGE. This could be a Build6 issue, or someone didn't rename something.

**Comment by hbushouse** [comment]
The 3-letter acronyms for each instrument, which are used in the prefix of each EXP_TYPE, are:

FGS = FGS (duh!)
MIRI = MIR
NIRCam = NRC
NIRISS = NIS
NIRSpec = NRS

So NIRISS imaging should in fact be 'NIS_IMAGE'. It's NIRSpec imaging that is 'NRS_IMAGE'. Which parts of B6 are supposedly using the wrong instance?

**Comment by stscieisenhamer** [comment]
Then it is a bug with the rules. Will figure out.

**Comment by stscieisenhamer** [comment]
Going through the exposure types, the issue is that NIRSpec imaging is classified as an engineering mode, so I did not include it in the generic imaging mode rule. Is this true?

**Comment by hbushouse** [comment]
That does seem to be the case, as there is no NIRSpec Imaging observation template available in APT to "regular" users. I have to click the "Allow Restricted" button in APT to get NIRSpec Imaging to appear in the list of observing templates for NIRSpec. Exposures taken in this mode would only receive regular detector-level processing and hence there's no need (that I can see) for them to ever appear in ASN tables for higher-level processing.

**Comment by stscieisenhamer** [comment]
w00t1 non-bug! at the moment...

**Comment by stscieisenhamer** [comment]
Unrelated but bugs:
- [ ] Rule Asn_NIR_IFU -> Asn_NRS_IFU
- [ ] Rule Asn_NIR_MSA -> Asn_NRS_MSA
