### ISSUE TITLE
[RT] Update comparison files for regression tests

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#1996]
The comparison files for the following regression tests need to be OK-ified due to a change from numpy 1.13 to numpy 1.14 so that can pass on the Jenkins side.

- [x] niriss.test_ami_analyze.test_ami_analyze
- [x] niriss.test_ami_pipeline.test_ami_pipeline
- [x] pipelines.test_coron3_1.test_coron3_pipeline1
- [x] pipelines.test_nrc_image3_1.test_image3_pipeline1

Once updated they will start passing on the Jenkins side and failing on pandokia.

The differences in these numerical results are tracked by issue #1988.

**Comment by jdavies-st** [comment]
The Jenkins build stores outputs from each test into its own directory.
```
/data1/jenkins/workspace/RT/JWST/test_outputs/
```
Make dated backups of each old file and then update to the new ones:
```
cd /data1/jenkins/workspace/RT/JWST/test_outputs
cp -u test_ami_analyze-current/ami_analyze_output_16_ami_analyze.fits /data4/jwst_test_data/niriss/test_ami_analyze/ami_analyze_ref_output_16.fits
cp -u test_ami_pipeline-current/test_targ_aminorm.fits /data4/jwst_test_data/niriss/test_ami_pipeline/ami_pipeline_targ_lgnorm.fits
cp -u test_coron3_pipeline1-current/jw9999947001_02102_00001_nrcb3_a3001_psfalign.fits /data4/jwst_test_data/nircam/test_coron3/jw99999-a3001_t1_nircam_f140m-maskbar_psfalign_ref.fits
```
I did not update the `test_image3_pipeline1` comparison file yet, as the test for that is currently failing and not producing an output file due to an unrelated issue.

@hbushouse the 3 tests above should now be updated to pass under numpy 1.14.

**Comment by nden** [comment]
Can someone, who knows more about the setup, add Jenkins related "Howto" to the JWST wiki for future reference.

**Comment by jdavies-st** [comment]
Updated two more comparison files that have these same python 1.13 vs 1.14 issues:
```
cp -u test_coron3_pipeline1-current/jw9999947001_02102_00001_nrcb3_a3001_psfsub.fits /data4/jwst_test_data/nircam/test_coron3/jw9999947001_02102_00001_nrcb3_psfsub_ref.fits
cp -u test_image3_pipeline1-current/mosaic_long_i2d.fits /data4/jwst_test_data/pipelines/nircam_calimage3/mosaic_long_i2d_ref.fits
```

**Comment by hbushouse** [comment]
@jdavies-st Not related to comparison files, but could we remove the "runslow" tag from the nis_wfss_spec2 test (under pipelines)? This test only takes 3 minutes, which (IMHO) is not all that long, and it's the only test we have that exercises grism (WFSS) processing. I've had it active on the Pandokia side for the past 1-2 weeks now (after fixing the errors in the test module itself).

**Comment by jdavies-st** [comment]
Sounds good @hbushouse.  Feel free to do a PR.

**Comment by jdavies-st** [comment]
Updated one more comparison file to get the coron3 test to pass.
```
cp -u test_coron3_pipeline1-current/jw9999947001_02102_00001_nrcb3_a3001_crfints.fits /data4/jwst_test_data/nircam/test_coron3/jw9999947001_02102_00001_nrcb3_a3001_crfints_ref.fits
```

**Comment by jdavies-st** [comment]
Yet another file updated.  Finally are we done OK-ifying this test?
```
cp -u test_coron3_pipeline1-current/jw9999947001_02102_00002_nrcb3_a3001_crfints.fits /data4/jwst_test_data/nircam/test_coron3/jw9999947001_02102_00002_nrcb3_a3001_crfints_ref.fits
```

**Comment by hbushouse** [comment]
"Finally are we done OK-ifying this test?"  Don't bet on it. There are more products yet beyond this one. There's at least an _i2d product from resample.

**Comment by jdavies-st** [comment]
Looks like these are all working now.  Closing this issue.
