### ISSUE TITLE
do performance analysis

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#208]

**Comment by stscieisenhamer** [comment]
Examine test_io.py first.

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] General analysis
- [ ] Change how list are handled #799

**Comment by stscieisenhamer** [comment]
OMG. The whole story is shown in the following image. Look at the ONE line that is 98.6% of the time...yep, a debug statement. Removing this one statement increased performance by about a factor of about 200. Note that the log level was not even set for debug, yet the debug call clearly goes through everything it would to print. Not there isn't other efficiencies that could be gained, but this has solved the majority of issues.

![screen shot 2017-05-01 at 11 43 59 pm](https://cloud.githubusercontent.com/assets/5658688/25603271/34e5fdbc-2ec8-11e7-9ff2-1c17a560f1da.png)

**Comment by hbushouse** [comment]
Now that you mention it, I seem to recall noticing a similar thing recently with logging. I was running one of the pipelines, letting the log info go to stdout as usual, and then when I ran it again while doing something to either redirect the log to a file or suppress the logging, I was amazed at how quickly the whole pipeline ran to completion. It was done waaaaaay faster than when you let the log messages appear.
