### ISSUE TITLE
flat_field error for NRS_BRIGHTOBJ 2-D product

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#2080]
https://jira.stsci.edu/browse/JP-318 reports instances of the _rate products of NRS_BRIGHTOBJ exposures causing an error in the flat_field step, because the step is expecting the data to be 3-D (_rateints product as input), whereas the _rate product contains 2-D data. We expect that the 3-D rateints product will always be the one to be processed through calwebb_spec2 for NRS_BRIGHTOBJ exposures, but I imagine there's a chance that some user might also be interested in processing the 2-D (integration averaged) product. At the very least we should try to add some hooks into the flat_field step so that it recognizes the 2-D input and shutsdown gracefully with a warning/error message. With some more work, we could perhaps allow processing to proceed on the 2-D form of the data.

**Comment by philhodge** [comment]
Fixed by #2088
