### ISSUE TITLE
Skip spectral extraction if dispaxis could not be determined

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#2102]
The dispersion direction is needed in order to extract a 1-D spectrum from a 2-D image.  (For IFU data the dispersion direction is assumed to be the first axis.)  If the dispersion direction was not specified in a reference file, and if the `extract_1d` step was not able to determine the direction based on the wavelengths, the step should skip extracting the spectrum.  This might be the case for some spectra in a file but not others, e.g. for some spectral orders, or when most of a spectrum is off the detector, in which case some spectra will be extracted and others will not be.

There was a case (I don't understand it!) where the `find_dispaxis` function in `extract_1d` found differences in wavelengths and a dispersion direction for spectral order 0.  A separate test should therefore be included to reject (i.e. not extract) any "spectrum" with spectral order 0.

**Comment by sosey** [comment]
for grisms dispersion direction doesn't get done until extract2d, is there a reason in other modes to hold off til then?

**Comment by jdavies-st** [comment]
What I've done in the past is pass a grid of X,Y values to the GWCS object and see which direction wavelength varies the most.  I suspect thought that this could get done as soon as `assign_wcs` is run, then we could use that information in any step later on that needs it.

**Comment by sosey** [comment]
in WFSS it comes out of the process of defining the spectral bounding boxes, it can only be done after `assign_wcs` and you need the wavelengthrange reference file to get appropriate values for the wavelengths to use. Instead of putting it with a step, we could add some functions to the higher library, maybe a `lib/spectral_utils.py` ?

**Comment by philhodge** [comment]
Couldn't the dispersion direction be an attribute of the wcs?  It could be None until it can be determined, e.g. after computing the bounding box.  By the way, I've seen some NIS_WFSS data for which `bounding_box` was None, and this was after `extract_2d`.

**Comment by sosey** [comment]
the bounding box for wfss should be the entire size of the image, the starting image, then each of the 2D extraction boxes, the wcs is good everywhere. The distorion transform carries it's own bounding box which should be available.  At some point `None` was interpreted as being the whole image. I just chatted with nadia and she mentions thinking about what do with this in general in gwcs. I can certainly go add the image size as a bounding box in the wfss for the pipeline.

**Comment by hbushouse** [comment]
Fixed by #2178.
