### ISSUE TITLE
MIRI MRS associations need to include multiple products

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#218]
There's an on-going discussion as to the structure and content of MIRI MRS ASN files. The cube_build task will construct multiple types and levels of products from a given set of MRS exposures. The possible types of products include:

1) Channel 1 data from all exposures with detector=MIRIFUSHORT and BAND=SHORT|MEDIUM|LONG

2) Channel 2 data from all exposures with detector=MIRIFUSHORT and BAND=SHORT|MEDIUM|LONG

3) Channel 3 data from all exposures with detector=MIRIFULONG and BAND=SHORT|MEDIUM|LONG

4) Channel 4 data from all exposures with detector=MIRIFULONG and BAND=SHORT|MEDIUM|LONG

5) Channel 1+2 data from all exposures with detector=MIRIFUSHORT and BAND=SHORT|MEDIUM|LONG

6) Channel 3+4 data from all exposures with detector=MIRIFULONG and BAND=SHORT|MEDIUM|LONG

7) Channel 1+2+3+4 data from all exposures with detector=MIRIFUSHORT|MIRIFULONG and BAND=SHORT|MEDIUM|LONG

The product name for each type would include an attribute called "channel", which would be used by the cube_build step to determine which part of the input data to use (there are 2 channel's worth of data in a single exposure), e.g.

`product: {"name": "jwppppp_....fits", "channel": "1", "members": [...]}`

CV3 SIL-DIL program 80600 contained some MIRIFUSHORT exposures, which could potentially be used to develop and test these capabilities.

**Comment by stscieisenhamer** [comment]
Resolved and is now tracked by #235
