### ISSUE TITLE
FGS associations should only contain 1 detector

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#219]
Ed Nelan indicates that when FGS is used in "science" mode to obtain regular imaging, only 1 of the 2 detectors will be used for the science observations, because the other one will always have to be used for guiding. CV3 SIC-DIL program 86600 contained FGS_IMAGE exposures, which in some cases resulted in ASN's containing a mixture of exposures from detectors Guider1 and Guider2. The FGS ASN rule needs to be updated to require a unique value for detector.

**Comment by stscieisenhamer** [comment]
@hbushouse Question: Is there an indicator of which one is the science? Or should both be done separately to be handled by the observer downstream?

**Comment by hbushouse** [comment]
I assume you would simply key off of the EXP_TYPE value, which would be 'FGS_IMAGE' for exposures taken in science mode. Guide-mode exposures will use some other EXP_TYPE value. I'll try to find out from Daryl Swade what the guide-mode values will be (they aren't listed in the latest exp_type spreadsheet that I have).

**Comment by hbushouse** [comment]
Daryl indicates that FGS guide-mode data don't come through the science channel and hence don't even get an EXP_TYPE assigned. So we won't see FGS guide mode data in ASN pools at all.

**Comment by stscieisenhamer** [comment]
Then nothing to do! The most ideal of bug resolutions.
