### ISSUE TITLE
Change Level3 product naming to just allow appending of extra info to name.

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#222]
Previously, a scheme was developed to allow Level 3 modules to modify the Level3 product names without having to know the format of said names through the use of formatting templates. Upon further reflection with @hbushouse, this was deemed unnecessary and too complicated for downstream users.

Instead, the suggested names will simply be considered prefixes, leaving it up to the Level3 modules to append information such as product type and extension. Current DMS standards allow this. If DMS standards change to make this unfeasible, the standards will be fought, anchorman-style.

**Comment by hbushouse** [comment]
👍

**Comment by stscieisenhamer** [comment]
Resolved in PR #223
