### ISSUE TITLE
Rule: MIRI MRS (IFU)

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#235]
This issue overrides the originating [TRAC issue](https://aeon.stsci.edu/ssb/trac/jwst/ticket/216).

**Comment by stscieisenhamer** [comment]
# Implementation
## Constraints:
- PNGTYPE='SCIENCE' | 'TARGET_ACQUISITION'
- INTRUME='MIRI'
- EXP_TYPE='MIR_MRS'
- FILTER=_unique_
- PROGRAM=_unique_
- DETECTOR=_unique_
- TARGNAME=_unique_

## Notes:
- One association with one product with all exposures
- Level3 module will have switches to decide on what products, besides the uber-cube, will be produced.
- Product name will only be specified up to the instrument: jwPPPPP-cCCCC_tTTT_miri. The cal routine needs to append _optical_elements_product_type_.fits
- _optical_elements_ is some combo of channel and band, separated by '-' dashes.

**Comment by stscieisenhamer** [comment]
@hbushouse @jemorrison 
Clarifications requested:
- In APT, is this referred to as "Low Resolution Spectroscopy"?
- The observer has no options on any optical elements: The MRS is a fixed set of gratings.
    - As has been agreed on: any exposure that belongs to an MRS observation is included in a single association: there is nothing further to filter on.
- There is an 'ACQ Filter' and there seems to be some sort of target acquisition: what does target acq involve and should said exposures be included in the association? Is there need to create separate associations based on the acq filter?

**Comment by hbushouse** [comment]
In APT the MRS mode is "Medium Resolution Spectroscopy" (hence the 3 letters of the acronym).

Should not be any need for separate associations based on acq filter(s). Just lump all of the targ_acq exposures that are logically related to the MRS observations into the ASN, with exptype='TACQ' in the ASN table.

**Comment by stscieisenhamer** [comment]
# Issue
How will the dedicated background exposures be identified so that we know to include them in an association? 

As of 6/8/2015 Rob Douglas indicates that they will likely expand the dither patterns to include background CHOP exposures, in which case the background exposure(s) would show up as an additional pointing within each set of dithered exposures and the background exposures would have a pointing_type of CHOP (while the target exposures would have SCIENCE).

**Comment by hbushouse** [comment]
More recent conversations with APT/PPS indicate that dedicated backgrounds will use separate targets and observations (i.e. _not_ part of the dither pattern for the science target) and there will be an additional field in APT that allows users to indicate that this target/observation is to be used as background for target/observation n. PPS will then create a 'BACKGROUND' type association candidate ID for the linked observations. And it sounds as if there will be an additional PPS DB table field that will be used to mark which of the observations in the candidate are the background.

https://www.ess.stsci.edu/prsystem/servlet/prbrowse/PR.83416

**Comment by stscieisenhamer** [comment]
@hbushouse This association is now pretty much like the NIRSpec IFU association. Because there is no dependency on optical elements, we gave NIRSpec IFU its own association type, `nrsifu`. Based on that logic, it seems this association is its own type also, `mrimsa`. Is this true?

**Comment by hbushouse** [comment]
If you actually mean "mirmrs", then I'd say yes.

**Comment by jemorrison** [comment]
Well if it is nrsifu for NIRSPec would it not be mrsifu for MIRI MRS ?

**Comment by hbushouse** [comment]
Yeah, there's the whole "mrs" versus "ifu" ying-yang for MIRI. Just like the wide-field slitless spectroscopy mode for NIRISS is referred to as "wfss" in the exp_type, while the same exact mode for NIRCam is referred to as "grism". Oy. Why can't we all just get along?

I'm happy to go either way with this one. It is in fact IFU data, it's just obtained via the MRS mode of the instrument.

**Comment by stscieisenhamer** [comment]
Ya, this is all just being consistent with how things are currently being documented. No matter to me either way.

**Comment by hbushouse** [comment]
OK, executive decision: "MIRIFU"  (not MRSIFU; that's redundant). Official 3-letter instrument ID ("NRS", "MIR"), followed by IFU.

**Comment by stscieisenhamer** [comment]
# Closing Notes
The concept of using separate types here has been removed for the moment. All of these are now just `spec3` associations. There is still output naming issues, but those will be dealt with in other issues.

**Comment by stscieisenhamer** [comment]
# Note
The concept of a different association type has been dropped for the moment. All IFU associations will currently remain `spec3` and be handled by `calwebb_spec3`

**Comment by stscieisenhamer** [comment]
Dedicated background has been implemented in #1194 and #1726. This issue is now resolved.
