### ISSUE TITLE
How to redo NIRSpec background sub?

### ISSUE THREAD

**Issue by pllim** [STScI-JWST/jwst#25]
If I want to rerun background subtraction step with my own background aperture, how do I do it? This question came up in JWST DADF MOS Tools sprint.

**Comment by hbushouse** [comment]
Which type of background subtraction are we talking about? Given the reference to the term "aperture", I'm guessing they're talking about a NIRSpec MOS observation that had some shutters designated as being used strictly for background? But I believe in this case the standard procedure is to extract the data from all the dedicated background apertures, average them together onto a common wavelength grid, and then essentially deproject this average background spectrum back into the space of each target aperture and subtract them from one another. I'm not sure there's a way to specify one or more particular background apertures to use for a given target aperture. We haven't developed those parts of the cal pipeline yet (coming in Build 7).

**Comment by pllim** [comment]
Sprint is over long time ago, so closing.
