### ISSUE TITLE
extract_2d should extract SOSS slits

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#262]

**Comment by nden** [comment]
@hbushouse Is this a valid issue? I saw on Trac that support for extract2d was removed because the team did not want to have 2D cutouts. Should we close this?

**Comment by hbushouse** [comment]
Yes, the latest word seems to be that for all the science mode exposures using NIRISS SOSS they do NOT want the orders extracted. They only want to extract them when they're doing observations of standard stars (for flux calibration) and need to analyze the individual orders separately. We can work out that hook later. For now - no extract_2d on NIRISS SOSS exposures.
