### ISSUE TITLE
Task: NIRSPEC - IFU

### ISSUE THREAD

**Issue by brechmos-stsci** [STScI-JWST/jwst#271]
To Do

- [x] Implement PRISM (common for all NIRSPEC)
- [x] Looking into pixel differences in the location of the spectrum on the detector compared to IDT data  (common for all NIRSPEC)
- [x] V2/V3 to Sky (common for all NIRSPEC)

**Comment by brechmos-stsci** [comment]
We are reproducing the model but we need to reproduce the conversion to full frame coordinates.

**Comment by nden** [comment]
implemented in #389 and #309
