### ISSUE TITLE
Task: NIRSPEC - MOS

### ISSUE THREAD

**Issue by brechmos-stsci** [STScI-JWST/jwst#272]
To Do

- [x]  Complete the MSA configuration file - hook with the rest of the code
- [x] Implement PRISM
- [x] Looking into pixel differences in the location of the spectrum on the detector compared to IDT data
- [x] V2/V3 to Sky

**Comment by brechmos-stsci** [comment]
We are reproducing the model but we need to reproduce the conversion to full frame coordinates.

**Comment by nden** [comment]
Prism implemented in #389, msa configuration file in #345 and V2V3 in #309
