### ISSUE TITLE
Task: NIRCAM - Image

### ISSUE THREAD

**Issue by brechmos-stsci** [STScI-JWST/jwst#277]
To Do
- [x]  V2/V3 to sky
- [x] Enable new modes in assign_wcs - EXP_TYPEs spelled out in Howard's comment.

**Comment by brechmos-stsci** [comment]
Currently the distortion comes from the SIAF file.

**Comment by hbushouse** [comment]
NIRCam image mode transforms also need to be extended in the CRDS rmap coverage to not only apply to exp_type=NRC_IMAGE, but also NRC_CORON, NRC_FOCUS, NRC_TACQ, and NRC_TSIMAGE. All of these modes are some flavor of direct imaging and hence the same WCS transforms can apply to all.

Note that the current CRDS NIRCam distortion rmap has entries for exp_type's NRC_TSI and NRC_TSS. These are old guesses at what the exp_type values would be for time series imaging and spectroscopy. We now know that the "official" exp_type values will be NRC_TSIMAGE and NRC_TSGRISM. Hence these entries in the rmap should be updated.

All of this work is an action on CRDS (ReDCaT), not the cal pipeline, hence they need to be informed to make these updates.

**Comment by nden** [comment]
These modes (with the correct exp_type) will need to be enabled in assign_wcs as well.

Bryan volunteered to convert and deliver new reference files for NIRCAM using the scripts we used for build 5.

**Comment by hbushouse** [comment]
Will the new ref files have both forward and reverse transforms? I believe the current set only has forward, which means the outlier_detection step in calimage3 can't work, because it has to be able to go both directions.

**Comment by nden** [comment]
Looking at the code the current reference files should have the inverse transforms. File an issue if they are not working.
