### ISSUE TITLE
Target Acquisitions need to association with their related science exposures

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#297]
From the DMS requirements:
> _DMS-554: The DMS shall associate Target Acquisition exposures with their subsequent Science exposures._

Resurrecting from originating [TRAC issue](https://aeon.stsci.edu/ssb/trac/jwst/ticket/242) because it is currently unknown how to know which target acquisition exposures go with which science exposures. Basically, `xxx_TACQ` must either be within the same observation, or an association candidate must be defined.

**Comment by stscieisenhamer** [comment]
@hbushouse Who should I pursue this with? PPS I presume?

**Comment by hbushouse** [comment]
Yes, the APT/PPS folks should know how the TACQs are logically associated with science exposures by the user. I believe it’s at the observation level.

On Sep 27, 2016, at 10:32 PM, Jonathan Eisenhamer <notifications@github.com<mailto:notifications@github.com>> wrote:


@hbushouse<https://github.com/hbushouse> Who should I pursue this with? PPS I presume?

**Comment by stscieisenhamer** [comment]
PPS has been questioned...

**Comment by stscieisenhamer** [comment]
And answered:
> Target Acq is in the same observation. So they’ll only have the OBSERVATION association type.

**Comment by stscieisenhamer** [comment]
# Implementation
## ToDO
- [ ] Add `xxx_TACQ` to each instrument base rule.
