### ISSUE TITLE
Implement new NIRSpec flat-fielding scheme.

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#299]
The NIRSpec IDT has derived a new scheme for flat-fielding the data from all NIRSpec spectroscopic modes.  This involves a combination of wavelength-independent and wavelength-dependent reference file data, a combination of images and tables, and separate reference files for different parts of the NIRSpec system:  the fore-optics, the spectrograph, and the detectors.

See Trac ticket jwst-trac #375 for further information.

**Comment by hbushouse** [comment]
Build 7 implemented the capability to apply the new wavelength-dependent flats to spectroscopic-mode exposures (NRS_MSASPEC, NRS_FIXEDSLIT, NRS_BRIGHTOBJ, and NRS_IFU). It was discovered during implementation, however, that the IDT did not provide a way to correct imaging-mode exposures, like target-acqs. This will be implemented in B7.1.
