### ISSUE TITLE
Rule: WFS: Optical configuration?

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#315]
So far, all discussion of the WFS has been limited to how to figure pairing. However, no discussion of optical configuration has occurred. Is optical configuration important? If so, what should it be.

## References
- [PIF:  OTE Fine Phasing](https://stsci.app.box.com/s/9olpi2gz5d1q4n6n21letm47pgh7yo7g)

**Comment by hbushouse** [comment]
By optical configuration, do you mean filter selection? I would assume that exposures would need to use the same optical configuration to qualify for association, but yes someone needs to confirm this.

**Comment by hbushouse** [comment]
The observing sequence laid out in the PIF (above) indicates that the dithers are hardcoded into an individual exposure sequence, each one of which allows for only 1 commanded setting of all optical elements, including FILTER and PUPIL. So yes, the asn_generator rule should create ASN's for only those exposures that have matching values of FILTER and PUPIL, as is done for normal imaging dithers.

**Comment by hbushouse** [comment]
Is there enough info available for this mode to allow for rule implementation yet in B7.1? At least a baseline best guess to be verified with OTB data later?

**Comment by stscieisenhamer** [comment]
Without reading the PIF, the answer is yes. The current setup is based on email discussions awhile back. The only new thing is #1340, which I'm about to push out before plane boarding.
