### ISSUE TITLE
Change MSACONFL to MSAMETFL

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#388]
DMS has decided that calling the MSA data file that we get from SDP the "configuration" file has too much potential to cause confusion with the form of the MSA shutter state file that is uploaded to the telescope and also known as the "configuration" file. Hence they have decided to call the version of the file that we use within DMS and cal pipeline the MSA "metadata" file.

This means changing the keyword name MSACONFL (MSA configuration file) to MSAMETFL (MSA metadata file) in the level-1b FITS products that we use as input to the cal pipeline. Hence the core data model schema needs to be updated for this keyword name change.

And of course as soon as we merge the change to the core schema we'll all need to change the name of that keyword in any test data files we're using.

**Comment by philhodge** [comment]
Nuts.  There isn't anything "meta" about it; this file contains data.

For local testing (not regression tests), I'll assign both keywords.

Phil
