### ISSUE TITLE
IFU cube meta data updates

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#434]
Right now the cube_build step copies the meta hierarchy of the input data model (when it's fed a single input data model) to the meta data of the output cube model, while resetting/updating just a few important pieces of that meta data to match the characteristics of the output cube. When cube_build gets used to combine data from multiple exposures it should use the fitsblender utility to merge the meta data from all the inputs. A critical piece of the resulting cube meta data is the name of the input file(s) from which the cube was created. The input file names will be needed in at least one other stage of calspec3, which is the MIRI MRS skymatch step, so that it knows which input files to write the background results to. Storing and passing of these input file names needs to be sorted out.

**Comment by hbushouse** [comment]
Duplicated/superseded by #603.

**Comment by jemorrison** [comment]
The first exposure meta data is written to the IFUCube model. The full fits blending is deferred until build 7.2, This issue is tracked in #1350
