### ISSUE TITLE
Jump step crashing on ngroups=1 data

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#438]
The jump step is crashing on a CV3 test data set that says ngroups=4 in the header, but the actual dimensions of the data array only have 1 group of data. The step is already setup to skip processing if ngroups<=2, but it's using the value of the ngroups header keyword to determine that, which in this case causes the failure (because it doesn't match the actual data dimensions). Some of the other steps, like dark_current, key off of the actual data dimensions to get this kind of info. Jump should be updated to do the same thing, to make it more robust against failures of this type.

**Comment by philhodge** [comment]
I think it should fail in this case.  How do you know which is correct, 
the keyword or the data?  It's certainly possible that the keyword is 
right and the data have been truncated.

**Comment by hbushouse** [comment]
That's a good point. It would perhaps be best to have any steps that depend on knowing the value of either ngroups or nints to do a comparison of the keyword values vs the data dimensions and issue an error when they don't match. That would illuminate the existence of the problem and eliminate any other processing issues downstream.

**Comment by hbushouse** [comment]
Fixed by #458
