### ISSUE TITLE
Need TUNIT keywords for table extensions

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#473]
The photom reference tables contain a column of wavelengths, which are in turn copied into the RELSENS extensions that get added to science products by the photom step. The tables in the photom ref files and the RELSENS extension should have TUNIT keywords so that the code can determine the units for the wavelengths (as opposed to guessing based on the values).

**Comment by bernie-simon** [comment]
This problem was fixed way back with pull request #540
