### ISSUE TITLE
timeconversion+jplephem question

### ISSUE THREAD

**Issue by jhunkeler** [STScI-JWST/jwst#474]
Should we consider packaging the *.bsp file(s) jplephem requires and automatically setting up the environment to reference them? If so, are the *.bsp file(s) ever expected to change, or are they static?

**Comment by jhunkeler** [comment]
On second thought -- Perhaps including a simple CLI script to download the appropriate files would be better. It's probably not in our best interest to bloat the installation with data files that are seldom used.

**Comment by stscieisenhamer** [comment]
Just to complete the face-to-face.

The user community will not have need for this, and the current code requires running in the workflow anyways.

So, as of today, no action is required. If a user-interface is requested, we can deal with that then.

jde
________________________________
