### ISSUE TITLE
Treat NRS_BRIGHTOBJ the same as NRS_FIXEDSLIT

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#515]
EXP_TYPE = 'NRS_BRIGHTOBJ' is actually a fixed-slit mode, so the flat_field step needs to be modified to also check for this value whenever 'NRS_FIXEDSLIT' is referenced.

**Comment by nden** [comment]
There's one more EXP_TYPE value which is a fixed-slit mode - `NRS_LAMP` - in which case potentially all slits may be projected on the detector.

**Comment by hbushouse** [comment]
Does NRS_LAMP only apply to the fixed-slits or can it occur for MSA and/or IFU as well (like NRS_AUTOWAVE)?

**Comment by nden** [comment]
Quote from a JIRA ticket (CRDS-73)
```
For NRS_LAMP, all the FS should be processed if the exposure is full frame or an ALLSLITS subarray. If the readout used one of the smaller slit-specific subarrays, then only that slit should be processed.
```
I took this to mean it only applies to fixed slits.
