### ISSUE TITLE
Possibly add 1 to upper limits

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#519]
Lower and upper limits for 2-D NIRSpec IFU data are gotten from the WCS domain.  If either or both of the upper limits have `'includes_upper' = True`, that limit should be incremented by 1, so that lower and upper can be used as the limits of a Python slice.

**Comment by philhodge** [comment]
The check on 'includes_upper' is currently commented out, because at the time I added the check, the 'includes_upper' key was sometimes not present in the WCS.

**Comment by hbushouse** [comment]
Has this been resolved yet or will it be superseded by changes underway right now to switch from using domain to bounding_box?

**Comment by philhodge** [comment]
This was superseded by the changes for issue #550.  The recent changes 
(see issue #769) were intended to be consistent with #550, but I should 
do more testing to be sure that is the case.

**Comment by hbushouse** [comment]
@philhodge Safe to assume this is no longer an issue?

**Comment by philhodge** [comment]
Yes, this is no longer an issue.
