### ISSUE TITLE
IFU Cube_Build do not produce valid cube for NIRSPEC NRS2 

### ISSUE THREAD

**Issue by jemorrison** [STScI-JWST/jwst#543]
When determining the size of the final 3D spectral cube on the sky, the code loops over every slice on the detector and checks that the x,y values bounds on the detector are > 0 . However x = 0 is a valid value of a pixel in a slice since the indexing starts at 0 and not 1.  Most of the Filter/Gratting combinations for NRS1 have slices that start a x> 1, but for NRS2 all the slices start at x = 0. 
Thus for NRS2 the cube_build code thinks there are no valid slices and returns a slice of 0 (for the wavelength dimension).

**Comment by hbushouse** [comment]
Fixed by #557.
