### ISSUE TITLE
Application of the nod offset correction

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#549]
If the lower and upper extraction limits were specified in the reference file by `xstart` and `xstop` (or `ystart` and `ystop`, depending on `dispaxis`), the nod offset is currently being applied to local variables that are never copied back to the `ExtractModel` attributes that are actually used for spectral extraction.

The `get_aperture` function should be rewritten.  The nod offset needs to be applied before checking for truncation of the aperture at the edges of the input image or at the WCS domain limits.

**Comment by hbushouse** [comment]
Was this fixed by #570? If so, we can close this issue.

**Comment by philhodge** [comment]
Yes, the problem with applying the nod offset correction was fixed with 
#570.
