### ISSUE TITLE
Be more careful with extraction limits `xstart`, `xstop`, etc.

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#550]
The original parameters for the extraction limits were (and these can still be used) `xstart`, `xstop`, `ystart`, `ystop`, and `extract_width`.  The start and stop limits should be inclusive (it says so in the doc), but in some places in the code the limits are treated like a Python slice.  (IMHO, weird language-specific conventions should not be visible to users.)  Also, when `extract_width` is specified together with the lower and upper limits, `extract_width` takes precedence for the width of the extraction region (as intended), but the extraction region should be more carefully centered between the lower and upper limits.

**Comment by hbushouse** [comment]
Was this fixed by #570? If so, we can close this issue.

**Comment by philhodge** [comment]
Yes.  If xstart, xstop, ystart, ystop, and/or extract_width are 
specified by the user (e.g. in the json reference file) for the source 
extraction limits, these values will be used to create polynomial 
functions (constant functions) that satisfy the constraints that the 
start and stop limits are interpreted to be inclusive integer values, 
and extract_width (if specified) takes precedence over the start and 
stop limits.  The latter constraint simply means that the number of 
pixels in the cross-dispersion direction for extracting the source 
spectrum will be equal to extract_width.  The polynomial functions give 
actual floating-point pixel values for the limits; so for example, the 
lower and upper polynomial functions could give 14.5 and 21.5 
respectively if extract_width = 7, and that would be equivalent to 
specifying ystart = 15 and ystop = 21.
