### ISSUE TITLE
Change the independent variable to pixels

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#551]
The default value for `independent_var` is currently "wavelength".  This is used for the polynomial functions that define the source and background extraction limits.  It would not be easy for a user to specify these limits as functions of wavelength, however, partly because the wavelengths for the extracted spectra would not be known until after extracting the spectra.  While this is a very useful option (e.g. the extraction width could be linearly proportional to wavelength), the default should be "pixel" because that is easily visible when displaying or plotting the input data.

**Comment by hbushouse** [comment]
Was this fixed by #570?

**Comment by philhodge** [comment]
Yes, the default independent variable (for polynomial functions for 
lower and upper extraction and background limits) is now "pixel" rather 
than "wavelength".
