### ISSUE TITLE
NIRSpec wavelength zeropoint correction

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#556]
When sources are not centered in the spectral direction of the NIRSpec fixed and MSA slits, the will need a correction applied to the wavelength assignments. This could be included as an additional WCS transform within the assign_wcs step or implemented as a separate correction step.

An outline of the correction algorithm and the necessary reference files is included in the document ​
https://confluence.stsci.edu/download/attachments/61442267/ESA-JWST%E2%80%93SCI-NRS-TN-2016-003_wavelength_zero_point_1.pdf?version=1&modificationDate=1462212841000&api=v2. 

It involves the use of 1 reference file for each of the 5 fixed slits and 1 for any source in an MSA slit. The correction is computed as a 2D grid of delta-lambda values, which are then subtracted from the original wavelength assignments for each pixel.

(Trac #373)

**Comment by hbushouse** [comment]
Duplicated by #601.

**Comment by nden** [comment]
Closed by #1091
