### ISSUE TITLE
Populate S_REGION keyword in calibrated products

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#580]
The S_REGION keyword is intended to store the spatial footprint of an imaging observation using the VO standard STCS representation. It can be easily computed using the astropy.wcs calc_footprint method on the WCS of the image. Brian McLean suggests the following settings to make the result consistent with the way CAOM has been computing footprints for HST and other MAST products:

footprint = w.calc_footprint(undistort=True, center=True)

The resulting footprint information, which consists of the indexes of the 4 corners of the image on the sky, should then be formatted into a string value as follows:

stcs = 'POLYGON ' + str(footprint[0][0]) + ' ' + str(footprint[0][1]) + ' '  + str(footprint[1][0]) + ' ' + str(footprint[1][1]) + ' ' + str(footprint[2][0]) + ' ' + str(footprint[2][1]) + ' ' + str(footprint[3][0]) + ' ' + str(footprint[3][1])

**Comment by hbushouse** [comment]
Near the end of the set_telescope_pointing "add_wcs" function (e.g. line 163), there is a header object that now has all the basic FITS WCS keywords populated, which is all that's necessary to compute the footprint. Hence something like the following code could be inserted at that point:

```
import astropy.wcs as wcs

w = wcs.WCS(pheader, naxis=2)
footprint = w.calc_footprint(center=True)
pheader['s_region'] = 'POLYGON ' + \
    str(footprint[0][0]) + ' ' + str(footprint[0][1]) + ' ' + \
    str(footprint[1][0]) + ' ' + str(footprint[1][1]) + ' ' + \
    str(footprint[2][0]) + ' ' + str(footprint[2][1]) + ' ' + \
    str(footprint[3][0]) + ' ' + str(footprint[3][1])
```

Of course at some point in the near future this entire function will need to be updated to account for the fact that the basic FITS WCS keywords (WCSAXES, CRPIXn, CRVALn, CTYPEn, CUNITn, CDELTn, PCn_m) will no longer be in the primary header, but instead in the SCI header.

@nden @stscieisenhamer

**Comment by hbushouse** [comment]
Note that Brian McLean says that the string value for S_REGION should also contain the designation 'ICRS' (after 'POLYGON') to indicate the coord frame and that there should be a total of 5 vertices so that it forms a closed loop (i.e. just repeat the values of the 1st vertex as the 5th vertex). So the entire S_REGION string should look like:

`"POLYGON ICRS 330.91031888 -26.06384481 330.91031888  -26.08593551 330.88654109  -26.08070886 330.88654109 -26.05862129 330.91031888 -26.06384481"`

**Comment by jdavies-st** [comment]
Does this S_REGION keyword need to be populated in the level 1 files?  Because after `assign_wcs` has been run in the level 2 pipeline, the GWCS object has a `footprint` method that computes these same vertices.  And of course these will be more accurate than the linear approximation computed from the PC matrix.

**Comment by hbushouse** [comment]
Ideally the archive wants to have it populated in at all levels, with the footprint changing as appropriate to match the changing product as it goes through calibration (e.g. we need to update it after running extract2d on MOS images and after creating combined images using resample).

**Comment by nden** [comment]
Opening this as a reference since @hbushouse indicates the APT algorithm needs to be implemented.

**Comment by hbushouse** [comment]
@nden I have a copy of Tom Donaldson's Java code from the APT, if you need it for reference. This code uses the apername from the exposure to read vertices from the corresponding entry in the SIAF, and then transforms those vertices (which are in the ideal frame) into RA/Dec using the exposure's telescope pointing and roll information. Because there currently isn't any good/easy way to access the SIAF in real time (other than sqlite queries), the APT code keeps copies of the SIAF for each instrument, in xml format, in with the code that does the calculations. Of course this means those copies need to be kept up to date with the operational SIAF. But we could potentially use this same method of using a local copy of the SIAF, at least initially, in order to avoid messy ways of accessing the operational SIAF. Then when/if someone finally constructs a better real-time interface to the SIAF, we can switch to using that.

**Comment by sosey** [comment]
would it make sense just to create a new SIAF reference file which could store this information and send it to crds? Then when operational updates are made a new reference file could be pushed without a code delivery

**Comment by hbushouse** [comment]
That's another possibility and would avoid having to redeliver the jwst package every time the SIAF gets updated, which you know is going to be happening at least weekly, if not daily, during the first 6 months or so of flight. Of course the cal pipeline may get updated nearly that frequently too ...  :-(

**Comment by sosey** [comment]
:/  it's another place that's an easier query to make to get the right file and information without resorting to sqlite queries and xml, just ask crds to for the SIAF match against a file. It's a convenient way to track the SIAF changes for an instrument as well outside of the PRDS, and will help out other packages and data analysis tools like webbpsf pull down the best SIAF file to be using.

**Comment by philhodge** [comment]
I thought that we (i.e. everybody) were supposed to have real-time access to some JWST databases after launch.  Has that idea been dropped already?

**Comment by hbushouse** [comment]
There's a web-based (http) interface to the engineering database, which the pointing script already makes use of, but there's no such interface to the SIAF, despite the fact that - according to people like Brian McLean - many people have been asking for one for years.

**Comment by nden** [comment]
Just a reminder note to make sure the vertices are in the order the archive expects them to be.

**Comment by hbushouse** [comment]
I kludged up some sample code from parts we had around that shows a read from the PRD SIAF sqlite aperture file.
We have an env var (XML_DATA) that points to where the prd.db sqlite database file lives.
I extracted a few parameters for a particular aperture row that applies after a certain useafter date.
Hopefully this can give you a start on getting what you need from the PRD SIAF.
 
Questions welcome,
Mike
 
 
[mswam@dljwdmsv2 ~]$ echo $XML_DATA
/ifs/archive/dev/jwst/store/mswam/JWSTDP-2017_1-170825/defs
[mswam@dljwdmsv2 ~]$ ./siaf_read_test.py
loaded 1 table rows from /ifs/archive/dev/jwst/store/mswam/JWSTDP-2017_1-170825/defs/prd.db
RESULT={'NRS1_FULL': (2048, 2048, 1024.5, 1024.5)}
[mswam@dljwdmsv2 ~]$ cat siaf_read_test.py
#!/usr/bin/env python
#------------------------------------------------------------------------
#
# siaf_read_test.py
#
# sample code demonstrating read from prd.db sqlite file, Aperture table
#-------------------------------------------------------------------------
import sys
import sqlite3
import os
 
PRD_DB_FILE = os.path.join(os.environ['XML_DATA'], "prd.db")
 
RESULT = {}
try:
    PRD_DB = sqlite3.connect(PRD_DB_FILE)
    DB_CURSOR = PRD_DB.cursor()
    DB_CURSOR.execute(
    "SELECT Apername,XDetSize,YDetSize,XDetRef,YDetRef "
    "FROM Aperture WHERE Apername = 'NRS1_FULL' and UseAfterDate > '1/1/2010'")
    for DB_ROW in DB_CURSOR:
        RESULT[DB_ROW[0]] = (DB_ROW[1], DB_ROW[2], DB_ROW[3], DB_ROW[4])
    PRD_DB.commit()
except sqlite3.Error as err:
    print("Error :" + err.args[0])
    raise
finally:
    if PRD_DB:
        PRD_DB.close()
print("loaded {} table rows from {}".format(len(RESULT), PRD_DB_FILE))
 
#--------------------------------------------------------------------------
if __name__ == '__main__':
    # TEST CASE
    print("RESULT={}".format(RESULT))
    sys.exit(0)

**Comment by stscieisenhamer** [comment]
@hbushouse : So in lieu of a real SIAF-access solution, I take it from the given code snippet that this should be implemented on top of the currently wcs-based solution?

**Comment by hbushouse** [comment]
Yes, it should be implemented in place of the current wcs.footprint() solution, for all exposure types. By the time the pointing script gets the level-1b FITS file it should have the APERNAME populated, which can then be used to retrieve the aperture-based vertices from the SIAF.

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] Update `set_telescope_pointing` to use SIAF
- [ ] Identify `Step`'s the modify the footprint
- [ ] `Step`'s to update
    - [ ] `assign_wcs`
    - [ ] `extract_2d`
    - ???

**Comment by hbushouse** [comment]
Brian McLean indicates that the order of the vertices listed in the S_REGION string should move counter-clockwise around the perimeter for a sky orientation that has North up and East to the left (RA increasing to the left). Check the ordering of the RA/Dec values being produced to see if they need to be reversed.

**Comment by hbushouse** [comment]
The assign_wcs step updates included in #1278 cause it to fail on NRS_BRIGHTOBJ exposures in the function `update_s_region`. The assign_wcs.py module has:
```
        exclude_types = ['NRS_FIXEDSLIT', 'NRS_IFU', 'NRS_MSASPEC',
                         'NRS_LAMP', 'MIR_MRS']
        if output_model.meta.exposure.type not in exclude_types:
            update_s_region(output_model)
```
It makes sense to add NRS_BRIGHTOBJ to the list `exclude_types`, because it is a subset of the NRS_FIXEDSLIT type.

**Comment by sosey** [comment]
@hbushouse I'm also adding NRC_GRISM and NIS_WFSS to this list...

**Comment by hbushouse** [comment]
And NIS_SOSS

**Comment by hbushouse** [comment]
On 10/30/2017 Brian McLean informed us:

I’ve been informed that the VO standard changed after I implemented it all on my side and that the polygons should technically **_not_** be closed (unless there are multiple polygons in the STCS – and I think its stupid to treat them differently). The problem is that all the portal graphics overlay code assumes closure so changing that ripples through the entire AUI.
I don’t think that there will be ANY multi-polygons since you are using the SIAF apertures so my suggestion right now is that you DON’T close it and I modify the ingest code to handle it for the portal.
