### ISSUE TITLE
cube_build_io, association and ModelContainer

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#586]
From a [basecamp report by Jeb](https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/100992154/comments), it appears there is a conflict about how/when associations are opened. cube_build is expecting just the filename for the association, but in the pipeline, it has already been opened as a ModelContainer

The offending section of code in cube_build_io is lines 517-543.

@jemorrison @jdavies-st  Thoughts?

**Comment by stscieisenhamer** [comment]
Note: I have Jeb's dataset to do testing if needed.

**Comment by jemorrison** [comment]
Hi Guys,
When I travel I have to use gmail to send mail so I might of broken the
email thread.
I know what is wrong cube build - it can not read in a model container yet.
If you have an association you have you have to do something like:
strun cube_build.cfg association_name

I will add a section to the documentation on cube_build that better
describes how to run cube_build. In build 7.1 cube_build will be able to be
passes a model container.

Jane

**Comment by jdavies-st** [comment]
The level 3 processing for imaging takes an association table in the same way:

`strun calwebb_image3.cfg test_asn.json`

Internally, the level 3 imaging pipeline uses a ModelContainer, but it has the same calling api as cube_build.

**Comment by stscieisenhamer** [comment]
after @jemorrison comment, i looked at jeb's script and saw that he was explicitly calling datamodel.open. He has been informed not to do that, yet.
