### ISSUE TITLE
Task: Calibrate FGS guide mode data

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#597]
DMS Level 4 requirement 692 specifies the calibration of FGS guide mode data.

FGS guide mode data are acquired and processed differently than regular imaging exposures. The guide mode data have several different flavors:

 - Identification (ID)
 - Acquisition (ACQ1, ACQ2)
 - Track (TRACK)
 - Fine Guide (FINEGUIDE)

Each mode involves reading the FGS detector in either full-frame or subarray modes, where each exposure can consist of many integrations (NINTS>>1), with each integration containing a ramp made up of only 2 reads (NGROUPS=2). SDP will produce level-1b products for each exposure containing the raw detector readouts. The cal pipeline will need to produce level-2 products that have had only minimal processing applied to them, including forming simple differences of the two groups in each ramp, and applying bad pixel masks and flat-fielding.

Daryl Swade is producing an FGS Guide Star Pipeline document specifying the detailed characteristics of each guiding mode and the required processing to be applied.

**Comment by hbushouse** [comment]
Daryl has setup a confluence page tracking the discussion of everything involved in the FGS guide star pipeline. The page is at: https://confluence.stsci.edu/pages/viewpage.action?spaceKey=jwstdms&title=JWST+DMS+Guide+Star+Data+Products+and+Processing

There's a link at the top of the page to the latest version of the design document.

Fortunately for us, the majority of the new work involved in creating the whole pipeline is in the realm of SDP for creating the level-1 products and their contents. Level-2 products, which will be produced by the SSB cal pipeline, do not require a great deal of additional processing, much of which is already in place for calibration of science mode images.

**Comment by dmggh** [comment]
Thanks. I had just asked Daryl and he also pointed me to that page, and said he updates the document almost daily

**Comment by hbushouse** [comment]
The 3 steps that need to be applied to turn a level-1 product into a level-2 product are:

1) Apply bad pixel mask. The existing dq_init step can be used for this. All FGS guide modes use subarray readouts and the dq_init step is already setup to extract matching subarray regions from full-frame MASK reference files.

2) Compute difference images from the groups in each integration. In principle this could be done using the existing ramp_fit step, but it would need a bit of modification to accommodate all of the guide modes. Most of the modes use NGROUPS=2 and NINTS>1, in which case we just compute the difference (group2 - group1) for each integration and leave the results in a per-integration cube. The only special case is the FineGuide mode, where 4 groups are saved at the start of each integration and another 4 groups at the end of each integration. For these we must first average together the 4 groups at the beginning, average together the 4 groups at the end, and then compute the difference of those two averages (i.e. treat as Fowler sampling). So this is different than what's currently available in the ramp_fit step.

3) Apply flat-fielding. This can be done using the existing flat_field step.

The pipeline itself:

In principle we could setup of custom configurations of the calwebb_sloper and calwebb_image2 pipelines to skip all steps but dq_init, ramp_fit, and flat_field, but I think a more direct and simpler approach would be to create an entirely new pipeline module ("calwebb_guider" or "calfgs_guiding"?) that just calls the 3 steps we need.

Alternative to ramp_fit:

The existing ramp_fit can handle the data for modes with ngroups=2 and form the differences of group2 - group1, but because we have to create a new way to handle the FineGuide mode anyway, I think it's probably just as easy and direct to write a whole new step that takes the place of ramp_fit (for this pipeline) and just does the simple subtractions (or Fowler sampling subtractions) for each mode.

**Comment by hbushouse** [comment]
ID mode:

36 subarray strips, each having a size of 2048x64, will be obtained across the detector, where each strip has 8 rows of overlap with the adjoining strip. SDP will construct 2 versions of _uncal (level 1) files for this mode. The first will have the data from adjacent strips butted against one another, while the second will have the overlapping pixels combined. The pixel data array of these two types will have the following characteristics:

1) NAXIS=4, NAXIS1=2048, NAXIS2=2304 (36*64), NAXIS3=2 (ngroups), NAXIS4=2 (nints)
2) NAXIS=4, NAXIS1=2048, NAXIS2=2024, NAXIS3=2 (ngroups), NAXIS4=2 (nints)

Level 2 (calibration) processing for each of these 2 types of raw exposures will consist of:

1) Compute the difference of ngroup=2 - ngroup=1 in nint=1
2) Compute the difference of ngroup=2 - ngroup=1 in nint=2
3) Combine the results of 1 and 2 into a single image using minimum pixel value replacement

So the resulting _cal products will be 2-D with dimensions of 2048x2304 and 2048x2024.

It is still TBD as to whether the bad pixel mask and flat-field should be applied to ID mode data, due to the complications involved in sorting out the mapping of the reference files to the overlapping strips of data. Reference data could be applied easily to the butted strips form of the data if the reference files themselves were constructed in the same fashion and stored that way in CRDS.

**Comment by hbushouse** [comment]
ACQ1 mode:

Level 1 _uncal products are 128x128x2x6. Level 2 (calibration) processing should 

1) compute the group2 - group1 difference for each of the 6 integrations, resulting in a 3-D product with dimensions of 128x128x6
2) apply bad pixel map to each integration
3) apply flat-field to each integration

ACQ2 mode:

Level 1 _uncal products are 32x32x2x5. Level 2 (calibration processing should

1) compute the group2 - group1 difference for each of the 5 integrations, resulting in a 3-D product with dimensions of 32x32x5
2) apply bad pixel map to each integration
3) apply flat-field to each integration

**Comment by hbushouse** [comment]
Track mode:

Level 1 _uncal products are 32x32x2xnints. Level 2 (calibration) processing should

1) compute the group2 - group1 difference for each of the nints, resulting in a 3-D product with dimensions of 32x32xnints

Because the subarray location can move from integration to integration, and it's not clear at this time whether we'll get the location information for each integration, it will be impossible to correctly apply a bad pixel mask or flat-field image to Track mode data.

**Comment by hbushouse** [comment]
FineGuide mode:

Level 1 _uncal products are 8x8x8xnints, which corresponds to 4 initial and 4 final frames/groups for each integration, obtained using an 8x8 subarray, where the number of integrations can be very large (thousands to tens of thousands). Each integration consists of 4 initial back-to-back groups (with nframes=1), followed by 39 dropped groups, followed by 4 final back-to-back groups.

Level 2 (calibration) processing should

  1. compute a countrate image for each integration, resulting in a 3-D product with dimensions of 8x8xnints
  2. apply a bad pixel mask to each integration
  3. apply flat-field to each integration

Ideally the JCCWG and FGS team would like to use actual ramp-fitting to compute the countrate for each pixel from the 4 initial and 4 final groups in each integration. But the application of the regular ramp-fitting step also involves the use of readnoise and gain reference files, which is complicated by the use of subarrays and the off-nominal readout patterns, and also requires updates to the ramp-fit code to properly handle the 39 dropped groups in the middle of each integration.

So for the baseline implementation we will construct a new step that does the simple thing, for each integration, of averaging together the 4 initial groups, averaging together the 4 final groups, and then subtracting the initial average from the final average and dividing by the appropriate time value to produce a countrate image. This is all the FGS team had asked for originally and is what's done on-board. Doing full-blown ramp-fitting is considered an optimal upgrade.

**Comment by hbushouse** [comment]
The initial version of the new guider_cds step, which is a very simple substitute for the ramp_fit step in creating difference images for each integration, divides by the effective exposure time between the groups to put the final difference images in units of count rate (DN/sec). Asked the FGS team whether they wanted the differences images in counts or count rate. So far the response is undetermined.

Ed Nelan said:

I believe on-board processing uses the differences. On the other hand,
using the rates makes comparison of ID, ACQ1, ACQ2, TRACK (all CDS)
straight forward since these have different integration times. Oh, what to
do!

Pierre, can you think of a compelling reason for either option? My
preference is for simple difference since I think this is what the
on-board FGS FSW uses.

**Comment by hbushouse** [comment]
Fixed by #1110 (and others).
