### ISSUE TITLE
Task: Wide-Field Slitless Spectroscopy (WFSS) pipeline

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#598]
DMS Level 4 requirements 696 and 719 require the calibration of NIRISS WFSS and NIRCam grism observations.

Calibration of WFSS observations is a complicated process. A given WFSS observation will consist of both direct and dispersed exposures of the target field. The direct images must first be processed through both level-2 (calwebb_image2) and level-3 (calwebb_image3) calibrations, in order to produce a combined direct image of the field and a source catalog listing the sources discovered in the field. The source catalog is then used as one of the inputs to level-2b calibration of the dispersed exposures, in order for the assign_wcs and extract_2d steps in calwebb_spec2 to know where to extract spectra for each source. The resulting calibrated level-2b dispersed products then receive normal level-3 spectroscopic processing (calwebb_spec3).

The current idea for orchestrating this processing flow is to create a high-level pipeline module dedicated to WFSS observations (calwebb_wfss?), which will first invoke calwebb_image2 and calwebb_image3 processing for all the direct exposures within an association, and then call calwebb_spec2 and calwebb_spec3 for the dispersed exposures, using the source catalog generated by calwebb_image3 as input to calwebb_spec2.

**Comment by stscieisenhamer** [comment]
Proposed workflow:
![wfss processing](https://cloud.githubusercontent.com/assets/5658688/22653938/18a8657e-ec59-11e6-9a94-7528b4c7ccfc.png)

**Comment by hbushouse** [comment]
This is a good start, but the spec processing flow is more complicated than that. The _cat.ecsv product is used as input to level-2b processing of the grism exposures, which means it and the "spec" product definition from the ASN file first flow into calwebb_spec2 processing, which produces multiple exposure-level _cal.fits products (one for each member listed in the ASN). The ASN spec definition and the corresponding _cal.fits products then serve as input to calwebb_spec3 processing, which produces multiple source-based _s2d.fits and _x1d.fits products (one of each type for each source listed in the _cat.ecsv).

**Comment by sosey** [comment]
Question for the masses: If there can be dithers between the grism and their corresponding filter exposures, and the source catalog is made from either the single filter image, or resampled and combined filter images from the association which have their WCS information updated, then how can we ever align to the grism image? There will always be some offset between the filter and grism image unless we know how to update the WCS metadata in the grism image. This may be small, but it might also mean a noticeable offset when the trace information is added into the wcs, making the later extraction off center. 

The assumption for all of this to work is that the metadata for the wcs that comes with the observation is absolutely correct, and doesn't contain any unknown offsets which need to be solved for and added as a delta, is that the correct assumption to make for the grism data? 

From the diagram above, it appears the catalog is made from the combined direct images (direct_image1, direct_image2, direct_image3), which have been run through tweakreg and resample. The grism images have already been run through calwebb_image2 and calwebb_spec3 uses that catalog to assign the wcs regions for each spectral trace for each object in the grism image. If the direct images were tweaked, and the direct images were not observed immediately before or immediately after each of their corresponding grism images - which means we can't use their tweak information on the grism images, how can we assume they are aligned?  Let me know what logic I'm missing :)

**Comment by stscieisenhamer** [comment]
Who would like to update the diagram? I can do it based on above comments, or @sosey maybe? After getting this worked out, we can see how this and #639 mesh.

**Comment by hbushouse** [comment]
Given that the spectroscopic exposures need to have association type processing done at both level-2b and level-3 (during level-2b they need to use the source catalog from the direct images and during level-3 they need to be combined), I think the ASN_WFSS is going to need to contain 2 entries for the spectroscopic exposures. The first will be used for level-2b processing and will list _rate.fits products as the input members, with no output product specified (i.e. a "bare" list of members that don't belong to a product), and the second will then list the level-3 product, which will contain _cal.fits products as input members (as shown above). The calwebb_wfss pipeline module will need to know which sets to use when calling calwebb_spec2 and calwebb_spec3.

**Comment by stscieisenhamer** [comment]
Question: Will there ever be off-target backgrounds used here?

**Comment by hbushouse** [comment]
There's no indication of off-target backgrounds being used in the description of the WFSS processing given here: https://confluence.stsci.edu/pages/viewpage.action?pageId=61442456

Just the subtraction of the master background image (from CRDS) that will be done as part of calspec2 processing.

**Comment by sosey** [comment]
Is there no additional local background subtraction being done for each target? I think aXe used both the master sky and a local flux around the object when it extracted the pixels. 

Side question - where in this process is the flatfield being done, just before, during or after extract 2d?  If they are doing a per-pixel wavelength dependent correction then we have to get through the wcs assignment so that they can ask for the wavelength of each pixel to apply the sensitivity correction.

**Comment by hbushouse** [comment]
Local background subtraction is always an option during the extract_1d process, when 1D spectrum is extracted from 2D cutout (stamp) images.

Flatfield is being done **_before_** extracting the 2D cutout (stamp) images. The teams have determined that there's little enough wavelength dependence to the flats to allow a "normal" division of the whole image by a flat that is specific to each filter+grism combination. Right now it's located after the assign_wcs step in the calspec2 flow, but since it doesn't need wavelength info it could theoretically occur at any time before extract_2d.

**Comment by stscieisenhamer** [comment]
# Resolution
Met with @hbushouse, @sosey and later with M.Swam. SDP basically runs its processes off the contents of the associations. So, we can create all the individual associations, let SDP know what should run from which type of association, and we're good to go. @stscieisenhamer will update flow and define the necessary associations.

Bottom line: No need for an uber-pipeline.

**Comment by stscieisenhamer** [comment]
@sosey The catalog is input to calwebb_spec2. Who gets the segmentation image? spec2 or spec3?

**Comment by sosey** [comment]
@stscieisenhamer  spec2 needs the segmentation image so that I can set the size of the wcs box for extraction that spec3 will use

**Comment by stscieisenhamer** [comment]
Question: for the level2 association, since there will be two extra members, the source catalog and segmentation map, how would `calwebb_spec2` prefer to handle this? We can make a new level2 association type, such as `wfss2`, or leave it as `spec2` and let `calwebb_spec2` handle the decision making.

IMHO: since level2b processing is on an exposure-by-exposure basis anyways, the latter option is more appropriate. It will need check for **EXPTYPE** anyways, on a per-exposure basis, so having anything particularly flagged at such a high level is not much help.

**Comment by hbushouse** [comment]
I would suggest the latter as well (let calwebb_spec2 handle the decision making). The source catalog and segmentation map members should have exptype != 'SCIENCE' and hence (as of yesterday) calwebb_spec2 is already setup to not do regular processing on those members, but will still be available in the ASN meta data for steps (like assign_wcs) that need to use them.

**Comment by sosey** [comment]
Just updating the information here with what we have implemented so far. 
* assign_wcs will attach a gwcs object to the exposure which is valid for the entire image, meaning that it can use used with any source catalog positions and the gwcs object itself doesn't limit which pixels can be translated. 
* in calwebb_spec_2, the source_catalog name that's been passed with the association is added to the input_model meta data for source_catalog.filename
* the source_catalog step itself will create a catalog which contains the minimum bounding box locations for all detected objects, so the segmentation map is no longer needed for any grism steps, but I believe it's still saved as part of the drizzled direct image so it can be referenced in the future
* extract_2d takes the input_model, opens the source catalog, uses the attached gwcs object and creates bounding boxes for all objects+orders which it then uses to do the 2d extraction

**Comment by larrybradley** [comment]
@sosey The segmentation map is not saved as part of the drizzled product.  The reason for saving it was for the WFSS pipeline, but that is no longer needed because we are defining the bounding boxes in the catalog.

**Comment by stscieisenhamer** [comment]
@sosey question/clarification on the catalogs: Through the stream of issues/comments, it was decided that there is no need for both the segment map and source catalog, and that everything was going to be in the catalog. Correct?

Presuming so, for each grism exposure, I currently have a member of the association that has `exptype` as `catalog` which will point to the source catalog. Is the good or is there preference for another name?

**Comment by hbushouse** [comment]
The current design and workflow does not require the use of a special pipeline, either for the direct images or the grism images, so this is being closed.
