### ISSUE TITLE
Task: WFSS master background subtraction

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#599]
This issue takes up where Trac 352 left off https://aeon.stsci.edu/ssb/trac/jwst/ticket/352 and applies to DMS Level 4 requirements 696 and 719.

A special background subtraction step exclusive to WFSS exposures needs to be added to calwebb_spec2. Briefly, it will subtract a master background exposure, based on filter+grating combination, stored as a reference file in CRDS. The reference background image must be scaled to match the signal level in the background regions of the science exposure before doing the subtraction.

**Comment by sosey** [comment]
see https://github.com/STScI-JWST/jwst/pull/1309
