### ISSUE TITLE
Task: DMS-458 (retrieve EngDB parameters)

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#600]
DMS Level 4 requirements 256 and 458 state that the calibration pipeline must access the Engineering Database (EngDB) and retrieve values of engineering mnemonics from it, to use during calibration processing. Given that the cal pipeline currently does not need any engineering parameters to perform calibration, but waiving, removing, or putting a lien on a Level 4 requirement requires and wastes so much time and effort, we will therefore create a new calibration step ("dms458") that will do nothing but retrieve some parameter value from the EngDB and print its value in a log message. This cal step will not be used in any of our current pipelines. It will simply exist for the purpose of I&T to run it from the command line and verify requirements 256 and 458.

**Comment by stscieisenhamer** [comment]
If allowed 1FTE month, I invite all developers to suggest features for this most valuable of calibration steps.  Keyword: Epic


-------- Original message --------

**Comment by hbushouse** [comment]
I was thinking more along the lines of 1 FTE _**day**_.

**Comment by stscieisenhamer** [comment]
I get it! Time constraint will make it more of a challenge!


-------- Original message --------

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] Rename step to `engdblog`
- [ ] Parameters
    - `mnemonics`: List of mnemonics to retrieve
    - `stime`: Start time to retrieve
    - `etime`: End time to retrieve
    - `verbosity`: How much to output. Values are
        - `initial`: Echo only the initial value for each mnemonic
- [ ] Outputs
    Log lines of each requested value for each requested mnemonic.

# Development
- [ ] Understand how to write a step
- [ ] Tests
- [ ] Code
- [ ] Review
- [ ] Merge
