### ISSUE TITLE
Task: calwebb_spec3 pipeline module

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#604]
This is a continuation of Trac 359 https://aeon.stsci.edu/ssb/trac/jwst/ticket/359

A calwebb_spec3 pipeline module needs to be constructed to implement the level-3 spectroscopic processing steps, which are outlined at https://confluence.stsci.edu/display/JWSTCC/CALSPEC3

**Comment by hbushouse** [comment]
The steps included in the B7.1 version of calspec3 are to be:
- skymatch (the MIRI MRS background matching version)
- outlier_detection
- resample_spec (for non-IFU data)
- cube_build (for IFU data)
- extract_1d

The high-level flow should follow this arrangement:

- Load the contents of the input ASN file
   - This implies either first loading the ASN object and then loading all the members into a 
ModelContainer, or just directly loading all the members of the ASN into a ModelContainer
- Convert, when necessary, exposure-based inputs to source-based inputs using the exp_to_source tool
   - This will be done only for cases in which multiple sources are defined, which includes EXP_TYPE's NRS_MSASPEC, NRC_GRISM, and NIS_WFSS. The operation basically transforms MultiSlitModels into MultiProductModels (I think we might need a better name)
   - All others will remain in exposure-based mode
- If conversion from exposure-based to source-based has taken place, all subsequent steps operate on one source-based model at a time
- If EXP_TYPE='MIR_MRS', call the MIRI MRS background matching (skymatch) step
   - The input here will always be multiple ImageModels. Never a MultiSlit or source-based model.
- Call outlier_detection
   - The input can take two different forms:
      - A single source-based model, in which case the detection is done by comparing the data in the various exposure instances contained in the source-based model
      - Multiple Image or MultiSlit models, each of which contain a single exposure instance of data (e.g. a MultiSlitModel with a single slit). The detection is done by comparing the data across the multiple input models.
- Save the outlier_detection results as level-2c products
- If EXP_TYPE='MIR_MRS' or 'NRS_IFU', call the cube_build step
   - The result is saved as an 's3d' product, which needs to have blendheaders applied to it
- For other EXP_TYPE's, call the resample_spec step
   - The result is saved as an 's2d' product, which needs to have blendheaders applied to it
- Call the extract_1d step
   - Uses either the 's3d' or 's2d' product (whichever was created) as input
   - The result is saved as an 'x1d' product. The blendheaders content in the input should be carried along to the x1d product.

**Comment by stscieisenhamer** [comment]
@hbushouse test data?

**Comment by hbushouse** [comment]
:rofl: Surely you jest!

But seriously folks, I recently got my hands on some realistic simulated NIRSpec MSA exposures. And I know that @jemorrison has NIRSpec IFU and MIRI MRS test cases. Will do some digging for others.

**Comment by jemorrison** [comment]
I will gather up some test data. I can get MIRI ground and simulated and 
I will ask NIRSPEC for simulated dithered data.
Where do you want me to put this data. And do you want uncal data or 
only data that has already been processed through
calspec2 ?
Jane

**Comment by stscieisenhamer** [comment]
@jemorrison All of it would be grand!  There may be some place more appropriate, but I would say 

/grp/jwst/ssb/test_build7.1/development/miri

**Comment by stscieisenhamer** [comment]
# Implementation

- [ ] Primary input: asn only or all of the above
- [ ] multi-source vs. single-source
- [ ] saving intermediates
- [ ] pipeline config

**Comment by jdavies-st** [comment]
I checked with Maca Garcia Marin about simulated test data for MIRI long slit, but nothing is available now, and probably no plans.

She _did_ point me to dithered MIRI imaging sims (horray!) and dithered IFU/MRS ones.  Not sure if these are the same ones you have @jemorrison.

**Comment by stscieisenhamer** [comment]
## Question
The `mrs_imatch` step does a cube_build. Now there are two cube_builds. Is this an issue? Should we be looking to streamline this?

**Comment by hbushouse** [comment]
There aren't two different versions of cube_build, it's just that the mrs_imatch step is calling cube_build from within itself in order to build individual exposure-level cubes that it needs to do its matching. Cube_build will also be called in this fashion (eventually) from within the outlier_detection step. And then finally, cube_build will be called from calspec3 to build the actual level-3 cube products.

**Comment by stscieisenhamer** [comment]
Right, do all the builds work on the same input? Or is each build dependent on the result of the previous step?  I.e., is each build building from different data?

**Comment by hbushouse** [comment]
The mrs_imatch step uses the original level-2b inputs to calspec3 as its inputs. The updated outputs of mrs_imatch are then used as input to outlier_detection and the updated outputs from outlier_detection are used as input to the final call to cube_build. Note that even though mrs_imatch and outlier_detection are building cubes internally to do their work, those cubes are only used internally. The updated outputs that get passed back up to calspec3 from each of those two steps are still in the form of 2D level-2b-like images (they've just had either some meta data updated or DQ flags updated). They are not passing back cubes to be used in subsequent steps.

**Comment by stscieisenhamer** [comment]
Actually, re-reading the last comment while not attending a meeting, the question still stands: So, when a cube is rebuilt, it is rebuilt from data that only has had meta/quality flags updated. Otherwise, is the cube built in each step the same cube(s)? If so, could one simply build the cube and pass it in to each step? Or does the meta/quality affect the cubes themselves?  I.e. the DQ gets embedded in the cube and its just easier to rebuild the cube than trying to update DQ within an already built cube.

Yes, I'm beating a dead cube...

**Comment by hbushouse** [comment]
It occurs to me now that the mrs_imatch step currently only computes background offsets and stores the results as meta data in the level-2b models that are passed back from it. It doesn't actually apply (subtract) those offsets, because of the way the various noise model routines work in the subsequent outlier_detection step. The outlier_detection step uses the background offset meta data (or it should at least - I don't know if it is now) as part of its calculations. So then when outlier_detection is done, we have level-2b models that have had their DQ arrays updated and have background offsets stored as meta data. At some point those background offsets need to actually get applied. Should they get applied by the calspec3 pipeline module before sending all the models into cube_build, or should something be added to cube_build to apply them, if they exist? How does this work in calimage3 when the skymatch step has been applied, such that the models going into the resample step have background offsets stored in their meta data? Do the background offsets get applied before going into the resample step or does the resample step look for them and apply them if they exist? We definitely want to have those background offsets removed before cube_build creates the final cube.

**Comment by hbushouse** [comment]
Closed, at least for B7.1 work, by #970 #1000 #1015 and #1047.
