### ISSUE TITLE
Task: MIRI MRS background matching and subtraction

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#605]
This is a continuation of Trac 345 https://aeon.stsci.edu/ssb/trac/jwst/ticket/345

This calibration step will be part of the calwebb_spec3 pipeline and will be used to match and subtract background signal from an ensemble of MIRI MRS exposures. Links to some documentation can be found in the Trac ticket.

**Comment by mcara** [comment]
Done in https://github.com/STScI-JWST/jwst/pull/989 using an optimized method.

Also, ``cube_skymatch`` - see https://github.com/STScI-JWST/jwst/pull/291 - presents the original method developed by the scientists of pair-wise image matching. This method has not been updated to work directly with 2D images and build cubes as necessary (it expects to receive cubes and 2D images) but this can be implemented if desired.

**Comment by hbushouse** [comment]
Closed #605 via #989.
