### ISSUE TITLE
Task: Finish implementation of cube_build for build 7.1

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#614]
All remaining aspects of the cube_build step necessary for processing NIRSpec IFU and MIRI MRS data must be completed. This includes the application to single exposures in the calwebb_spec2 pipeline and to multiple exposures in the calwebb_spec3 pipeline.

This is a carryover of Trac 360: https://aeon.stsci.edu/ssb/trac/jwst/ticket/360

Issues for build 7.2 were pulled out and put into issue #1350

**Comment by jemorrison** [comment]
Additional features cube_build needs:
1. Create  a cube build default parameter reference files that contain the default information necessary to build IFUcube for each band. Add these files to CRDS and read them in cube_build.  A separate reference file is needed for MIRI and NIRSPEC.
2. For MIRI create a resolution reference files that holds information on the psf and lsf for each MIRI band. Add this reference file to CRDS and read this file in cube_build. 
3. The default IFUCubes created from an association are per band. If an association or datamodel contains several bands (which will always be true for MIRI data) then in cube_build loop over each band and create a IFUcube for that band.  However, keep input options in cube_build to override this and create IFUCube comprised of several bands. 
4. Create 'single' IFU cubes to support skymatching and outlier detection. These types of IFU cubes are single exposure, single band cubes mapped to a common output cube. The WCS of this common output is built from several dithered files of the same band.
5. Add the ability to "blot" an IFUcube image back to the detector space to support outlier detection. First a set of "single" IFU cubes are built from a common WCS . Each "single" IFU cube is created from a single exposure, single band. The outlier detection step takes the set of single IFUcube and creates a median image (possibility also sigma clipped). This median image and the original images (which are the output from calspec2) are the input to 'blot_cube.py'. Each original image is "blotted" (mapped from the common IFU cube space to the detector space). For MIRI the blotting is done 1 channel at a time and it is left to the outlier rejection tool to stick the two blotted channels together on the detector.
6. Add the necessary WCS information to create alpha-beta type cubes for MIRI. 
7. After sky match has been run the information about the background sky is written to the header. The cube_build code needs to read this information and apply a correction to the data.    
8. Add more diagnostic information  about holes that exist in the IFUcube
9. Create a rules file for fits_blender to combine the input information in a reasonable way in a table that is written out of the IFU Cube product. 
10. Update all the documentation
11. Add the option to create a non-linear wavelength dimension. This could be in the form of a wavetable (which requires an update to gwcs). This option could be put off until build 7.2
12. A feature that the MIRI instrument team would like is create IFUCubes in the alpha-beta coordinate system from dithered data. This feature will likely not be implemented until build 7.2

**Comment by hbushouse** [comment]
Closed, at least for B7.1 work, by many PR's, including #557 #565 #571 #939 #1085 and #1239.
