### ISSUE TITLE
Task: Data products for B7.1

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#623]
## Definition
This task consists of several main pieces of work:

- Define any new types of data products that will come out of the B7.1 cal pipeline
- Create data models for the new types of products
- Create examples of all new types of products from B7.1, where "new" is defined as a type that the rest of DMS has not yet seen (even if we may have been creating them for a while already)

The last item can be done by either doing a "one off" creation of a static example data file for each product type or by rigging up skeletons of the pipeline modules (e.g. calwebb_tso3) that will be creating those products such that they create dummy (i.e. zero-filled) output files of the correct type when the skeleton pipeline module is executed.

The rest of the downstream DMS subsystems would like to have examples of all types of B7.1 data products by mid-2017 (June-July) in order to give them time to finish their B7.1 development work.

## Resources
- [Science Data Products](https://confluence.stsci.edu/pages/viewpage.action?spaceKey=SSB&title=Science+Data+Products)

**Comment by stscieisenhamer** [comment]
# Implementation
## In Development
- [ ] calwebb_coron3
- [ ] calwebb_tso3

## Future
- [ ] calwebb_spec3
- [ ] calwebb_wfss

**Comment by stscieisenhamer** [comment]
The collecting of products will be in the directory
```
/grp/jwst/ssb/test_build7.1/examples_for_dms
```

**Comment by hbushouse** [comment]
All data product formats, contents, and file name syntax have been defined and documented at https://confluence.stsci.edu/display/SSB/Science+Data+Products. Example files were created through the use of either actual pipeline processing or generation of fake data products, using a set of python notebooks developed by @stscieisenhamer @stsci-hack and @hbushouse. The notebooks and resulting example data products were placed in the directory tree at /grp/jwst/ssb/test_build7.1/examples_for_dms/ and made available to the other DMS subsystems for their use in testing archiving, etc.
