### ISSUE TITLE
Add new NIRCAM SUBARRAY values

### ISSUE THREAD

**Issue by jaytmiller** [STScI-JWST/jwst#624]
Two reference file deliveries from the NIRCAM team made on Nov 28, 2016 and post-poned until now had an associated spreadsheet that defined a plethora of new SUBARRAY values.  Append them to the value list core.schema.yaml.

The complete list to be merged from the spreadsheet is:

FULL
SUB160B1
SUB160B2
SUB160B3
SUB160B4
SUB160BLONG
SUB160PA3
SUB160PALONG
SUB160PB1
SUB160PBLONG
SUB320A335R
SUB320A430R
SUB320ALWB
SUB320B1
SUB320B2
SUB320B3
SUB320B335R
SUB320B4
SUB320B430R
SUB320BLONG
SUB32TATS
SUB32TATSGRISM
SUB400PA3
SUB400PALONG
SUB400PB1
SUB400PBLONG
SUB640A210R
SUB640ASWB
SUB640B1
SUB640B2
SUB640B210R
SUB640B3
SUB640B4
SUB640BLONG
SUB640BLWB
SUB640BSWB
SUB64FP1A
SUB64FP1B
SUB64PA3
SUB64PALONG
SUB64PB1
SUB64PBLONG
SUB8FP1A
SUB8FP1B
SUB96DHSPILA
SUB96DHSPILB
SUBFSA210R
SUBFSA335R
SUBFSA430R
SUBFSALWB
SUBFSASWB
SUBGRISM128LW
SUBGRISM256LW
SUBGRISM64LW
SUBNDA210R
SUBNDA335R
SUBNDA430R
SUBNDALWBL
SUBNDALWBS
SUBNDASWBL
SUBNDASWBS
SUBNDB210R
SUBNDB335R
SUBNDB430R
SUBNDBLWBL
SUBNDBLWBS
SUBNDBSWBL
SUBNDBSWBS

Duplicates of existing values need to be removed,  whatever remains needs to be added.

**Comment by jaytmiller** [comment]
[NIRCam_SIAF-OSS_Summary_20161117_MMA.xlsx](https://github.com/STScI-JWST/jwst/files/717751/NIRCam_SIAF-OSS_Summary_20161117_MMA.xlsx)

**Comment by jaytmiller** [comment]
I have a forthcoming pull request for this.

**Comment by nden** [comment]
In most cases distortion of subarrays will be retrieved from the full frame distortion reference files. There's a small number of coronagraphic subarrays which need to be calibrated individually. The NIRCAM team will provide a list of those subarrays in about a week.
