### ISSUE TITLE
GLS option fails with bitwise comparison between int32 and uint32

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#632]
In function ``gls_ramp_fit`` in ramp_fit.py, the ``temp_dq`` array is created with data type ``np.int32``, but a bitwise comparison is done with array ``dq_int``, which is ``np.uint32``.  ``temp_dq`` should be ``np.uint32`` as well.

**Comment by hbushouse** [comment]
Fixed by #680.
