### ISSUE TITLE
Pipeline missing steps

### ISSUE THREAD

**Issue by ccossou** [STScI-JWST/jwst#633]
I tried to see the help message for all the steps available and encountered an error for 3 steps:

- calniriss_ami3.cfg
- skymatch.cfg
- tweakreg.cfg

For calniriss_ami3.cfg for instance, the error is:
AttributeError: 'module' object has no attribute 'NirissAmiPipeline'

I did not found any trace of such an error in the issues so I created one. 

Christophe COSSOU, Mirisim team, IAS, France

**Comment by hbushouse** [comment]
The calniriss_ami3.py and calniriss_ami3.cfg were removed from the repo in a recent merge (#629), because they are now obsolete, having been replaced by the calwebb_ami3.py and calwebb_am3.cfg modules. The obsolete files were inadvertently left in the Build 7 delivery.
