### ISSUE TITLE
Velocity Aberration Divide by Zero

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#645]
As reported in [Discrepancy Report #003857](https://www.ess.stsci.edu/prsystem/servlet/prbrowse/dr.3857):
```
There was a velocity aberration divide by zero error while processing NIRCam
Darks.  The error is below.

Files:
w88500022001_07101_00001_nrca1_uncal.fits
jw83500002001_02104_00001_nrcb3_uncal.fits


set_velocity_aberration.py
/ifs/int/jwst/info/jwowlmgr/build7/paths/sdp/fits/jw83500002001_02104_00001_nrcb
3_uncal.fits Traceback (most recent call last): File
"/ifs/int/jwstd/pipeline/build7/pkgs/miniconda3/envs/jwstb7rc7/bin/set_velocity_
aberration.py", line 4, in
__import__('pkg_resources').run_script('jwst==0.7.0rc7',
'set_velocity_aberration.py') File
"/ifs/int/jwstd/pipeline/build7/pkgs/miniconda3/envs/jwstb7rc7/lib/python2.7/sit
e-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in
run_script File
"/ifs/int/jwstd/pipeline/build7/pkgs/miniconda3/envs/jwstb7rc7/lib/python2.7/sit
e-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499,
in run_script File
"/ifs/int/jwstd/pipeline/build7/pkgs/miniconda3/envs/jwstb7rc7/lib/python2.7/sit
e-packages/jwst-0.7.0rc7-py2.7-linux-x86_64.egg/EGG-INFO/scripts/set_velocity_ab
erration.py", line 183, in add_dva(filename) File
"/ifs/int/jwstd/pipeline/build7/pkgs/miniconda3/envs/jwstb7rc7/lib/python2.7/sit
e-packages/jwst-0.7.0rc7-py2.7-linux-x86_64.egg/EGG-INFO/scripts/set_velocity_ab
erration.py", line 168, in add_dva ra_ref, dec_ref) File
"/ifs/int/jwstd/pipeline/build7/pkgs/miniconda3/envs/jwstb7rc7/lib/python2.7/sit
e-packages/jwst-0.7.0rc7-py2.7-linux-x86_64.egg/EGG-INFO/scripts/set_velocity_ab
erration.py", line 99, in aberration_scale cos_theta = dot_prod / speed
ZeroDivisionError: float division by zero
```

**Comment by hbushouse** [comment]
I'm guessing this is most likely due to the jwst velocity keywords (jwst_dx, jwst_dy, jwst_dz) being zero in the header of the level-1b file on which the script is run, possibly due in turn to lack of coverage in the EngDB for these exposures.

**Comment by philhodge** [comment]
I don't see from the traceback how set_velocity_abberation.py is called, i.e. where it gets its arguments.  The first three arguments are the components of the velocity, and if they're populated with zeros, the speed will also be zero.

**Comment by hbushouse** [comment]
The top-level script is called from within SDP with an existing level-1b FITS file as the argument, using the values of the header keywords jwst_dx, jwst_dy, and jwst_dz for the x,y,z velocities.

**Comment by philhodge** [comment]
The keyword values in jw88500022001_07101_00001_nrca1_uncal.fits are:

JWST_DX =                  0.0 / X component of JWST velocity (km/sec)
JWST_DY =                  0.0 / Y component of JWST velocity (km/sec)
JWST_DZ =                  0.0 / Z component of JWST velocity (km/sec)

The speed should be about 30 km/s.  For testing purposes, you could just set one of these keywords to 30.

**Comment by stscieisenhamer** [comment]
What should the behavior of the script be in this situation? I presume just settings of zeros with appropriate warning messages. SDP doesn't like when things exception.

I can fix when decided.

**Comment by hbushouse** [comment]
The script should also be updated to be robust against this condition. Check for speed=0 before trying to use it in division, issue a warning, and set the outputs to suitable defaults like zero (for the offsets) and one (for the scale factor).
