### ISSUE TITLE
extract_1d should not do flux calibration for IFU

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#648]
The `extract_1d` step applies flux calibration to the count rate values in the net column (using the RELSENS extension of the input file) in order to populate the flux column.  For both MIRI and NIRSpec IFU cubes, however, the data values will already be in flux units; see #611 and #647.  The `extract_1d` step should be modified to not attempt to apply flux calibration to any IFU data; instead, the net column should be copied directly to the flux column.

**Comment by hbushouse** [comment]
We'll need to wait until all of the details of the IFU flux calibration scheme are sorted out, but it may end up being the case that the pixel area map and relative response conversion factors that get attached by the photom step and then applied at the beginning of the cube_build step only put the pixel values onto the same "zeropoint" (i.e. remove pixel-to-pixel differences in sensitivity, area, etc.), but still aren't in units of full physical flux (or surface brightness). An additional scalar conversion factor may be needed to do that last step. The scalar factor would be stored in a header keyword of the science data by the photom step. If it does not get applied by cube_build, when it applies the other corrections/conversions, then extract_1d may need to apply that last step, as it does now with the RELSENS function.
