### ISSUE TITLE
Association tasks for Build 7.1

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#654]
All Build7.1 issues for Associations can be [viewed here](https://github.com/STScI-JWST/jwst/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Aassociations%20milestone%3A%22Build%207.1%22%20).

**Comment by hbushouse** [comment]
Mark K. indicates that we should start getting OTB-generated example data by the end of March. So hopefully this work can commence April-May.

**Comment by hbushouse** [comment]
Aforementioned OTB test data is now predicted to arrive in the Dec. 2017 time frame, so this issue is being moved to the B7.2 milestone.

**Comment by stscieisenhamer** [comment]
Closing since all remaining tasks have been pushed to Build 7.2
