### ISSUE TITLE
Rule: Time Series

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#656]
Time-series will be defined for many observing modes, including MIRI LRS slitless, NIRSpec fixedslit, NIRISS SOSS, NIRCam time-series imaging, and NIRCam time-series grism spectroscopy. Time-series rules will likely be very similar, if not identical, to the rules for dithers (just look for all the exposures for a given target using the same instrument setup).

As definitions are made for each mode, issues will be created.

# Resources
- All TSO's will have an IS_TSO column with a boolean indication ([JSDP-214](https://jira.stsci.edu/browse/JSDP-214))

# Implementation
- [x] Constraints
    - [x] `EXP_TYPE` _not needed; all based on `is_tso`_
        - `mir_lrs-slitless`
        - `nis_soss`
        - `nrc_tsimage`
        - `nrc_tsgrism`
        - `nrs_brightobj`
    - [x] `IS_TSO` is `True`
        _Possible that this is the only flag needed._
- [x] Level2
    - [x] Input and output products should be the integrations, where `ints` is part of the suffix
- [x] Level3
    - [x] Association type [`tso3`](http://ssb.stsci.edu/doc/jwst_dev/jwst/associations/jwst_conventions.html#association-types)
    - [x] Inputs are the `calints` from Level2b
- [x] test cases

# Issues

## Exposure chunking
From @hbushouse:

> It's possible that many, if not most, TSO observations will consist of a single, but VERY long exposure, so we'd be building an ASN table with just one exposure. Once SDP implements "chunking" of raw TSO data into multiple level-1b products to keep file sizes down, then we'd have to create ASN's that include those multiple files as members. I don't recall if anyone has yet thought about file naming syntax for those level-1b products that will come from a single exposure (obviously need something to get file name uniqueness).

**Comment by stscieisenhamer** [comment]
@hbushouse please to review the initial comment for implementation details. I'm presuming that for the Level2 work, we need this in ASAP for Build7.1?

**Comment by hbushouse** [comment]
Made a couple minor edits to the initial comment (mostly just typos, not errors). Yes, we should have Level2 ASN's available for Build7.1, assuming that DMS is now relying on ASN's for doing all level-2b processing.

**Comment by stscieisenhamer** [comment]
About whether the `is_tso` flag will always be present or not. From R.Hawkins:

> Yes, that’s exactly right. The time_series_observation is populated for all implicit templates (as they’re forced to have the SR) as well as all other usages of the SR (templates that are *allowed* to be TSO and that the observer chooses to indicate as such).
