### ISSUE TITLE
individual steps saved relative to config file, not working directory

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#671]
Not sure if an issue or not, but just noticed that if one has edited a step/pipeline config to save intermediate steps, the path of those files are relative to the location of the config file, and not relative to the working directory.

For example, given a config `mypipe.cfg` which is sloper but with `output_file` specified for one or more steps, and the following command is used:
```
$ strun path_to_mypipe/mypipcfg input.fits
```
will save the intermediate files in `path_to_mypipe` and not the current working directory.

This behavior may befuddle or even frustrate, users. Thoughts?

**Comment by hbushouse** [comment]
You've got it wrong: change the word "may" in the last sentence to "does." I've seen this one rear its ugly head a few times in the past. I vote that the behavior be changed to always follow the path of the input file, unless overridden by the user specifying a path within the output_file argument or the output_dir argument.

**Comment by stscieisenhamer** [comment]
Resolved by #678
