### ISSUE TITLE
TEAL promo messages on import

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#675]
I've noted this for awhile, but was wondering if this is intentional or not:
```
> from jwst.pipeline import SloperPipeline
The following task in the fitsblender package can be run with TEAL:
                                  blendheaders
```
A good-to-know, but wondering if having this sprinkled throughout users outputs won't bother the users a bit.

Note: This is both in the Build7 and master installs.

**Comment by sosey** [comment]
Is JWST even supporting teal? That would confuse them more

**Comment by hbushouse** [comment]
The calwebb_image3 pipeline module uses blendheaders to collect all of the meta data from association members, so the message is probably occurring as the fitsblender package gets imported when all the pipeline modules get imported by __init__ in the pipeline sub-package.

**Comment by stscieisenhamer** [comment]
Haven't seen in awhile and have a nagging feeling of seeing some other issue that resolved this flying by. Ergo, closing.
