### ISSUE TITLE
Consider pipeline output standards

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#678]
Issue: Given the command and configuration below, there will be three output files using two different naming schemes located in three different directories. Discussion is needed on how to make this more consistent, or a bit more transparent.

calwebb_sloper.cfg:
```
name = "SloperPipeline"
class = "jwst.pipeline.SloperPipeline"
save_calibrated_ramp = False

    [steps]
      [[dq_init]]
        config_file = dq_init.cfg
      [[saturation]]
        config_file = saturation.cfg
      [[ipc]]
        skip = True
      [[superbias]]
        config_file = superbias.cfg
      [[refpix]]
        config_file = refpix.cfg
      [[rscd]]
        config_file = rscd.cfg
      [[lastframe]]
        config_file = lastframe.cfg
      [[linearity]]
        config_file = linearity.cfg
      [[dark_current]]
        config_file = dark_current.cfg
      [[persistence]]
        config_file = persistence.cfg
      [[jump]]
        config_file = jump.cfg
        output_file = test_jump.fits
      [[ramp_fit]]
        config_file = ramp_fit.cfg
```
Command:
```
strun cfgs/calwebb_sloper.cfg jw82600001001_02101_00001_nrca1_uncal.fits --output_file ./results/cmd_out.fits
```
Files produced:
- ./cfgs/test_jump.fits
- ./results/cmd_out.fits
- ./test_rateints.fits

**Comment by stscieisenhamer** [comment]
Related to #671

**Comment by hbushouse** [comment]
This is a messy issue that does need some discussion. It's simple when you're just concerned about a single step that has a single output. But as soon as you start dealing with pipelines that have one or more outputs, and those pipelines include steps that can save intermediate results, it gets messy fast. Not so much in terms of _where_ (what directory) to save the files, but mainly in terms of what names to use for them, especially if the user has also specified a --output_file value. For the sloper pipeline, for example, if the user has specified output_file, we assume that name will apply directly to the final rate-type product and overrides the pipeline composing a name for what would be the _rate.fits file. But then what should the pipeline name the _rateints.fits product produced by the ramp_fit step (or should the saving of that product be moved out of the ramp_fit step and let the pipeline handle it?). And if save_calibrated_ramp is True, what should the pipeline name that intermediate product? For the _rateints file, do we take the user's value in output_file and just append "_rateints" to the end of the root name? Or do we look for and try to replace any suffix that was included in output_file? Same questions for the _ramp.fits file.

It gets super messy for some of the level-2b and level-3 pipelines (calwebb_spec2, calwebb_coron3, calwebb_ami3, ...), some of which produce one or more calibrated products for every input member, and others produce 2, 3, or 4 different stages of combined products. What does output_file mean in a situation like that? (right now it's completely ignored).

**Comment by stscieisenhamer** [comment]
# Strawman Proposal
A possible soluation is as follows. Define three options:

`--output_dir='./'`
Pretty much as defined. However, its value is passed down to substeps, so all substeps would use this directory, unless overridden by a substep option.

`--output_file='{root}{type}'`
The name of the output file, or files. The trick here is what is seen in the default: use string replacements to construct the name.  `{root}` is replaced with the input file name minus the DMS type, such as `_uncal`. `{type}` is replaced with whatever this step wants to put in there. If there are multiple outputs of different type, then `{type}` is replaced with each of those types.

Also note that if `--output_file` is specified, but without a value, the files will be created using the given default

`--save_substeps`
If specified, save all the sub-steps, using the given `--output_dir` and `--output_file` options.

## Use Cases
Given the following pipeline with two steps and the specified types:

![pipeline](https://cloud.githubusercontent.com/assets/5658688/22597470/b5b16c98-e9fd-11e6-8806-fde8a143c2f6.png)

### Case 1: Defaults
`strun pipeline.cfg jw82600001001_02101_00001_nrca1_uncal.fits`

Outputs:
```
./jw82600001001_02101_00001_nrca1_pipe-ext1.fits
./jw82600001001_02101_00001_nrca1_pipe-ext2.fits
```
### Case 2: Change directory and save all steps
`strun pipeline.cfg jw82600001001_02101_00001_nrca1_uncal.fits --output_dir='./results' --save_substeps`

Outputs:
```
./results/jw82600001001_02101_00001_nrca1_pipe-ext1.fits
./results/jw82600001001_02101_00001_nrca1_pipe-ext2.fits
./results/jw82600001001_02101_00001_nrca1_s1-ext1.fits
./results/jw82600001001_02101_00001_nrca1_s2-ext1.fits
./results/jw82600001001_02101_00001_nrca1_s2-ext2.fits
```

### Case 3: Change directory, name, and save all steps
`strun pipeline.cfg jw82600001001_02101_00001_nrca1_uncal.fits --output_dir='./results' --output_file='myname{type}' --save_substeps`

Outputs:
```
./results/myname_pipe-ext1.fits
./results/myname_pipe-ext2.fits
./results/myname_s1-ext1.fits
./results/myname_s2-ext1.fits
./results/myname_s2-ext2.fits
```

### Case 4: Save in directories by exposure name, given the outputs generic names, and using the config
`pipeline.cfg`:
```
output_dir = ./{root}
output_name = pipe{type}

    [steps]
        [[step1]]
            output_name = step1{type}

        [[step2]]
            output_name = step2{type}

```
`strun pipeline.cfg jw82600001001_02101_00001_nrca1_uncal.fits`

Outputs:
```
./jw82600001001_02101_00001_nrca1/pipe_pipe-ext1.fits
./jw82600001001_02101_00001_nrca1/pipe_pipe-ext2.fits
./jw82600001001_02101_00001_nrca1/step1_s1-ext1.fits
./jw82600001001_02101_00001_nrca1/step2_s2-ext1.fits
./jw82600001001_02101_00001_nrca1/step2_s2-ext2.fits
```

### Case 5: Change name and User shooting foot
The issue here is that `{type}` is not used in the filename. Presumably warnings/errors could be produced in this situation, but the code obeys the user:

`strun pipeline.cfg jw82600001001_02101_00001_nrca1_uncal.fits --output_name='myout' --save_substeps`

Outputs:
```
./myout.fits
```

**Comment by stscieisenhamer** [comment]
# Coding Issues

In general, the `stpipe.run` call, which wraps all steps/pipelines, seems to have all the mechanisms needed to handle the strawman proposal, minus the templating. It simply appears that as development has progressed, the core routine was not updated and other, varying, solutions took hold. As such, the current state appears to be:

- `stpipe.run` can handle returning and saving multiple results. However, this facility does not seem to be used by any implemented step/pipeline. The most likely reason is that having multiple outputs breaks the "pass output from one step as input to next step" paradigm, or at least makes it a bit more complicated.
- modules implemented as `Pipeline` have an extra method, `setup_output`, that encapsulate the naming requirements for the pipeline and its one output. However, this concept is not implemented in any of the modules implemented as `step`.
- `setup_output` also handles output directory path, but only path taken from the location of the config file; it doesn't use `output_dir`
- A `stpipe.save_model` method does incorporate the workflow naming scheme and honors the `output_dir` parameter. However, it's use throughout the pipeline/step code breaks the `stpipe.run` model.
- As implied by the above, `stpipe.run` and `stpipe.save_model` both implement a logic on saving models, but the logic differs.
- There are flags to save intermediate results from steps. This is unclear why as if an output is specified for the step, it will save.
- There is suspicion that there are is another definition of "intermediate results". Currently, this is in reference to results from steps, but there is probably also a definition of intermediate results within a step, which is why there is such a `stpipe.save_model` in the first place. 

### Solutions
The most direct solution is refactoring the logic of `stpipe.run`, `stpipe.save_model`, and `setup_output`, so at least there is common code on naming, output directory, etc. This would take care of 95% of the issues. The `step` model is still broken with-respect-to the random saving of results, but the saving logic would at least be consistent.

Ultimately, the following could be considered:
- If there are intermediate results that are produced within a step, ask the serious question: if those results are important, consider making the logic producing said results a defined step.
- Create a class, StepResults, that handles the possibility of multiple results and provides tools to still enable the pipeline-ness of passing output-to-input of steps transparent.

**Comment by stscieisenhamer** [comment]
# Implementation
## Defaults
Right now, there are three "defaults" in play:

1.  `Step` puts outputs in the same directory as the input
2. Major pipelines, through the `setup_output` method, puts the output in the same directory as the config file
3. `Step.save_model` puts outputs in the current working directory

It has been decided that the great simplification should occur: Regardless of the inputs, the outputs, but default, always land in the current working directory, or the directory specified by `--output_dir`. All three saving methods above will honor this.

Note: This will mark a significant change in behavior of the pipelines and steps.
