### ISSUE TITLE
Cube_build output product meta data

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#691]
Right now the cube_build step only copies the input meta data to the output cube if the input is a single data model, but not if the input is a single FITS file. Populating the output cube meta data properly needs work as part of the more general B7.1 work on cube_build. At the very least, the input meta data should also be copied to the output when the input is a single FITS file. It should also be copied from one of the inputs (say, the first) when the input is a list of files/models from an ASN. In the case of an ASN, the "blendheaders" routine should also be called to collect meta data from all inputs and store it as a table in the output cube. This is related to the work outlined in #603. A decision will need to be as to whether to call "blendheaders" from within cube_build itself, or relegate that work to the calwebb_spec3 pipeline module.

**Comment by jemorrison** [comment]
blend headers for IFUdata will need to wait until 7.2. The MIRI and NIRSPEC teams are creating rules files and Warren is updating blend headers to work with datamodels.

**Comment by jemorrison** [comment]
For Build 7.1 cube_build copies the input meta-data from the first file, but information from the other files is not represented in the output product. This feature has been put into #1350
