### ISSUE TITLE
extract_1d does not recognised upper case in src_type keyword

### ISSUE THREAD

**Issue by PaddyKavanagh** [STScI-JWST/jwst#710]
The src_type step assigns the default value for each instrument, which for MIRI MRS is 'EXTENDED'. However, when extract_1d checks this keyword, it does a string comparison against lower case keywords, which results in 'EXTENDED' not being recognised and the src_type keyword is reset to 'point'.

**Comment by philhodge** [comment]
Thank you!  I'll fix this.

**Comment by philhodge** [comment]
It looks as if the keyword is 'SRCTYPE', rather than 'SRC_TYPE', based on core.schema.yaml.

**Comment by hbushouse** [comment]
Fixed by #711
