### ISSUE TITLE
RELSENS in NIRSpec MSA exposures

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#717]
James Muzerolle reports that testing of the B7 pipeline on a NIRSpec MSA exposure revealed that only 1 RELSENS extension was attached by the photom step during calwebb_spec2 processing, even though there are multiple slits worth of data in the product. This in turn causes the extract_1d step to issue the warning "No relsens for current slit, so can't compute flux" when it's processing all slits but the last (see https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/101478323/comments).

The NIRSpec MSA photom reference file contains a single 1D flux conversion vector (as a function of wavelength) for each allowed filter+grating combination, which is to be applied universally to all slit spectra in an MSA observation, which is likely the reason as to why only one RELSENS extension is being attached by the photom step.

I currently see a couple different ways of addressing this, including:

1) modifying extract_1d to look for only the 1 RELSENS instance and apply it to all spectra in the product

2) modifying photom to attach an identical copy of the RELSENS extension for all slit instances (i.e. one RELSENS included with every SCI, ERR, DQ tuple of the MultiSlit product).

**Comment by philhodge** [comment]
I tried the photom step on a file with NIRSpec MSA data this morning, 
and photom did append a RELSENS extension for each of the (two) slits in 
my test file.

**Comment by hbushouse** [comment]
You're right. This issue was already reported in #567 and fixed by #568. James was running the B7 version, which hadn't been fixed yet. The fix in #568 implemented option 2 above. Closing this issue.
