### ISSUE TITLE
Association Type Definitions: Refactor

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#738]
# Proposal
The current association type definitions are [found in the docs](http://ssb.stsci.edu/doc/jwst_git/docs/associations/html/reference/level3_asn_rules.html#association-types). To better accommodate Level2 associations and make the connection between an association and its related module more obvious, the following is proposed: Make each association type match its corresponding `calwebb_*` name. The example mappings between association type and module would be:

- `spec2` => `calwebb_spec2`
- `image2` => `calwebb_image2`
- `spec3` => `calwebb_spec3`
- `image3` => `calwebb_image3`
- `coron3` => `calwebb_coron3`
- `ami3` => `calwebb_ami`
- `tso3` => `calwebb_tso3`

There are still a few stragglers, but that is not critical.

- `wfs` => `wfs_combine`
- `nrsifu` => `calwebb_spec3` but somehow different because of #240.

**Comment by stscieisenhamer** [comment]
@hbushouse thoughts?

**Comment by hbushouse** [comment]
I think this seems reasonable. I had originally thought of level-2 asn types that were specific to the reason why the data were associated, e.g. a bkg-chop, a bkg-nod, nrs-imprint, etc. But that's more akin to the asn_rule that was used to produce the association. And some associations can be composed of mixtures of more than one of these types, such as a set of NIRSpec background-nod or background-chop exposures that also have an associated imprint (leakcal) exposure. So it's probably just as well to align the asn type with the processing module that will handle it. We don't use the asn_type for anything else downstream, do we? At first we were thinking of using it as part of the output product name, but now we have the standard set of product name types like "i2d", "s3d", etc.

**Comment by stscieisenhamer** [comment]
WRT type representing more closely what the association means: With Level3, this is an advantage. The example is the `nrsifu`. And, in the future, there very possibly will be more of these. So, not being too-tied to the module name is actually a good thing.

WRT Level2: You have touched upon the basic difference between the two associations: Level2 is almost always (when possibly not?) a complete list of the exposures. It is more an accretion-of-knowledge: We "discover" that for an exposure, it has a background, and BTW, this observation is a WFSS one, so we need to add extra members, and...so there really are only the two associations: spectral and image, of which every exposure will fall into one or the other, and may happen to have extra info attached to it

So, the compromise is: leave the Level3 naming scheme as already defined, and just call out the level2 associations as `level2_image` and `level2_spec`.

**Comment by hbushouse** [comment]
I don't see the harm in transforming the level3 types to their corresponding pipeline modules, because each type usually is made up of different kinds of association information. Image3 and Spec3 might always just be a list of members that have to be combined, but coron3 and ami3 will usually also contain PSF members. I'm not sure I see the need for a special 'nrsifu' type. It will still be processed by calwebb_spec3, but will contain some additional logic in the calwebb_spec3 pipeline itself so that it knows to produce combined products for each of the filter+grating combos, as well as a product for all of them together, all of which could easily be specified via defining multiple products (and their members) in the ASN file.

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] Update code
- [ ] Update docs
