### ISSUE TITLE
failing tests in datamodels 

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#74]
I have commented out a few failing tests in datamodels so that we could get a clean run.
These need to be fixed:

test_fits.test_extra_fits
test_fits.test_extra_fits_update
test_schema.test_date
test_schema.test_date2
test_schema.test_list2
test_schema.test_multislit_garbage
test_wcs.test_wcs

**Comment by brechmos-stsci** [comment]
I went through these to see where the issues are.  I created a branch https://github.com/brechmos-stsci/jwst/tree/74_datamodel_tests where I made the changes.  I am not going to create a PR at this point.

Below are things that will need to be discussed at some point ( @nden ).  Not today :-)

**test_extra_fits()**

Not sure if this is what was happening previously. Are these causing the failures?
```
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: 'N/A' is not valid in keyword 'CONT_ID'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: '2011-06-17T02:00:54.193000' is not valid in keyword 'EXPSTART'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: '2011-06-17T02:00:54.193000' is not valid in keyword 'EXPMID'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: '2011-06-17T02:07:56.405000' is not valid in keyword 'EXPEND'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: 'fast' is not valid in keyword 'READPATT'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: '1' is not valid in keyword 'NUMDTHPT'
 warnings.warn(msgfmt.format(result, fits_keyword))
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
```

**test_extra_fits_update()**
Not sure if this is what was happening previously. Are these causing the failures?
```
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: 'N/A' is not valid in keyword 'CONT_ID'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: '2011-06-17T02:00:54.193000' is not valid in keyword 'EXPSTART'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: '2011-06-17T02:00:54.193000' is not valid in keyword 'EXPMID'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: '2011-06-17T02:07:56.405000' is not valid in keyword 'EXPEND'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: 'fast' is not valid in keyword 'READPATT'
 warnings.warn(msgfmt.format(result, fits_keyword))
/Users/crjones/Documents/JWST/jwst/jwst/datamodels/fits_support.py:494: UserWarning: '1' is not valid in keyword 'NUMDTHPT'
 warnings.warn(msgfmt.format(result, fits_keyword))
```

**test_schema.test_date()**
The date is supposed to be a string (at least according to the schema). I added a date validation check in `properties.__setattr__` to make sure the date makes sense by calling `dateutil.parser.parse`.  This now properly returns a ValidationError if it is not correct.

**test_schema.test_date2()**
I changed the check to see if it is a string as the schema appears to want a string.

**test_schema.test_list2()**
This seems to be fine when I run it from within my python environment.

**test_schema.test_multislit_garbage()**
This seems to be fine when I run it from within my python environment.

**test_wcs.test_wcs()**
This seems to be working too, now. There are some warnings but I think they are all right.
```
In [14]: test_wcs()
WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]
WARNING: Some non-standard WCS keywords were excluded: B_0_3, A_1_1, B_ORDER, BP_0_2, A_1_2, A_3_0, B_0_2, AP_0_1, AP_ORDER, BP_2_0, A_ORDER, BP_1_2, AP_0_3, AP_2_0, B_1_1, BP_3_0, B_1_2, AP_3_0, A_2_0, BP_1_1, AP_2_1, BP_0_3, BP_0_1, B_3_0, AP_1_2, BP_ORDER, A_0_2, AP_1_0, AP_0_2, BP_1_0, BP_2_1, AP_1_1, B_2_0, B_2_1, A_2_1, A_0_3 Use the ``relax`` kwarg to control this. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]
```
_Note: There is one line that I needed to comment out as the CRPIX1 is not in the extra_fits.PRIMARY.header. Not sure why on that one._

**Comment by hbushouse** [comment]
All of the UserWarnings from fits_support.py are simply due to the fact that we've changed the expected data types and/or contents of several header keywords since the .fits file being used in the test was created (which is likely many years ago already).

CONT_ID must now be an integer
EXPSTART, EXPMID, and EXPEND must now be floats (in units of MJD)
NUMDTHPT must now be a string (e.g. '1' instead of the integer 1)
READPATT: still a string, but allowed values can be found in core.schema.yaml. FAST is one of the allowed values, but I'm wondering if it's case sensitive?

Simply updating these keyword values in the test .fits file will make the warnings go away.

**Comment by nden** [comment]
This was fixed at some point in build 7.
