### ISSUE TITLE
Improve skymatch documentation

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#741]
INS has requested that more descriptive content be added to the skymatch step docs:

https://jira.stsci.edu/browse/JP-124

**Comment by hbushouse** [comment]
Fixed by #740 #746 and #1053. Closing.

**Comment by hbushouse** [comment]
Additional updates to the skymatch docs have been requested in https://jira.stsci.edu/browse/JP-124. In particular:
```
1. In the Algorithm section the link to the "astrodizle" is broken. Also needs a space after the link
2. Does this step applies to background images only? if it does then please add this to the documentation. If not, add how do you determine it is the sky region
3. In Step Arguments:
  a. The font in the "stepsize" description is larger thatn the rest.
  b. "subtract" has the same problem and also appears in bold
4. In Limitations and Discussion: All the bullet points show with a larger font than the rest.

**Comment by mcara** [comment]
In https://github.com/STScI-JWST/jwst/pull/2084 I have addressed some of the issues described here. 3.a and 4 are invalid. Issue 2 is not very clear and I requested clarification on JIRA. I have expanded `skymatch` documentation based on _those_ comments.
