### ISSUE TITLE
Update calwebb_image2 to take Level2 association as input

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#750]

**Comment by hbushouse** [comment]
It would be good to do this in a way that makes use of commonalities between multiple pipelines, like calwebb_spec2. In other words, refactor things like the "Lvl2Input" function in calwebb_spec2 to make it a generic routine that could live within a common library somewhere (perhaps either within the associations or pipelines sub-packages?) and be used by both calwebb_image2 and calwebb_spec2. It needs to have the capability to handle multiple input use cases, including

1) an ASN file name
2) a single exposure file name
3) a single exposure data model

**Comment by hbushouse** [comment]
This work could also include #687.

**Comment by stscieisenhamer** [comment]
# Implementation

- [ ] Tests
    - [ ] use the TEST_BIGDATA environment as is done on the pandokia tests.
    - [ ] modify the spec2 tests also.
- [ ] `calwebb_image2.py`
    Modify as `calwebb_spec2.py`
- [ ] docs
    - [ ] image2
    - [ ] spec2

**Comment by stscieisenhamer** [comment]
Not sure why closed; must have had a wayward issue number somewhere.
