### ISSUE TITLE
Pathloss wavelength vectors error

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#759]
James Muzerolle reports (https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/101800996/comments):

There is a mistake in the point and uniform source wavelength vectors added to the output file in the pathloss correction step.  The first wavelength value in each should be 0.6 microns, not 0.365 (and the last point should be 5.3).  Looks like this is just an offset problem when reading in the CRPIX/CRVAL keywords from the reference file headers?

**Comment by stscicrawford** [comment]
@stscirij Might want to take a look at this one while looking at the other NIRSPEC model issues as well
