### ISSUE TITLE
NIRISS imaging distortion model needs updating

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#765]
The current NIRISS imaging distortion is broken.

1) The distortion reffile currently in CRDS `jwst_niriss_distortion_0006.asdf` only implements a part of the distortion and scale correction, translating pixel coords to arcsec.  There is no account of the reference pixel in aperture nor the location of that reference pixel in v2v3, nor the parity or the v3yangle.

So while it does have the correct units, it needs significant fixing to work.  These are essentially the same issues that the NIRCam distortion reffile had, and the solutions for fixing them are likely similar.  The current reffile was created by Michael Wolfe based on data from Andre Martel.  It might pay for them to have a chat with Bryan Hilbert on how to go about fixes.

2) On our end, we currently assume the distortion comes in units of arcmin. So we need to remove that scaling factor in our NIRISS `assign_wcs` code.  This is an easy fix and will at least get the (wrong) distortion above into the correct units.

**Comment by nden** [comment]
True. The NIRISS team is aware of these issues and has agreed to rework the files. Same goes for FGS.

**Comment by nden** [comment]
Just to add to this - because of other work the NIRISS team won't be able to provide the new files soon, the deadline for this is early September. Also all instrument teams have agreed to provide reference files wih units of arcsec in V2, V3.

**Comment by jdavies-st** [comment]
Thanks Nadia!  I'll modify the NIRISS imaging for the changes then, which will also solve the issue of wrong units being produced by our code and the current NIRISS imaging distortion reffile.  This will help with testing on our end.

Currently, the FGS distortion files only correct for distortion.  They go from distorted pixels to undistorted pixels, so Science to Ideal frames in SIAF terms.  They contain no scaling to arcsec, no offsets to account for crval_n_ or v2/v3_ref, no rotation to account for v3yangle and no parity.

**Comment by jdavies-st** [comment]
2. above is fixed in #768
