### ISSUE TITLE
Use wcs.bounding_box instead of domain for extract_1d.

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#769]
If the spectral extraction region was not specified, `wcs.domain` is used to specify that region, or to limit the region if the specified slice was too large.  `domain` will be replaced by `bounding_box` in `spacetelescope/gwcs`, however, so the `extract_1d` step must be modified to use `bounding_box`.

**Comment by hbushouse** [comment]
Fixed by #773. Closing.
