### ISSUE TITLE
Use wcs.bounding_box instead of domain for flat_field.

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#770]
The flat_field step uses `wcs.domain` for NIRSpec IFU data (only), to determine the regions over which to apply the flat field.  `domain` will be replaced by `bounding_box` in `spacetelescope/gwcs`, however, so the `flat_field` step must be modified to use `bounding_box`.

**Comment by hbushouse** [comment]
Fixed by #774. Closing.
