### ISSUE TITLE
Extending schemas is broken

### ISSUE THREAD

**Issue by mcara** [STScI-JWST/jwst#788]
The following code used to work fine (sometime ago) but now it crashes:
```python
>>> from jwst import datamodels
>>> im1 = datamodels.ImageModel('image01_1.fits')
2017-04-06 17:50:39,812 - stpipe - WARNING - /.../lib/python2.7/site-packages/asdf/
asdftypes.py:260: UserWarning: 'tag:stsci.edu:jwst_pipeline/v23tosky' with version 0.1.0
found in file, but asdf only understands version 0.7.0.
  warnings.warn(warning_string)

>>> skybg_schema = (
...     "meta.skybg",
...     {
...         "title": "Computed sky background value",
...         "type": "float",
...         "fits_keyword": "SKYBG"
...     }
... )
>>> im1.extend_schema([skybg_schema])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../jwst/jwst/datamodels/model_base.py", line 389, in extend_schema
    self._schema = mschema.flatten_combiners(schema)
  File "/.../jwst/jwst/datamodels/schema.py", line 226, in flatten_combiners
    walk_schema(schema, callback)
  File "/.../jwst/jwst/datamodels/schema.py", line 180, in walk_schema
    recurse(schema, [], None, ctx)
  File "/.../jwst/jwst/datamodels/schema.py", line 162, in recurse
    recurse(sub, path, c, ctx)
  File "/.../jwst/jwst/datamodels/schema.py", line 157, in recurse
    if callback(schema, path, combiner, ctx, recurse):
  File "/.../jwst/jwst/datamodels/schema.py", line 213, in callback
    type = schema.get('type')
AttributeError: 'list' object has no attribute 'get'
>>>
```

CC: @bernie-simon

**Comment by hbushouse** [comment]
In addition to addressing the issue of extend_schema no working, we should also just go ahead and add this keyword entry to the core schema, so that the background matching routines don't have to extend the schema.

**Comment by mcara** [comment]
@hbushouse I am not particularly attached to the 'SKYBG' keyword for indicating computed constant sky background (or depending on parameters, just "matching level" - so maybe BKGLEV, for example, would be better?) and I just used it as an example. If you prefer something more descriptive or better sounding, please let me know.

**Comment by hbushouse** [comment]
Something like BKGLEV seems good to me, because it uses the more generic term "background", which isn't always necessarily indicative of actual signal from the sky (can be telescope/instrument background, for example). Why don't we take advantage of the whopping 8-character limit that FITS allows us and go all out with a name of "BKGLEVEL"?

**Comment by mcara** [comment]
OK.

**Comment by bernie-simon** [comment]
I don't know how things worked in olden times, but extend_schema wants to be passed a dictionary, not a list or tuple. The following code works fine:

```skybg_schema = {
   "meta.skybg":
    {
        "title": "Computed sky background value",
        "type": "float",
        "fits_keyword": "SKYBG"
    }
}
im1.extend_schema(skybg_schema)
```

**Comment by bernie-simon** [comment]
I don't know how things worked in olden times, but extend_schema wants to be passed a dictionary, not a list or tuple. The following code works fine:

```
skybg_schema = {
   "meta.skybg":
    {
        "title": "Computed sky background value",
        "type": "float",
        "fits_keyword": "SKYBG"
    }
}
im1.extend_schema(skybg_schema)
```

**Comment by mcara** [comment]
Old usage may be seen in the old documentation: https://aeon.stsci.edu/ssb/trac/jwst/changeset/2880

**Comment by bernie-simon** [comment]
Okay, I will fix that when I get the time.

**Comment by mcara** [comment]
@bernie-simon No need to fix anything if old usage is no longer supported. I'll just do it the new way.
