### ISSUE TITLE
Check overlap between WCS bounding box and aperture.

### ISSUE THREAD

**Issue by philhodge** [STScI-JWST/jwst#804]
A sanity check needs to be added to the `extract_1d` step to make sure the `wcs.bounding_box` actually overlaps the cutout from which the spectrum is to be extracted.  During the transition from `domain` to `bounding_box`, some files had X and Y limits swapped, and `extract_1d` gave an obscure and misleading error message.

**Comment by hbushouse** [comment]
Fixed by #805.
