### ISSUE TITLE
NIRSpec GWA tilt sensor temperature keyword

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#82]
SDP is currently using the keyword name "GWA_TILT" in the headers of level-1b products that they produce, which contains the temperature of the NIRSpec GWA (grating wheel assembly) tilt sensor. That keyword name will be changing to "GWA_TTIL" to keep it in sync with the name used in the engineering telemetry and the FITS files produced by the FITSWriter for ground test data. Hence we will need to update our core data model schema to use the new form of this keyword name.

**Comment by nden** [comment]
`assign_wcs` should use the new keyword too.

**Comment by hbushouse** [comment]
While the name of the keyword may be changing, we don't necessarily have to change the name of the meta data attribute that gets populated from that keyword value, so as long you're not referencing the keyword directly, the assign_wcs code may not need updating.

**Comment by nden** [comment]
Ah, OK. I'm only using the model attribute, not the keyword.
