### ISSUE TITLE
execute background subtraction before assign_wcs

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#905]
Currently in Spec2Pipeline, and future-related to Image2Pipeline, the background step is executed after assign_wcs. However, there is a check on whether the `assign_wcs` step is skipped, and, if so, the whole pipeline is stopped.

However, is wcs info really needed for background subtraction? If not, the background subtraction step should be moved before the wcs step and check.

**Comment by hbushouse** [comment]
Nope, WCS info is not needed at all for this particular kind of background subtraction. It's just subtracting two images from one another, in detector space. No use of WCS at all. So it would be OK to move it ahead of assign_wcs. The only minor drawback to that is if the user optionally selects to have the intermediate background-subtracted results saved to a file, that file won't have a populated WCS object in it. But probably not a big deal.

**Comment by stscieisenhamer** [comment]
Ahh, then have assign_wcs, then background subtract, then the check on whether assign_wcs happened. so, if there is wcs, background will have it, otherwise not.

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] Spec2Pipeline _see PR #909_
- [ ] Image2Pipeline _see #901_
