### ISSUE TITLE
steps still save results if skipped

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#941]
If a step has been marked to be skipped, but has also been told to save its results, either through specification of `output_file` or `save_results`, it will still save its results.

This is not intuitive and can be misleading.

**Comment by jdavies-st** [comment]
I suspect the desired behavior is to have `skip=True` override any saving?  I.e. if a step is skipped, don't save any results, even if `output_file` and `save_results` are set?

**Comment by hbushouse** [comment]
That would certainly be the behavior that I would expect. If something doesn't execute, there's nothing to be saved (other than a copy of the unmodified input data).

**Comment by jdavies-st** [comment]
Maybe issuing a warning that `save_results` is not being respected if `skip=True` would be the thing to do.  People can then get their .cfg files in order.
