### ISSUE TITLE
stpipe suffix compounds instead of replaces

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#949]
When running a pipeline and using the `--steps.ramp.save_results=True` for a step in the middle of a pipeline, the result is saved as `*_ramp.fits`, but this causes the result of the Sloper pipeline to save the final result of the pipeline as `*_ramp_rate.fits`.  So the suffix is getting passed from the step onward instead of staying only in the step itself, and the final suffix is appending to the end instead of replacing.

So an example:
```
strun jwst.pipeline.SloperPipeline det_image_1_MIRIMAGE_F1500Wexp1.fits --steps.jump.save_results=True
```
produces two outputs named
```
det_image_1_MIRIMAGE_F1500Wexp1_jump.fits
det_image_1_MIRIMAGE_F1500Wexp1_jump_rate.fits
```

The preferred outputs would be
```
det_image_1_MIRIMAGE_F1500Wexp1_jump.fits
det_image_1_MIRIMAGE_F1500Wexp1_rate.fits
```

The following also produces the same, wrongly-named results:
```
strun jwst.pipeline.SloperPipeline det_image_1_MIRIMAGE_F1500Wexp1.fits --save_calibrated_ramp=True
```

**Comment by stscieisenhamer** [comment]
This is due to a quick-fix for the suffix replacement scheme. The original system would blindly replace anything after the last underscore. For pipeline-consistent files, this is OK. But for files named by the public, this would horribly mash the filenames.

The quick-fix is a, very short, list of valid suffix's. This is a bad solution because the list would need be maintained... 🤣 🤣 

But, not other real heuristic would work, so probably should just let the mangling happen and the user-beware.

**Comment by jdavies-st** [comment]
Makes sense.  Perhaps we can add `jump` and `ramp` to our list of valid suffixes used by the pipeline?

**Comment by jdavies-st** [comment]
The `Step.save_model` method used to do a replace of the existing suffix with the new one passed as an argument.  I think that behavior should be restored, but using the [REMOVE_SUFFIX regex](https://github.com/STScI-JWST/jwst/blob/master/jwst/stpipe/step.py#L25).

Is this just as simple as adding the approved suffixes to the regex?

**Comment by stscieisenhamer** [comment]
currently yes, just need to add them to the regex.

**Comment by jdavies-st** [comment]
Perhaps the regex could be generated.  For a pipeline containing steps, all the steps are instantiated at the beginning.  One could query `Step.suffix` for each step and use this list (or a generated regex) to do the checking?

**Comment by stscieisenhamer** [comment]
except that some steps/pipelines dynamically determine suffix. and presumably, the steps being run are on data created by other steps not currently being run, so any initial inputs may have suffixes produced by steps not currently instantiated.

one could use this idea, where each step registers its suffixes. then, as part of the `setup.py install`, a func can be called to find all registered suffixes and save them in some config file.

**Comment by jdavies-st** [comment]
Do these steps with dynamically determined suffix have a default suffix, i.e. when run without optional flags, they produce a single output?  Or is the output suffix determined by input data type?

Would having a suffix defined in `Step.spec` (so `self.suffix` is defined for the step) be a too narrow solution?  Obviously if the step outputs additional, diagnostic output, say for debugging, via optional parameters, that suffix could (and is) hard-coded into the step too.

**Comment by stscieisenhamer** [comment]
determined by data type. Spec2Pipeline and i believe SloperPipeline both have this.  And, for multiple, intermediate products, those are just in the code.
