### ISSUE TITLE
Refactor DataModel.__init__ in light of asdf changes

### ISSUE THREAD

**Issue by drdavella** [STScI-JWST/jwst#986]
The top-level `open` function for opening ASDF files recently changed to provide more flexibility. In addition to accepting 'true' ASDF files, it now also accepts FITS files with ASDF extensions, as well as `HDULists` containing ASDF extensions. This makes the differences in these various inputs transparent to callers.

However, the `__init__` function in `DataModel` expects all inputs except true ASDF files to fail with `ValueError`. The `asdf` module provides a backwards compatibility flag to the `open` function but its sole purpose is as a temporary workaround for this particular case. 

The code in `__init__` should be refactored to handle these various file types appropriately. In particular, it needs to differentiate between pure FITS files and FITS files that contain ASDF extensions since they still must be handled differently. It's possible that `asdf` could provide helper functions to identify file types.

**Comment by bernie-simon** [comment]
I agree that trying to open a file as asdf and then failing over to fits is a fragile way of opening a file in datamodels. I've already switched the generic open to look for the magic cookie at the start of asdf and fits files and will modify the code in model_base to do the same.

**Comment by jdavies-st** [comment]
Is this resolved now?

**Comment by bernie-simon** [comment]
Yes, #1001 addresses it.
