### ISSUE TITLE
Create unique product type names for different flavors of source/photometry catalogs.

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#991]
The various cal pipeline modules currently produce a different flavors of source and/or photometry catalogs, which are stored in ecsv format. The calimage3 source_catalog step produces a source catalog from the combined science image. The caltso3 pipeline will produce a photometry catalog for imaging TSO modes and a "white light" photometry catalog for spectroscopic TSO modes. Each of these different types of catalogs can contain different sets of meta data in their headers (in addition to the portion of the header that simply defines the data columns).

Instrument scientists would like to have the meta data from these catalogs stored in the archive catalog, so that they can be used in searches. In order for the archive catalog ingest to do this for the different sets of meta data that will appear in each of the different catalog types, they will need to have each different catalog type identified using a unique product type file name suffix, so that there's a one-to-one correspondence between the product type suffix and the list of meta data values that need to be ingested into the archive catalog.

Right now all flavors of these catalogs use the "_cat" suffix in their file names. We need to define and implement unique suffixes for each of the 3 different types of catalogs.

**Comment by hbushouse** [comment]
How about the following for new product type names:

1) Source_catalog step output remains _cat (it is a catalog after all)
2) tso_photometry step output becomes _phot (it's just photometry; no catalog info)
3) white_light step output becomes _whtlt (there's no limit to length, but don't want folks to have to type out long strings like "_whitelight")

Thoughts/comments?: @stscieisenhamer @larrybradley @hack

**Comment by hbushouse** [comment]
Hello? (tap, tap, tap) Is this thing on?  Any other comments yay or nay on the proposed new product type names? Otherwise, hearing no objections, I will make it so.

**Comment by larrybradley** [comment]
I updated `tso_photometry` here: https://github.com/STScI-JWST/jwst/pull/1076.
